- CMakeLists.txt
- README.md
- common/cross_sockets/CMakeLists.txt
- common/cross_sockets/xsocket.cpp
- common/cross_sockets/xsocket.h
- game/CMakeLists.txt
- game/kernel/kboot.cpp
- game/kernel/kdsnetm.cpp
- game/kernel/kdsnetm.h
- game/kernel/klisten.cpp
- game/kernel/kmachine.cpp
- game/kernel/ksocket.cpp
- game/runtime.cpp
- game/sce/deci2.cpp
- game/system/Deci2Server.cpp
- game/system/Deci2Server.h
- goalc/CMakeLists.txt
- goalc/listener/CMakeLists.txt
- goalc/listener/Listener.cpp
- goalc/listener/Listener.h
- test/CMakeLists.txt
- test/test_listener_deci2.cpp
This isn't completely working yet, mostly wanted to get the diff.  
Be warned - I deleted the multi Deci2Server tests as per our discussion.  I dug a little bit, and they were failing on the listener trying to connect after the second server was made.
Related to #12
> Fix Listener/Deci2Server on Windows

- CMakeLists.txt
- game/CMakeLists.txt
lets see if it works on windows!
> Update to c++17

- game/system/SystemThread.cpp
- game/system/SystemThread.h
> Remove SystemThread performance stats

- common/type_system/TypeSystem.cpp
- doc/changelog.md
- goal_src/kernel/gkernel-h.gc
- goal_src/kernel/gkernel.gc
- goalc/compiler/Compiler.h
- goalc/compiler/compilation/Atoms.cpp
- goalc/compiler/compilation/Type.cpp
Fix a few small issues from the previous compiler PR
> Add features for gkernel 2

- .gitmodules
- CMakeLists.txt
- test/CMakeLists.txt
- test/test_zydis.cpp
> Add Zydis library for disassembling

- offline_test_git_branch.sh
This adds a default symlink directory.
> Add a default symlink for the Offline test

- decompiler/data/tpage.cpp
This fixes the conversion from rgba16 to rgba32.
I also renamed the function because according to the _GS User Manual, Section 2.3.1_ that _Color Data Format_ it's called `rgba16` and not `rgba15` hope you don't mind.
> Fix and rename rgba16_to_rgba32

- common/type_system/TypeSystem.cpp
- common/type_system/TypeSystem.h
- doc/changelog.md
- goal_src/kernel/gcommon.gc
- goalc/compiler/compilation/Atoms.cpp
- goalc/compiler/compilation/Static.cpp
- goalc/compiler/compilation/Type.cpp
- test/goalc/source_templates/with_game/test-integer-boxed-array.gc
- test/goalc/source_templates/with_game/test-static-boxed-array.gc
- test/goalc/test_with_game.cpp
Add the boxed array type to the compiler.  They can be created on a heap or static.
> Add boxed array type

- common/listener_common.h
- game/kernel/Ptr.h
- game/kernel/kboot.cpp
- game/kernel/kdsnetm.cpp
- game/kernel/kdsnetm.h
- game/kernel/klink.cpp
- game/kernel/klisten.cpp
- game/kernel/kmachine.cpp
- game/kernel/kmalloc.cpp
- game/kernel/kprint.cpp
- game/kernel/kscheme.cpp
- game/main.cpp
- game/overlord/fake_iso.cpp
- game/runtime.cpp
- game/sce/iop.cpp
- game/system/Deci2Server.cpp
- game/system/IOP_Kernel.cpp
- game/system/IOP_Kernel.h
- game/system/SystemThread.cpp
- goalc/listener/Listener.cpp
- goalc/listener/Listener.h
- test/goalc/CMakeLists.txt
- test/goalc/framework/test_runner.cpp
- test/goalc/framework/test_runner.h
- test/goalc/test_game_no_debug.cpp
This will close https://github.com/water111/jak-project/issues/113 and will close https://github.com/water111/jak-project/issues/82
It also cleans up the reset vs. shutdown message and removes all C++ exceptions from runtime C++ code that could be called from GOAL.
> [Runtime] misc fixes to runtime and listener

- .github/workflows/linux-workflow.yaml
- .github/workflows/windows-workflow.yaml
- CMakeLists.txt
- CMakeSettings.json
- README.md
- common/cross_os_debug/xdbg.cpp
- game/kernel/asm_funcs.asm
- game/kernel/kboot.cpp
- game/kernel/kprint.cpp
- test-cov.sh
- test/CMakeLists.txt
- test/test_emitter.cpp
Also added a release variant for MSVC.
Linux builds will now use clang
> Add Address Sanitizer support to MSVC and CMake 

- CMakeSettings.json
- decompiler/CMakeLists.txt
- decompiler/Disasm/Instruction.h
- decompiler/Disasm/InstructionParser.cpp
- decompiler/Disasm/OpcodeInfo.cpp
- decompiler/Function/Function.cpp
- decompiler/Function/Function.h
- decompiler/IR2/AtomicOp.cpp
- decompiler/IR2/AtomicOp.h
- decompiler/IR2/AtomicOpBuilder.cpp
- decompiler/IR2/AtomicOpBuilder.h
- decompiler/ObjectFile/LinkedObjectFile.cpp
- decompiler/ObjectFile/LinkedObjectFile.h
- decompiler/ObjectFile/ObjectFileDB.cpp
- decompiler/ObjectFile/ObjectFileDB.h
- decompiler/ObjectFile/ObjectFileDB_IR2.cpp
- decompiler/config.cpp
- decompiler/config.h
- decompiler/config/jak1_ntsc_black_label.jsonc
- decompiler/main.cpp
- scripts/gen-test-cases.py
- test/decompiler/test_AtomicOpBuilder.cpp
Atomic op conversion is still very much in progress, but we now run the Atomic Op builder on functions and write a disassembly file when the `run_ir2` config flag is set.
> [Decompiler] Write IR2 to file and implement some Atomic Op conversions

- decompiler/IR2/AtomicOp.h
- decompiler/IR2/AtomicOpBuilder.cpp
- test/decompiler/test_AtomicOpBuilder.cpp
And add a test `RegUseDuplication` to make sure it works.
> [Decompiler] Fix register info duplication in IR2

- decompiler/Function/BasicBlocks.h
- decompiler/Function/Function.cpp
- decompiler/Function/Function.h
- decompiler/IR2/AtomicOp.cpp
- decompiler/IR2/AtomicOp.h
- decompiler/IR2/AtomicOpForm.cpp
- decompiler/IR2/AtomicOpTypeAnalysis.cpp
- decompiler/IR2/Env.h
- decompiler/IR2/Form.cpp
- decompiler/IR2/Form.h
- decompiler/IR2/FormExpressionAnalysis.cpp
- decompiler/IR2/FormStack.cpp
- decompiler/IR2/FormStack.h
- decompiler/IR2/IR2_common.h
- decompiler/ObjectFile/ObjectFileDB_IR2.cpp
- decompiler/analysis/atomic_op_builder.cpp
- decompiler/analysis/cfg_builder.cpp
- decompiler/analysis/cfg_builder.h
- decompiler/analysis/expression_build.cpp
- decompiler/analysis/expression_build.h
- decompiler/analysis/reg_usage.cpp
- decompiler/analysis/variable_naming.cpp
- decompiler/analysis/variable_naming.h
- decompiler/util/TP_Type.cpp
- decompiler/util/TP_Type.h
- test/decompiler/FormRegressionTest.cpp
- test/decompiler/test_FormBeforeExpressions.cpp
- test/decompiler/test_FormExpressionBuild.cpp
> [Decompiler] Expression Building

- decompiler/Function/BasicBlocks.cpp
- decompiler/Function/CfgVtx.cpp
- decompiler/Function/CfgVtx.h
- decompiler/IR2/AtomicOp.cpp
- decompiler/IR2/AtomicOp.h
- decompiler/IR2/AtomicOpTypeAnalysis.cpp
- decompiler/IR2/Env.h
- decompiler/IR2/Form.h
- decompiler/ObjectFile/ObjectFileDB_IR2.cpp
- decompiler/analysis/atomic_op_builder.cpp
- decompiler/analysis/cfg_builder.cpp
- decompiler/config/jak1_ntsc_black_label/type_hints.jsonc
- test/decompiler/test_AtomicOpBuilder.cpp
- test/decompiler/test_FormBeforeExpressions.cpp
- test/decompiler/test_FormExpressionBuild.cpp
- test/decompiler/test_FormExpressionBuildLong.cpp
Will close https://github.com/water111/jak-project/issues/236
> [Decompiler] Put likely delay slots in their own block

- goalc/compiler/Compiler.h
- goalc/compiler/IR.cpp
- goalc/compiler/IR.h
- goalc/compiler/compilation/Asm.cpp
- goalc/compiler/compilation/Atoms.cpp
- goalc/compiler/compilation/Math.cpp
- goalc/emitter/IGen.h
- test/goalc/source_templates/with_game/sqrtf.gc
- test/goalc/test_with_game.cpp
- test/test_emitter.cpp
> Add floating point sqrt

- doc/goal_doc.md
- goalc/compiler/Compiler.h
- goalc/compiler/compilation/Atoms.cpp
- goalc/compiler/compilation/CompilerControl.cpp
- goalc/main.cpp
As discussed, a brief help command.  Originally I wanted to do it in GOAL code, but doing it in C++ allows me to print without requiring any setup / better coloring and formatting.  I'll try adding the persistent history next.
> repl: Add a (repl-help) command for forgetful people like me

- decompiler/Function/Function.h
- decompiler/IR2/FormExpressionAnalysis.cpp
- decompiler/ObjectFile/ObjectFileDB.h
- decompiler/ObjectFile/ObjectFileDB_IR2.cpp
- decompiler/analysis/final_output.cpp
- decompiler/analysis/final_output.h
- decompiler/config/jak1_ntsc_black_label/label_types.jsonc
- goalc/compiler/Compiler.cpp
- goalc/compiler/Compiler.h
- goalc/compiler/compilation/CompilerControl.cpp
- goalc/main.cpp
- test/CMakeLists.txt
- test/decompiler/reference/gcommon_REF.gc
- test/decompiler/test_FormExpressionBuild.cpp
- test/offline/CMakeLists.txt
- test/offline/offline_test_main.cpp
- test/test_main.cpp
Adds an offline test framework for the decompiler and runs it on `gcommon`. The test fails because the output can't compile.
> [Decompiler] Add offline tests

- common/CMakeLists.txt
- common/util/DgoReader.cpp
- common/util/FileUtil.cpp
- common/util/FileUtil.h
- decompiler/ObjectFile/ObjectFileDB.cpp
- tools/dgo_unpacker.cpp
Seems to support everything but the early Jak 2 demo.
> [Tools] Support compressed DGOs in the unpacker

- decompiler/config/all-types.gc
- decompiler/config/jak1_ntsc_black_label/var_names.jsonc
- goal_src/engine/gfx/hw/display-h.gc
- goal_src/engine/gfx/hw/gs.gc
> [gs] fill in most of the register types

- goal_src/kernel/gstring.gc
this will be very useful for debugging and just making new strings in general
> Add `string-format` macro for in-place formatted strings

- goalc/compiler/Compiler.cpp
> [repl] Always reset runtime before disconnecting

- common/type_system/TypeSystem.cpp
- common/type_system/TypeSystem.h
- decompiler/Function/CfgVtx.cpp
- decompiler/IR2/Env.cpp
- decompiler/IR2/Env.h
- decompiler/IR2/FormExpressionAnalysis.cpp
- decompiler/IR2/IR2_common.h
- decompiler/ObjectFile/ObjectFileDB_IR2.cpp
- decompiler/analysis/cfg_builder.cpp
- decompiler/util/DecompilerTypeSystem.cpp
- decompiler/util/data_decompile.cpp
- goalc/compiler/Compiler.cpp
- goalc/compiler/Compiler.h
- test/decompiler/FormRegressionTest.cpp
- test/decompiler/reference/all_forward_declarations.gc
- test/decompiler/reference/engine/load/file-io_REF.gc
- test/decompiler/reference/engine/target/target-h_REF.gc
- test/offline/offline_test_main.cpp
Will fix:
- https://github.com/water111/jak-project/issues/450 (failing tests)
- https://github.com/water111/jak-project/issues/417 (no more crashes when decompiling everything)
Will make some progress on https://github.com/water111/jak-project/issues/416 (better errors).
> Clean up some errors/crashes in decompiler

- third-party/fmt/color.h
- third-party/fmt/core.h
- third-party/fmt/format-inl.h
- third-party/fmt/format.cc
- third-party/fmt/format.h
- third-party/fmt/ranges.h
built locally... fingers crossed on tests
> deps: Update {fmt} to `7.1.3` and include `ranges.h` cause its nice

- third-party/11zip/extlibs/minizip/include/minizip/gzguts.h
- third-party/11zip/extlibs/minizip/src/miniunz.c
- third-party/11zip/extlibs/minizip/src/minizip.c
- third-party/11zip/src/zipper.cpp
Fix a few warnings/missing includes and a small memory bug.
> Zip library tweaks

- decompiler/analysis/atomic_op_builder.cpp
- decompiler/analysis/expression_build.cpp
- decompiler/analysis/stack_spill.cpp
> [decompiler] support float stack spills

- decompiler/config/all-types.gc
- decompiler/config/jak1_ntsc_black_label/stack_structures.jsonc
- decompiler/config/jak1_ntsc_black_label/type_casts.jsonc
- goal_src/engine/data/res-h.gc
- goal_src/engine/data/res.gc
- goal_src/engine/geometry/geometry-h.gc
- test/decompiler/reference/engine/data/res-h_REF.gc
> [decomp] yet even more `res`

- .gitignore
- .vs/launch.vs.json
- Taskfile.yml
- tools/MemoryDumpTool/main.cpp
Issue 2 here - https://github.com/water111/jak-project/issues/534
Will output a JSON file with all the type occurrences, as well as append to it on future runs.
> ee-analysis: Output and append to JSON file

- common/type_system/Type.cpp
- common/type_system/Type.h
- common/type_system/TypeSystem.cpp
- common/type_system/TypeSystem.h
- common/type_system/deftype.cpp
- decompiler/config/all-types.gc
- decompiler/util/DecompilerTypeSystem.cpp
- docs/markdown/progress-notes/changelog.md
- goal_src/kernel-defs.gc
- goalc/compiler/compilation/Define.cpp
- goalc/compiler/compilation/Type.cpp
- test/decompiler/reference/all_forward_declarations.gc
- test/test_type_system.cpp
Will fix https://github.com/water111/jak-project/issues/595
> Improve forward declaring types

- common/CMakeLists.txt
- common/audio/audio_formats.cpp
- common/audio/audio_formats.h
- common/util/BinaryReader.h
- decompiler/CMakeLists.txt
- decompiler/ObjectFile/ObjectFileDB.cpp
- decompiler/config.cpp
- decompiler/config.h
- decompiler/config/jak1_ntsc_black_label/inputs.jsonc
- decompiler/data/streamed_audio.cpp
- decompiler/data/streamed_audio.h
- decompiler/main.cpp
Most of this is from before starting this repository. The unpacking takes ~30 seconds (there's ~10 hours of audio!) and is disabled until you set `"audio_dir_file_name": "VAG/VAGDIR.AYB",` in the input config file.
> Add some really old vag file unpacking stuff

- decompiler/IR2/AtomicOp.cpp
- decompiler/IR2/AtomicOp.h
- decompiler/IR2/AtomicOpTypeAnalysis.cpp
- decompiler/IR2/Form.cpp
- decompiler/IR2/Form.h
- decompiler/IR2/FormExpressionAnalysis.cpp
- decompiler/IR2/IR2_common.h
- decompiler/analysis/atomic_op_builder.cpp
- test/decompiler/reference/engine/math/vector-h_REF.gc
Also improves a few error messages that have been confusing in the past.
> [decomp] support vector 4 dot

- Taskfile.yml
- decompiler/IR2/FormExpressionAnalysis.cpp
- decompiler/ObjectFile/ObjectFileDB_IR2.cpp
- scripts/next-decomp-file.py
- scripts/update-goal-src.py
a few script changes that i used when decompiling the latest large batch of files, i'd like them available in master to use until that PR is finished
> tooling: breaking off my tooling changes in the big batch PR so they can be used

- goal_src/engine/entity/relocate.gc
- goal_src/engine/level/level.gc
- goal_src/kernel/gkernel-h.gc
Actor compaction can now be enabled! And it doesn't crash!
> fix actor compaction

- game/graphics/opengl_renderer/tfrag/tfrag_common.cpp
fixes bug where the last few colors might be skipped if the color count is not a multiple of 4.
fixes a bug where colors overflow earlier than in the original implementation due to being a factor of 2 off in the float to int conversion. Now we should match the game exactly for color rounding/clipping/overflow.  This second bug was causing the weird lava tube flashing.
> fix flashing lava in firecanyon

- docs/gh-pages-proj/src/views/Home.vue
fixed and tested here - https://xtvaser.github.io/jak-project/
> docs: fix link to gallery

- decompiler/analysis/mips2c.cpp
- decompiler/config/all-types.gc
- decompiler/config/jak1_ntsc_black_label/hacks.jsonc
- game/CMakeLists.txt
- game/mips2c/functions/collide_mesh.cpp
- game/mips2c/functions/collide_probe.cpp
- game/mips2c/mips2c_private.h
- game/mips2c/mips2c_table.cpp
- goal_src/engine/collide/collide-probe.gc
- goal_src/examples/debug-collide.gc
- test/decompiler/reference/engine/collide/collide-probe_REF.gc
As I suspected, `collide-probe` produces the exact same collide list as the `collide-ray`, but is a faster implementation.
> collide probe works, amazingly

- decompiler/config/all-types.gc
- decompiler/config/jak1_ntsc_black_label/label_types.jsonc
- decompiler/config/jak1_ntsc_black_label/stack_structures.jsonc
- decompiler/config/jak1_ntsc_black_label/type_casts.jsonc
- test/decompiler/reference/engine/gfx/ocean/ocean-vu0_REF.gc
`ocean-near` is not fully decompiled yet (two functions remain) and I'm not 100% confident on everything in it, but I figured I'd put up what I have so far.
> decomp: `ocean-near` and `ocean-vu0`

- decompiler/config/all-types.gc
- decompiler/config/jak1_ntsc_black_label/hacks.jsonc
- decompiler/config/jak1_ntsc_black_label/label_types.jsonc
- decompiler/config/jak1_ntsc_black_label/type_casts.jsonc
- goal_src/engine/gfx/generic/generic-vu0.gc
- goal_src/engine/gfx/shadow/shadow-cpu-h.gc
- test/decompiler/reference/engine/gfx/generic/generic-merc_REF.gc
- test/decompiler/reference/engine/gfx/generic/generic-vu0_REF.gc
- test/decompiler/reference/engine/gfx/generic/generic-vu1_REF.gc
- test/decompiler/reference/engine/gfx/shadow/shadow-vu1_REF.gc
`generic-reset-buffers` is unused and I couldn't figure out the last bit, so I uncommented it in the final output.
> decomp: `generic-merc` | `generic-vu0` | `generic-vu1` | `shadow-vu1`

- game/graphics/opengl_renderer/DirectRenderer.cpp
- game/graphics/opengl_renderer/DirectRenderer.h
- game/graphics/opengl_renderer/GenericRenderer.cpp
- game/graphics/opengl_renderer/GenericRenderer.h
Fixes https://github.com/open-goal/jak-project/issues/1198
I also changed it to avoid binding unused textures, and at least on my computer this made it faster. Final boss went from 16 ms/frame to 13.
> [graphics] Fix texture selection in Direct

- game/graphics/opengl_renderer/DirectRenderer.cpp
- game/graphics/opengl_renderer/DirectRenderer.h
- game/graphics/opengl_renderer/shaders/direct_basic_textured.frag
- game/graphics/opengl_renderer/shaders/direct_basic_textured.vert
> [graphics] fix texturing settings

- game/graphics/opengl_renderer/BucketRenderer.cpp
- game/graphics/opengl_renderer/BucketRenderer.h
- game/graphics/opengl_renderer/EyeRenderer.h
- game/graphics/opengl_renderer/OpenGLRenderer.cpp
- game/graphics/opengl_renderer/OpenGLRenderer.h
- game/graphics/opengl_renderer/TextureUploadHandler.cpp
- game/graphics/opengl_renderer/TextureUploadHandler.h
- game/graphics/texture/TexturePool.cpp
- goal_src/engine/gfx/eye.gc
> [eyes] enable filter by default and fix up bucket hacks

- game/graphics/opengl_renderer/Sprite3.cpp
- game/graphics/opengl_renderer/Sprite3.h
this was less work than expected
> add back direct in sprite

- game/graphics/opengl_renderer/Sprite3.cpp
- game/graphics/opengl_renderer/SpriteRenderer.cpp
- game/graphics/opengl_renderer/shaders/sprite3_3d.vert
- game/graphics/opengl_renderer/shaders/sprite_3d.vert
> [graphics] revert bad change to sprite shader

- decompiler/config/jak1_ntsc_black_label/type_casts.jsonc
- game/graphics/opengl_renderer/ocean/CommonOceanRenderer.cpp
- game/graphics/opengl_renderer/ocean/CommonOceanRenderer.h
- game/graphics/opengl_renderer/ocean/OceanMid.cpp
- game/graphics/opengl_renderer/ocean/OceanMid.h
- game/graphics/opengl_renderer/ocean/OceanMidAndFar.cpp
- game/graphics/opengl_renderer/ocean/OceanMid_PS2.cpp
- game/graphics/opengl_renderer/ocean/OceanNear.cpp
- game/graphics/opengl_renderer/ocean/OceanNear.h
- game/graphics/opengl_renderer/ocean/OceanNear_PS2.cpp
- game/graphics/opengl_renderer/shaders/ocean_common.frag
- goal_src/engine/draw/drawable.gc
- goal_src/engine/gfx/ocean/ocean-mid.gc
saves up to 1 ms in bad ocean places!
also add a missing background draw when the sky is off (happens in lpc)
> [graphics] improve ocean mid speed

- .gitignore
> Add texture replacements to gitignore.

- game/system/newpad.cpp
- goal_src/engine/draw/process-drawable.gc
See https://github.com/open-goal/jak-project/issues/1248 for details on the bug and fix
> [gameplay] fix disappearing boulders

- common/custom_data/TFrag3Data.cpp
- common/custom_data/Tfrag3Data.h
- decompiler/config/all-types.gc
- decompiler/level_extractor/BspHeader.cpp
- decompiler/level_extractor/extract_level.cpp
- decompiler/level_extractor/extract_shrub.cpp
- game/CMakeLists.txt
- game/graphics/opengl_renderer/Loader.cpp
- game/graphics/opengl_renderer/Loader.h
- game/graphics/opengl_renderer/OpenGLRenderer.cpp
- game/graphics/opengl_renderer/Shader.cpp
- game/graphics/opengl_renderer/Shader.h
- game/graphics/opengl_renderer/background/Shrub.cpp
- game/graphics/opengl_renderer/background/Shrub.h
- game/graphics/opengl_renderer/background/Tfrag3.cpp
- game/graphics/opengl_renderer/background/Tie3.cpp
- game/graphics/opengl_renderer/background/Tie3.h
- game/graphics/opengl_renderer/background/background_common.cpp
- game/graphics/opengl_renderer/background/background_common.h
- game/graphics/opengl_renderer/buckets.h
- game/graphics/opengl_renderer/shaders/shrub.frag
- game/graphics/opengl_renderer/shaders/shrub.vert
- goal_src/engine/dma/dma-h.gc
- goal_src/engine/gfx/background-h.gc
- goal_src/engine/gfx/merc/merc.gc
- goal_src/engine/gfx/ocean/ocean.gc
- goal_src/engine/gfx/shrub/shrubbery.gc
- test/decompiler/reference/engine/gfx/merc/merc_REF.gc
- test/decompiler/reference/engine/level/level-h_REF.gc
Remaining todo:
- figure out the "base color" part. The time of day color is definitely working, but there's other vertex colors that I'm not using, and some stuff is clearly wrong (hand rails on bridge too bright, plant boss tentacle dirt too bright...)
- figure out the alpha stuff a bit more. Somehow everything is drawn with alpha blending enabled, but this seems wrong. Also, the plants in the water are bad, but that might just be the next issue.
- hook up the renderer to the buckets, instead of hacking through TIE.
- redo the index stream so we don't have all this (index, index, RESET) crap.
- figure out if the triangle count is accurate, and if so, make sure we aren't drawing everything 2x or something stupid like that
- figure out the messed up shrubs in village2
- implement some …
> [graphics] shrub

- game/overlord/sbank.cpp
> overlord: Fix LookupSoundIndex

- game/overlord/srpc.cpp
- game/overlord/ssound.cpp
Found some decompilation mistakes to fix.
> A few overlord fixes

- docs/progress-notes/changelog.md
- goalc/compiler/IR.cpp
- goalc/compiler/IR.h
- goalc/compiler/compilation/Math.cpp
- test/goalc/source_templates/arithmetic/divide-2.static.gc
- test/goalc/source_templates/arithmetic/divide-signs.static.gc
- test/goalc/source_templates/arithmetic/mod-unsigned.static.gc
- test/goalc/test_arithmetic.cpp
- test/offline/readme.md
Will fix https://github.com/open-goal/jak-project/issues/33
> [goalc] fix mod bug and add div tests

- decompiler/extractor/main.cpp
> [extractor] fix bug with relative path

- common/CMakeLists.txt
- common/util/read_iso_file.cpp
- common/util/read_iso_file.h
- decompiler/extractor/main.cpp
Note that this is currently lacking checks on the ISO.
> [extractor] support ISO files

- game/graphics/sceGraphicsInterface.cpp
- game/overlord/srpc.cpp
- game/overlord/ssound.cpp
Fix a bunch of decompilation mistakes, and implement part of VBlank_Handler.
> Overlord fixes

- goal_src/engine/game/task/process-taskable.gc
> [game] fix flava triggering on nans

- decompiler/ObjectFile/ObjectFileDB.h
- game/graphics/opengl_renderer/shaders/generic.vert
- game/graphics/opengl_renderer/shaders/merc2.frag
- game/graphics/opengl_renderer/shaders/merc2.vert
now the orbs in boggy look right with increased fog
> hook up merc2 to fog intensity, flip some min/max fogs

- game/mips2c/functions/collide_edge_grab.cpp
> [game] prevent NaNs when there's a zero area triangle in edgegrab

- decompiler/config/all-types.gc
- goal_src/levels/jungleb/plant-boss.gc
- test/decompiler/reference/levels/jungleb/plant-boss_REF.gc
> fix `plant-boss` decomp

- game/overlord/dma.cpp
- game/overlord/iso.cpp
- game/overlord/iso_api.cpp
- game/overlord/sbank.cpp
- game/overlord/soundcommon.cpp
- game/overlord/srpc.cpp
- game/overlord/ssound.cpp
- game/sound/989snd/loader.cpp
- game/sound/989snd/sound_handler.h
- game/sound/CMakeLists.txt
- third-party/cubeb/cubeb/CMakeLists.txt
now it compiles on clang with no warnings again!
> fix a few compiler warnings

- common/deserialization/subtitles/subtitles.cpp
- common/nrepl/ReplServer.cpp
- decompiler/config/jak1_ntsc_black_label/type_casts.jsonc
- game/tools/subtitles/subtitle_editor.cpp
- game/tools/subtitles/subtitle_editor.h
Hopefully I didn't break anything in the process.
Closes #1447
> tools: Some subtitle editor cleanup and add hint support

- game/graphics/display.cpp
- game/graphics/display.h
- game/graphics/gfx.cpp
- game/graphics/gfx.h
- game/graphics/pipelines/opengl.cpp
- game/graphics/pipelines/opengl.h
- game/kernel/kmachine.cpp
- goal_src/pc/pckernel-h.gc
- goal_src/pc/pckernel.gc
Moves a lot of useless boilerplate to virtual methods, reworks a bunch of PC graphics code so that the game doesn't launch with the wrong window size.
- Fixes #1459 
- Fixes #1464 
- Fixes #1456
- Fixes #1153 (hopefully)
> a bunch of PC/GFX system fixes

- game/graphics/display.cpp
- game/graphics/display.h
- game/graphics/pipelines/opengl.cpp
- Toggle the ImGui menu bar by pressing Alt
- Hides the menu bar by default in fullscreen and borderless modes
> Add menu bar toggle

- decompiler/extractor/main.cpp
- game/graphics/opengl_renderer/debug_gui.cpp
- goal_src/pc/pckernel-h.gc
- goal_src/pc/pckernel.gc
Fixes #1467 and fixes #1468 .
Also adds a disclaimer to the top bar...
> small fixes

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/enhancement-request.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
Adds GitHub issue templates for bug reports and feature and enhancement requests so people can create more helpful issues.
> issues: add issue templates

- common/custom_data/TFrag3Data.cpp
- game/graphics/pipelines/opengl.cpp
- game/runtime.cpp
The only two files I've noticed so far that cause issues - this leads to permission headaches over on the launcher side
> paths: ensure `imgui` and `game_config` respects the project path

- common/util/compress.h
- third-party/lzokay/lzokay.cpp
Modifies lzokay which I don't like but I'm tired of doing this manually and upstream seems inactive.
> Fix GCC 12 build

- .github/ISSUE_TEMPLATE/bug-report.yml
> github: fix issue with bug report template

- goal_src/engine/game/settings.gc
> fix soundbank loading on black label

- common/goal_constants.h
- game/kernel/kscheme.cpp
- goal_src/engine/game/generic-obs.gc
- goal_src/kernel/gcommon.gc
- test/goalc/test_variables.cpp
- test/test_kernel.cpp
> expand symbol table

- game/assets/jak1/subtitle/subtitle-editor-db.json
- game/tools/subtitles/subtitle_editor.cpp
- game/tools/subtitles/subtitle_editor.h
Adds a bunch of new subtitle settings so they can be arbitrarily played, as well as some UX improvements in the editor (namely, when you play a scene it will reload the db file).
Sage cutscenes suck
> subtitles: add a bunch of new subtitle playing settings

- .vs/launch.vs.json
- game/kernel/jak1/kmachine.cpp
- scripts/batch/gk-release.bat
> disable goal networking when not in debug mode

- decompiler/config/all-types.gc
- goal_src/jak1/engine/gfx/hw/display.gc
- goal_src/jak1/levels/beach/seagull.gc
this probably doesn't fix the crash
> fix seagulls at high fps

- game/overlord/iso.cpp
- game/overlord/iso_api.cpp
- goal_src/jak1/engine/draw/drawable.gc
- goal_src/jak1/engine/load/loader.gc
> fix wrong vag stream playing sometimes

- game/kernel/jak1/kmachine.cpp
- game/kernel/jak2/kmachine.cpp
- game/kernel/jak2/kprint.cpp
- game/kernel/jak2/kscheme.cpp
Nothing too interesting here, I just didn't get to these in the first pass.  I believe this is all the jak 2 ckernel functions, but the majority are untested and there could easily be bugs. Not much testing is possible until we have a compiler though.
> [ckernel] add remaining jak2 functions

- .vs/launch.vs.json
- common/CMakeLists.txt
- common/goos/Interpreter.cpp
- common/util/FileUtil.cpp
- common/util/unicode_util.cpp
- common/util/unicode_util.h
- decompiler/data/TextureDB.cpp
- decompiler/extractor/main.cpp
- decompiler/main.cpp
- game/graphics/pipelines/opengl.cpp
- game/main.cpp
- test/offline/offline_test_main.cpp
- test/test_main.cpp
- third-party/fpng/fpng.cpp
- third-party/stb_image/stb_image.cpp
- third-party/tiny_gltf/tiny_gltf.h
- tools/MemoryDumpTool/main.cpp
- tools/dgo_packer.cpp
- tools/dgo_unpacker.cpp
- tools/level_tools/level_dump/main.cpp
- vendor.yaml
> Fix UTF-8 handling when running the game, env-vars, and setting the project path

- goal_src/jak1/levels/racer_common/target-racer.gc
- Deceleration when holding x + square
- Deceleration when holding square
- Turning/sliding speed
https://github.com/open-goal/jak-project/issues/1499#issue-1277190691
> [high fps] fix target-racer

- game/graphics/display.h
- game/graphics/opengl_renderer/BucketRenderer.h
- game/graphics/opengl_renderer/DirectRenderer.cpp
- game/graphics/opengl_renderer/OpenGLRenderer.cpp
- game/graphics/opengl_renderer/OpenGLRenderer.h
- game/graphics/opengl_renderer/Sprite3.cpp
- game/graphics/opengl_renderer/opengl_utils.cpp
- game/graphics/pipelines/opengl.cpp
This is a pretty big performance increase when msaa is off, and a medium increase when it's on. I can play at 2x on my desktop now, and my laptop is closer to getting 60fps,
> [graphics] some blit optimizations

- game/system/SystemThread.cpp
Helps when looking at debug tools.
> Set thread names of system threads

- Taskfile.yml
- test/decompiler/reference/jak2/kernel/gkernel-h_REF.gc
Builds jak 1 and jak 2 offline tests on every PR (also potentially on master commits...we'll see upon merging).  But PRs are the most important (keep failures from merging).
> Test Jenkins Build and Update Jak 2's Reference Tests

- README.md
Saw that there was a newer how-to video.
> Update intro video in the README.md

- game/overlord/iso_queue.cpp
- game/overlord/srpc.cpp
- game/overlord/ssound.cpp
- game/sce/iop.cpp
- game/sce/iop.h
- game/system/IOP_Kernel.cpp
- game/system/IOP_Kernel.h
These are really only used as locks in jak1, I'm not sure there's even any change in behavior from this. I think we'll want these for jak 2 though.
Might want to give this some testing, I didn't do much tbh.
> Implement IOP semaphores.

- .github/workflows/windows-build-clang.yaml
shame! accidentally removed :(
> ci: add back the windows artifact

- .gitignore
- common/versions.cpp
- common/versions.h
- game/graphics/opengl_renderer/debug_gui.cpp
- game/graphics/opengl_renderer/debug_gui.h
- game/graphics/pipelines/opengl.cpp
Added screenshot hotkey and added a toggle to debug GUI to disable screenshot hotkey #1765
> Added screenshot hotkey

- game/graphics/opengl_renderer/loader/LoaderStages.cpp
- goal_src/jak1/levels/village1/sequence-a-village1.gc
Should fix the crash issues:
https://github.com/open-goal/jak-project/issues/1792 and https://github.com/open-goal/jak-project/issues/1793
> fix tie lod and intro cutscene linux crash

- goal_src/jak1/pc/pckernel-h.gc
hopefully less people complain about lag when first starting up
> use 2x msaa by default instead of 4x

- common/goos/Reader.cpp
should fix es subtitles not compiling on linux
> fix for windows newlines

- README.md
It was written:
> If you the build directory you'll need…
I tried to fix it, hopefully I found the correct wording. Otherwise please let me know what was missing.
> README: update the Docker part

- decompiler/IR2/AtomicOpTypeAnalysis.cpp
- decompiler/types2/ForwardProp.cpp
- decompiler/util/DecompilerTypeSystem.cpp
- goal_src/jak1/engine/util/capture.gc
- goal_src/jak2/engine/debug/debug-sphere.gc
- goal_src/jak2/engine/engine/engines.gc
- goal_src/jak2/engine/game/game-info-h.gc
- goal_src/jak2/engine/gfx/sprite/particles/sparticle-launcher.gc
- goal_src/jak2/engine/load/loader-h.gc
- goal_src/jak2/engine/target/logic-target.gc
- goalc/compiler/compilation/Type.cpp
- test/decompiler/reference/jak1/engine/engine/engines_REF.gc
- test/decompiler/reference/jak1/engine/gfx/capture_REF.gc
- test/decompiler/reference/jak1/engine/sparticle/sparticle-launcher_REF.gc
- test/decompiler/reference/jak1/levels/lavatube/lavatube-obs_REF.gc
- test/decompiler/reference/jak1/levels/robocave/cave-trap_REF.gc
- test/decompiler/reference/jak1/levels/sunken/helix-water_REF.gc
- test/decompiler/reference/jak2/engine/debug/debug-sphere_REF.gc
- test/decompiler/reference/jak2/engine/engine/engines_REF.gc
- test/decompiler/reference/jak2/engine/game/game-info-h_REF.gc
- test/decompiler/reference/jak2/engine/gfx/sprite/particles/sparticle-launcher_REF.gc
- test/decompiler/reference/jak2/engine/load/loader-h_REF.gc
- test/decompiler/reference/jak2/engine/target/logic-target_REF.gc
also make jak 1 and jak 2 behave the same way, to reduce confusion. It wasn't too bad to update jak 1.
> More array special cases

- game/CMakeLists.txt
- game/graphics/opengl_renderer/BucketRenderer.h
- game/graphics/opengl_renderer/OpenGLRenderer.cpp
- game/graphics/opengl_renderer/VisDataHandler.cpp
- game/graphics/opengl_renderer/VisDataHandler.h
- game/graphics/opengl_renderer/background/TFragment.cpp
- game/graphics/opengl_renderer/buckets.h
- goal_src/jak2/engine/gfx/background/background.gc
It works!
Visibility off:
On:
Overall the visibility data looks a lot better than in jak 1.
> [graphics] hook up visibility data for jak 2

- goal_src/jak1/levels/title/title-obs.gc
I think this got removed awhile back, not sure if it was intentional, but thought it was nice to have. Feel free to close if it's not supported for a good reason 👍
> allow daxter/naughtydog intro cutscene skip

- common/type_system/TypeSystem.cpp
- common/type_system/TypeSystem.h
- tools/type_searcher/main.cpp
Useful when you are trying to find a type with atleast a method at a given id.
> tools: add the ability to search by method id

- test/decompiler/FormRegressionTest.cpp
- test/decompiler/FormRegressionTest.h
Not sure why but using the static members here caused a linker error, but they're only used in one place so I just passed them as constants.
> Fix GCC build

- decompiler/config/jak2/inputs.jsonc
- game/sound/989snd/blocksound_handler.cpp
- game/sound/989snd/player.cpp
quick fix for decompiler crash
> format, fix decompiler crash

- game/sound/989snd/blocksound_handler.cpp
- game/sound/989snd/blocksound_handler.h
- game/sound/989snd/sfxblock2.cpp
- game/sound/989snd/sfxgrain.cpp
- game/sound/989snd/sound_handler.h
> Assorted sound fixes

- game/overlord/srpc.cpp
- game/overlord/srpc.h
- game/overlord/ssound.cpp
> Fix EarTrans assignment

- common/util/set_util.h
- goal_src/jak2/game.gp
oops, leads to some very confusing behaviour
> decomp: don't mutate allowed/banned object lists

- decompiler/config/all-types.gc
- game/overlord/srpc.cpp
- game/overlord/srpc.h
- game/overlord/ssound.cpp
- game/overlord/ssound.h
- goal_src/jak1/engine/sound/gsound-h.gc
- goal_src/jak1/engine/sound/gsound.gc
- goal_src/jak1/pc/pckernel.gc
- test/decompiler/reference/jak1/engine/sound/gsound-h_REF.gc
And replace the previous mechanism for mirroring the sound.
> Overlord: mirror sound RPC command

- game/overlord/sbank.cpp
- game/overlord/srpc.cpp
- game/sound/989snd/blocksound_handler.cpp
- game/sound/989snd/blocksound_handler.h
And correctly initialize the volume group for sfx
> Fix sound bank allocation

- goal_src/jak1/levels/jungle/jungle-mirrors.gc
> Make jungle mirrors respect first person camera settings

- goal_src/jak2/levels/dig/dig-obs.gc
was already right, goal src just needed updating.
> dig obs small fix

- goal_src/jak1/engine/gfx/font-h.gc
Commented font colors for easier modding and orientation in the file.
> Font colors comments

- game/graphics/opengl_renderer/OpenGLRenderer.cpp
- game/graphics/pipelines/opengl.cpp
> Fix F2 screenshots

- game/kernel/jak1/kmachine.cpp
- goal_src/jak1/engine/debug/debug.gc
- goal_src/jak1/kernel-defs.gc
This adds a Vaser's ImGUI menu from #2085 to help filter out the clutter on screen to jak 1.
https://cdn.discordapp.com/attachments/877636980912046150/1066922792924225646/2023-01-22_22-29-25.mp4
> Hook Jak 1 into ImGUI actor filter

- goal_src/jak2/engine/gfx/texture/texture.gc
Fixes a bunch of hud textures:
> [jak2] pc-hook for pris texture upload

- game/graphics/opengl_renderer/foreground/Generic2.cpp
- game/graphics/opengl_renderer/foreground/Generic2.h
- game/graphics/opengl_renderer/foreground/Generic2_Build.cpp
fixes the lightning fade out effect seen when jak touches the electric gate.
> [jak2] fix alpha test in lightning

- decompiler/config/jak2/type_casts.jsonc
- decompiler/config/jak2/var_names.jsonc
- goal_src/jak2/levels/drill_platform/drill-spool.gc
- test/decompiler/reference/jak2/levels/drill_platform/drill-spool_REF.gc
> jak2: fix `drill-eggs` crash

- game/graphics/opengl_renderer/OpenGLRenderer.cpp
- game/graphics/opengl_renderer/VisDataHandler.cpp
- goal_src/jak2/engine/gfx/background/background.gc
> set up fog for jak 2

- common/log/log.cpp
- common/util/FileUtil.cpp
- common/util/FileUtil.h
Fixes #1228 (wow only took 1 year)
> rotate log files

- common/log/log.cpp
- common/log/log.h
- common/util/FileUtil.cpp
- common/util/FileUtil.h
- decompiler/extractor/main.cpp
- decompiler/main.cpp
- game/main.cpp
- goalc/main.cpp
- lsp/main.cpp
Fixes both issues mentioned in #2297
> util/file: cleanup log initialization and some file-util functions

- .vs/launch.vs.json
- Taskfile.yml
- common/util/FileUtil.cpp
- game/common/game_common_types.h
- game/kernel/jak2/kmachine.cpp
- game/main.cpp
- game/runtime.cpp
- game/runtime.h
- goalc/main.cpp
- scripts/batch/gk-display.bat
- scripts/batch/gk-release.bat
- scripts/batch/gk.bat
- scripts/batch/gk2-display.bat
- scripts/batch/gk2-noboot.bat
- scripts/shell/boot_game.sh
- scripts/shell/boot_kernel.sh
- scripts/shell/gk.sh
- test/goalc/framework/test_runner.cpp
Reverts open-goal/jak-project#2189
can't figure out how to use the new options yet
> Revert "game: cleanup `gk`'s CLI documentation"

- goal_src/jak1/engine/game/game-save.gc
- goal_src/jak1/engine/load/loader-h.gc
- goal_src/jak1/engine/load/loader.gc
Not really sure if this actually caused any issues in-game, but better safe thatn sorry.
> [jak1] fix concerning `game-save` bug

- game/overlord/iso.cpp
- game/overlord/iso.h
- game/overlord/iso_queue.cpp
- goal_src/jak2/engine/level/level-h.gc
- goal_src/jak2/engine/level/level.gc
- goal_src/jak2/game.gp
> [jak2] double load dgo workaround

- decompiler/ObjectFile/ObjectFileDB.h
> [decompiler] fix crash when no spools are loaded

- goal_src/jak2/engine/load/loader.gc
Recent subtraction compiler bug fix exposed this.
> [jak2] fix speed for spool anim hack

- game/graphics/opengl_renderer/EyeRenderer.cpp
- game/graphics/opengl_renderer/EyeRenderer.h
- game/graphics/opengl_renderer/OpenGLRenderer.cpp
- game/graphics/opengl_renderer/ProgressRenderer.cpp
- game/graphics/opengl_renderer/SkyBlendCPU.cpp
- game/graphics/opengl_renderer/SkyBlendCPU.h
- game/graphics/opengl_renderer/SkyBlendGPU.cpp
- game/graphics/opengl_renderer/SkyBlendGPU.h
- game/graphics/opengl_renderer/ocean/OceanTexture.cpp
- game/graphics/texture/TexturePool.cpp
- game/graphics/texture/TexturePool.h
Accidentally used Jak 1's tpage dir size...
> [jak2] Fix texture page dir offset for jak 2

- game/mips2c/jak2_functions/nav_control.cpp
- goal_src/jak2/engine/target/target2.gc
add -> multiply.
Fixes https://github.com/open-goal/jak-project/issues/2429
> [jak2] fix nav typo

- decompiler/config/jak2/all-types.gc
- decompiler/config/jak2/ntsc_v1/hacks.jsonc
- decompiler/config/jak2/ntsc_v1/label_types.jsonc
- decompiler/config/jak2/ntsc_v1/type_casts.jsonc
- decompiler/data/game_text.cpp
- game/CMakeLists.txt
- game/graphics/opengl_renderer/DirectRenderer.cpp
- game/mips2c/jak2_functions/vortex.cpp
- game/mips2c/mips2c_table.cpp
- goal_src/jak2/engine/draw/drawable.gc
- test/decompiler/reference/jak2/levels/intro/vortex-data_REF.gc
- test/decompiler/reference/jak2/levels/intro/vortex_REF.gc
- test/offline/config/jak2/config.jsonc
Add the vortex renderer. The vortex texture isn't there yet (it uses the same texture as clouds), so it uses a checkerboard. But the colors/vertices seem right.
> [jak2] add vortex renderer

- game/common/game_common_types.h
- game/kernel/common/klisten.cpp
- game/main.cpp
- game/runtime.cpp
- game/runtime.h
- goal_src/jak2/engine/draw/drawable.gc
- goalc/compiler/Compiler.cpp
- goalc/compiler/compilation/CompilerControl.cpp
- goalc/listener/Listener.cpp
- goalc/listener/Listener.h
> fix repl buffer overrun + use a different port for each game version

- goal_src/jak2/levels/mars_tomb/left/chase/tomb-boulder.gc
add a temporary gui-control hack to make boulder chase mission completable
> add a temporary gui-control hack to make boulder chase mission completable

- .github/workflows/linting.yaml
- scripts/ci/check-for-asserts.py
> ci: check for incorrect assert usage in C++ files

- game/graphics/opengl_renderer/OpenGLRenderer.cpp
- game/mips2c/jak2_functions/generic_merc.cpp
Fixes crashes when killing the big spider, killing predator metal heads, and watching the end cutscene. The presursor guy is the wrong color, but I don't have time to look into this today.
> [jak2] fix generic crashes

- goal_src/jak2/levels/temple/mountain-obs.gc
Related to https://github.com/open-goal/jak-project/issues/2509
> g/j2: temporarily disable some `gui-control` code to fix rock avalanche

- goal_src/jak2/engine/ambient/ambient.gc
> d/jak2: temp fix for rewarding orbs from talker speeches

- decompiler/config/jak2/ntsc_v1/hacks.jsonc
- game/graphics/opengl_renderer/OpenGLRenderer.cpp
- game/mips2c/jak2_functions/foreground.cpp
- game/mips2c/mips2c_table.cpp
- goal_src/jak2/engine/gfx/foreground/foreground.gc
- goal_src/jak2/engine/gfx/texture/texture.gc
The skull gem is not moving, but I'm assuming that's a texture animation.
> jak2: fix 3d hud elements not drawing

- game/graphics/gfx.cpp
> settings: handle corrupted json settings files

- game/CMakeLists.txt
I sorted the list of sources on my SDL PR to reduce future merge conflicts, but in the meantime everytime something gets added to it I have a pretty rough set of conflicts to resolve.  Committing this early to preserve my sanity
> cmake: sort `game/CMakeLists.txt` files

- game/graphics/opengl_renderer/ShadowRenderer.cpp
- goal_src/jak1/levels/racer_common/racer-part.gc
- goal_src/jak1/pc/debug/pc-debug-common.gc
- goal_src/jak1/pc/pckernel-common.gc
- goal_src/jak1/pc/pckernel-h.gc
> fix racer hud regression

- goal_src/jak2/levels/forest/pegasus.gc
Regression from #2662 
Closes #2675
> jak2: fix `pegasus` crash

- goal_src/jak2/levels/common/races/race-manager.gc
> jak2: fix race crash

- third-party/SDL/src/video/x11/SDL_x11window.c
- vendor.yaml
Related to https://github.com/libsdl-org/SDL/issues/4216
> sdl2: add back x11 window code fix

- game/mips2c/jak2_functions/joint.cpp
Fixes https://github.com/open-goal/jak-project/issues/2477
(and any other case of bad bones/cspaces when a bone's scale is very small/negative)
> [jak2] joint to bone nan fix

- common/repl/nrepl/ReplServer.cpp
These are kinda interim fixes until I commit to merging hopefully the final socket code cleanup.
> nREPL: fix some logs and some spots where it could get stuck

- game/graphics/opengl_renderer/Warp.cpp
- game/graphics/opengl_renderer/foreground/Generic2.cpp
- game/graphics/opengl_renderer/foreground/Generic2.h
- game/graphics/opengl_renderer/foreground/Generic2_Build.cpp
The warp giftags don't set PRE and seem to rely on fogging being disabled at the start.
> [jak2] fge=0 at the start of warp

- goal_src/jak2/engine/entity/entity.gc
- goal_src/jak2/levels/common/airlock.gc
- goal_src/jak2/pc/debug/entity-debug.gc
- goal_src/jak2/pc/pckernel-impl.gc
- goal_src/jak2/pc/pckernel.gc
open: 150% -> 175%
post-close: 100% -> 175%
> increase airlock open and post-close speed

- decompiler/config/jak2/all-types.gc
- goal_src/jak2/engine/physics/rigid-body.gc
- goal_src/jak2/levels/dig/dig-obs.gc
- goal_src/jak2/levels/dig/dig3-obs.gc
- goal_src/jak2/levels/stadium/stadium-obs.gc
- test/decompiler/reference/jak2/engine/physics/rigid-body_REF.gc
- test/decompiler/reference/jak2/levels/dig/dig-obs_REF.gc
- test/decompiler/reference/jak2/levels/dig/dig3-obs_REF.gc
- test/decompiler/reference/jak2/levels/stadium/stadium-obs_REF.gc
> jak2: fix `rigid-body-object-event-handler` type

- common/serialization/subtitles/subtitles_ser.cpp
- common/serialization/subtitles/subtitles_ser.h
- goal_src/jak1/pc/subtitle.gc
- goalc/compiler/Compiler.cpp
- goalc/compiler/compilation/Macro.cpp
There is one instance of the same hint being played for different IDs which was breaking things.
> fix some jak 1 hint subtitles not showing up

- common/listener_common.h
- game/kernel/jak1/klisten.cpp
- game/kernel/jak2/klisten.cpp
Found 3 instances, corrected all at once. Let me know if this needs more.
> Typo fix LTT_MSG_INSEPCT

- goal_src/jak2/pc/debug/vag-player.gc
- goal_src/jak2/pc/subtitle2.gc
There was a regression recently that caused this.
> fix vag player not really working

- game/graphics/pipelines/opengl.cpp
- game/kernel/jak2/kmachine.cpp
- game/system/hid/devices/mouse.h
- game/system/hid/display_manager.h
- goal_src/jak2/engine/ps2/pad.gc
Not sure if this is the best way to go about it.
Fixes #2259
> fix mouse mispositioning when letterboxed

- game/graphics/opengl_renderer/OpenGLRenderer.cpp
- game/graphics/opengl_renderer/TextureAnimator.cpp
- game/graphics/opengl_renderer/TextureAnimator.h
- game/graphics/opengl_renderer/TextureUploadHandler.cpp
- game/overlord/jak1/ramdisk.cpp
Fixes skull gems using a low resolution texture.
Fixes issue where jak in cutscenes is dark after watching oracle-level-1 (and likely other bugs with texture animations getting stuck)
> [jak2] Fix dark jak anim and low res skull gems

- goal_src/jak1/engine/entity/entity.gc
- goal_src/jak1/engine/level/level.gc
- goal_src/jak1/pc/debug/default-menu-pc.gc
- goal_src/jak1/pc/features/speedruns.gc
- goal_src/jak1/pc/pckernel-common.gc
- goal_src/jak1/pc/pckernel-h.gc
- goal_src/jak1/pc/progress-pc.gc
- goal_src/jak2/engine/entity/entity.gc
- goal_src/jak2/pc/debug/default-menu-pc.gc
> `force-actors?` -> `ps2-actor-vis?`

- game/kernel/common/kmachine.cpp
> fix collision renderer filters not working

- game/system/hid/devices/keyboard.cpp
- game/system/hid/input_manager.cpp
Fixes #2893 
Careless copy-paste mistake
> input: fix double press issue when assigning a bind

- game/graphics/opengl_renderer/sprite/GlowRenderer.cpp
Now you can be blinded by the sun:
> [glow] fix clipping bug

- decompiler/data/TextureDB.cpp
- decompiler/data/TextureDB.h
- decompiler/level_extractor/extract_tie.cpp
Fixes texture difference shown in issue https://github.com/open-goal/jak-project/issues/2908
> handle texture of 0 in extract_tie

- game/graphics/opengl_renderer/DirectRenderer.cpp
- game/graphics/opengl_renderer/DirectRenderer.h
- game/graphics/opengl_renderer/OpenGLRenderer.cpp
- game/graphics/opengl_renderer/TextureAnimator.cpp
- game/graphics/opengl_renderer/TextureAnimator.h
- game/graphics/opengl_renderer/TextureUploadHandler.cpp
- goal_src/jak2/engine/scene/scene.gc
> [jak2] Support Japanese Subtitles

- common/goos/Interpreter.cpp
- common/goos/Interpreter.h
- decompiler/extractor/extractor_util.hpp
- decompiler/extractor/main.cpp
- game/kernel/common/kboot.h
- goal_src/goal-lib.gc
- goal_src/goos-lib.gs
- goal_src/jak1/compiler-setup.gc
- goal_src/jak1/engine/game/main.gc
- goal_src/jak1/engine/game/settings.gc
- goal_src/jak1/pc/pckernel-h.gc
- goal_src/jak1/pc/pckernel-impl.gc
- goal_src/jak2/engine/ps2/pad.gc
- goal_src/jak2/pc/debug/default-menu-pc.gc
- goalc/make/MakeSystem.cpp
- goalc/make/MakeSystem.h
Also fixes a minor issue where the JP sound bank wouldn't work (Jak 1).
Fixes #2793
> [extractor] fix territory being set to wrong value

- decompiler/level_extractor/fr3_to_gltf.cpp
Export models with "wind".  The levels with wind models are:
firecanyon (9), beach (5), village1 (7), lavatube (2).
Sometimes a single object is made up of multiple models - for example the tree in sandover is actually several meshes.
> [gltf export] Export TIE wind models

- decompiler/level_extractor/fr3_to_gltf.cpp
Fix a bug where meshes are extracted too many times.
> [jak1] Fix duplicated tie extract

- decompiler/level_extractor/BspHeader.cpp
- decompiler/level_extractor/BspHeader.h
- decompiler/level_extractor/extract_collide_frags.cpp
- decompiler/level_extractor/extract_collide_frags.h
- decompiler/level_extractor/extract_level.cpp
- docs/progress-notes/jak2/debug_collide_stuff.md
- game/graphics/opengl_renderer/shaders/collision.vert
> [jak 2] Export the collision mesh

- game/assets/jak2/game_subtitle.gp
- game/assets/jak2/subtitle/subtitle_lines_de-DE.json
- game/assets/jak2/subtitle/subtitle_lines_en-GB.json
- game/assets/jak2/subtitle/subtitle_lines_es-ES.json
- game/assets/jak2/subtitle/subtitle_lines_fr-FR.json
- game/assets/jak2/subtitle/subtitle_lines_it-IT.json
- game/assets/jak2/subtitle/subtitle_lines_ko-KR.json
- game/assets/jak2/subtitle/subtitle_meta_de-DE.json
- game/assets/jak2/subtitle/subtitle_meta_en-GB.json
- game/assets/jak2/subtitle/subtitle_meta_es-ES.json
- game/assets/jak2/subtitle/subtitle_meta_fr-FR.json
- game/assets/jak2/subtitle/subtitle_meta_it-IT.json
- game/assets/jak2/subtitle/subtitle_meta_ko-KR.json
> [jak2] placeholder subtitle files

- decompiler/analysis/variable_naming.cpp
- goal_src/jak2/levels/nest/boss/metalkor-states.gc
- test/decompiler/reference/jak2/levels/nest/boss/metalkor-states_REF.gc
> jak2: fix `metalkor` regression

- game/graphics/opengl_renderer/loader/Loader.cpp
- goal_src/jak1/engine/game/settings.gc
- goal_src/jak1/engine/ps2/pad.gc
- goal_src/jak1/pc/debug/default-menu-pc.gc
- goal_src/jak1/pc/progress-pc.gc
- goalc/compiler/IR.cpp
- goalc/compiler/compilation/ControlFlow.cpp
Fixes #2235 
Fixes #2236 
Fixes #2963 
Fixes #3027
> misc low hanging fruit fixes

- game/mips2c/jak2_functions/font.cpp
- goal_src/jak1/pc/debug/default-menu-pc.gc
- goal_src/jak1/pc/pckernel-common.gc
- goal_src/jak1/pc/pckernel-h.gc
- goal_src/jak2/engine/debug/debug.gc
- goal_src/jak2/engine/debug/menu.gc
- goal_src/jak2/engine/gfx/font.gc
- goal_src/jak2/engine/gfx/hw/video-h.gc
- goal_src/jak2/engine/level/region.gc
- goal_src/jak2/pc/debug/default-menu-pc.gc
- goal_src/jak2/pc/debug/entity-debug.gc
- goal_src/jak2/pc/debug/pc-debug-methods.gc
- goal_src/jak2/pc/pckernel-impl.gc
also hides empty (no commands) regions from the viewers by default now.
>  [jak2] scalable debug font + fix debug menu widescreen bugs 

- common/goos/Interpreter.cpp
- common/repl/util.cpp
- game/kernel/jak2/kboot.cpp
- game/main.cpp
- game/runtime.cpp
- game/sce/sif_ee.cpp
- goal_src/goal-lib.gc
- goal_src/jak1/kernel-defs.gc
> [jak2] fully implement `*user*`

- game/graphics/opengl_renderer/OpenGLRenderer.cpp
- game/graphics/opengl_renderer/sprite/GlowRenderer.cpp
> [glow] potentially fix bad glow texture

- CMakeLists.txt
> ci: properly statically link on macOS

- goal_src/jak2/pc/features/speedruns-h.gc
- goal_src/jak2/pc/features/speedruns.gc
> g/jak2: allow `L1 + R1 + Start` to open speedrun menu as well

- goal_src/jak2/pc/features/speedruns.gc
> g/jak2: disable speech volume when starting a new speedrun

- goal_src/jak2/engine/target/board/target-board.gc
> g/j2: use the large font for the jetboard trick combo display

- game/kernel/jak2/kprint.cpp
> [jak2] better handling of invalid `format`s

- goal_src/jak2/engine/gfx/foreground/foreground.gc
- goal_src/jak2/engine/gfx/hw/display.gc
- goal_src/jak2/engine/ui/hud-classes.gc
- goal_src/jak2/engine/ui/minimap.gc
- goal_src/jak2/levels/drill/ginsu.gc
- Texscroll speed
- Minimap wanted flash speed
- Minimap flashing icons speed (e.g. escort kid)
- Ginsu ambush speed
Fixes #3174, fixes #3172
> jak2: some high fps fixes

- game/kernel/common/kmachine.cpp
- game/system/hid/input_manager.cpp
- game/system/hid/input_manager.h
- goal_src/jak2/kernel-defs.gc
- goal_src/jak2/pc/progress/progress-static-pc.gc
Fixes #3129.
I can't test the last commit, and because this is my first contribution here, I may have made a mistake.
> [jak2] Fix "Select controller"

- goal_src/jak2/engine/ps2/pad.gc
> [jak2] Support STICK_DEADZONE

- goal_src/jak2/engine/nav/nav-enemy.gc
- goal_src/jak2/engine/target/mech/grunt-mech.gc
- goal_src/jak2/levels/castle/boss/castle-baron.gc
- goal_src/jak2/levels/castle/roboguard-level.gc
- goal_src/jak2/levels/city/kiddogescort/crocesc-states.gc
- goal_src/jak2/levels/city/kiddogescort/kidesc-states.gc
- goal_src/jak2/levels/city/traffic/citizen/civilian.gc
- goal_src/jak2/levels/common/enemy/fodder/fodder.gc
- goal_src/jak2/levels/common/enemy/metalmonk.gc
- goal_src/jak2/levels/common/enemy/spyder.gc
- goal_src/jak2/levels/common/entities/spydroid.gc
- goal_src/jak2/levels/mountain/rhino.gc
- goal_src/jak2/levels/nest/mantis.gc
> [jak2] fix use-after-free bug in nav enemies

- goal_src/jak2/levels/city/traffic/vehicle/vehicle.gc
- goal_src/jak2/pc/damage-number.gc
> [jak2] fix health bar color fading

- game/kernel/jak2/kdgo.cpp
- game/overlord/common/srpc.cpp
- game/runtime.cpp
- game/sound/989snd/ame_handler.cpp
- game/sound/989snd/ame_handler.h
- game/sound/989snd/blocksound_handler.cpp
- game/sound/989snd/midi_handler.cpp
- game/sound/989snd/midi_handler.h
- game/sound/989snd/musicbank.cpp
- game/sound/989snd/musicbank.h
- game/sound/989snd/player.cpp
- game/sound/989snd/player.h
- game/sound/989snd/sfxblock.cpp
- game/sound/989snd/sfxblock.h
- game/sound/989snd/sndplay.cpp
- game/sound/989snd/soundbank.h
- game/sound/989snd/vagvoice.cpp
- game/sound/989snd/vagvoice.h
- game/sound/sndshim.cpp
Fix for https://github.com/open-goal/jak-project/issues/3244
> [jak2] Fix unicode issue with GAME.CGO load

- game/kernel/jak2/kmachine.cpp
Boards that have no runs yet look kinda awkward but i'd rather just wait until those fill out (won't take long) rather than add another string to be translated.
> g/j2: switch to OpenGOAL speedrun.com leaderboards

- goalc/build_level/common/gltf_mesh_extract.cpp
> Impr: Make mesh extract compatible with gLTF 2.0 (and Blender 4.0)

- game/overlord/common/ssound.cpp
- game/overlord/common/ssound.h
- game/overlord/jak1/iso.cpp
- game/overlord/jak1/ssound.cpp
- game/overlord/jak1/ssound.h
- game/overlord/jak2/dma.cpp
- game/overlord/jak2/iso.cpp
- game/overlord/jak2/iso_api.cpp
- game/overlord/jak2/spustreams.cpp
- game/overlord/jak2/srpc.cpp
- game/overlord/jak2/ssound.cpp
- game/overlord/jak2/ssound.h
- game/overlord/jak2/stream.cpp
- game/overlord/jak2/streamlist.cpp
- game/overlord/jak2/streamlist.h
- game/overlord/jak2/vag.cpp
- game/overlord/jak2/vag.h
- game/sound/sdshim.cpp
- game/sound/sdshim.h
Some cleanup of vag related functions in overlord.
> j2-overlord: Clean up some VAG functions

- decompiler/level_extractor/extract_collide_frags.cpp
- decompiler/level_extractor/extract_collide_frags.h
- decompiler/level_extractor/extract_level.cpp
> Support extracting collision to obj for jak2/3 formats

- game/overlord/common/ssound.cpp
- game/overlord/jak2/srpc.cpp
> [jak2] fully implement PLAYER `set-param` for VAG streams + fix regression

- decompiler/config/jak3/ntsc_v1/var_names.jsonc
- lsp/state/workspace.cpp
- lsp/state/workspace.h
> lsp: flag unnamed variables in IR files

- decompiler/config/jak3/all-types.gc
- decompiler/config/jak3/ntsc_v1/type_casts.jsonc
- decompiler/config/jak3/ntsc_v1/var_names.jsonc
- goal_src/jak3/engine/gfx/blit-displays-h.gc
- goal_src/jak3/engine/gfx/texture/texture-anim-h.gc
- goal_src/jak3/engine/gfx/texture/texture-h.gc
- goal_src/jak3/engine/gfx/vu1-user-h.gc
- goal_src/jak3/engine/level/level-h.gc
- goal_src/jak3/engine/ui/bigmap-h.gc
- test/decompiler/reference/jak3/decompiler-macros.gc
- test/decompiler/reference/jak3/engine/gfx/texture/texture-h_REF.gc
- test/decompiler/reference/jak3/engine/gfx/texture/texture_REF.gc
- test/decompiler/reference/jak3/engine/level/level-h_REF.gc
- test/offline/config/jak3/config.jsonc
For now - just a plain decompilation, with no PC port changes. I think it'll be easier to do those once we have a little bit more decompiled.
> [jak3] decompile (but not port) texture

- decompiler/analysis/insert_lets.cpp
- decompiler/config/jak3/all-types.gc
- decompiler/config/jak3/ntsc_v1/anonymous_function_types.jsonc
- decompiler/config/jak3/ntsc_v1/stack_structures.jsonc
- decompiler/config/jak3/ntsc_v1/type_casts.jsonc
- decompiler/config/jak3/ntsc_v1/var_names.jsonc
- goal_src/jak3/engine/camera/cam-interface-h.gc
- goal_src/jak3/engine/game/effect-control-h.gc
- goal_src/jak3/engine/game/game-info-h.gc
- goal_src/jak3/engine/game/main-h.gc
- goal_src/jak3/engine/game/settings-h.gc
- goal_src/jak3/engine/load/load-dgo.gc
- goal_src/jak3/engine/load/ramdisk.gc
- goal_src/jak3/engine/sound/gsound-h.gc
- goal_src/jak3/engine/target/target-h.gc
- goal_src/jak3/engine/ui/progress/progress-h.gc
- goal_src/jak3/kernel/gstate.gc
- test/decompiler/reference/jak3/decompiler-macros.gc
- test/decompiler/reference/jak3/engine/game/game-info-h_REF.gc
- test/decompiler/reference/jak3/engine/game/settings-h_REF.gc
- test/decompiler/reference/jak3/engine/load/load-dgo_REF.gc
- test/decompiler/reference/jak3/engine/load/ramdisk_REF.gc
- test/decompiler/reference/jak3/engine/sound/gsound-h_REF.gc
- test/decompiler/reference/jak3/engine/sound/gsound_REF.gc
> [jak3] decomp gsound

- goal_src/jak2/engine/game/game-save.gc
- goal_src/jak2/pc/pckernel.gc
> jak2 pckernel: save `pc-settings` on cheat progress and regular auto-saves

- game/system/hid/devices/mouse.cpp
- game/system/hid/devices/mouse.h
- game/system/hid/display_manager.cpp
- goal_src/jak2/pc/progress/progress-static-pc.gc
> Fix issues with camera movement with controller when mouse tracking is also enabled

- decompiler/analysis/insert_lets.cpp
- decompiler/config/jak3/all-types.gc
- decompiler/config/jak3/ntsc_v1/type_casts.jsonc
- game/graphics/opengl_renderer/sprite/Sprite3.cpp
- goal_src/jak3/engine/dma/dma-buffer.gc
- goal_src/jak3/engine/gfx/sprite/simple-sprite-h.gc
- goal_src/jak3/engine/gfx/sprite/sprite-h.gc
- goal_src/jak3/engine/gfx/vu1-user-h.gc
- test/decompiler/reference/jak3/decompiler-macros.gc
- test/decompiler/reference/jak3/engine/gfx/sprite/simple-sprite-h_REF.gc
- test/decompiler/reference/jak3/engine/gfx/sprite/sprite-h_REF.gc
- test/decompiler/reference/jak3/engine/gfx/sprite/sprite_REF.gc
- test/offline/config/jak3/config.jsonc
Decompile `sprite.gc`. Also update the DMA macro for a small change in Jak 3: a check to see if nothing was added to the bucket.
> [jak3] Decompile sprite

- goal_src/jak2/pc/features/autosplit.gc
- goal_src/jak2/pc/features/speedruns.gc
- goal_src/jak2/pc/pckernel.gc
> Fix minor issues related to the speedrunner mode menu, also stop saving the `pc-settings` every frame when sr mode is on

- goal_src/jak3/engine/gfx/sprite/sprite.gc
- test/goalc/test_type_consistency.cpp
Make this test run in CI as the game is not done yet, CI in master is failing because something was missed (forward declaration)
> d/j3: ensure type-tests pass

- decompiler/config/jak3/ntsc_v1/inputs.jsonc
Now needed to extract and compile from scratch
> Intro palace DGOs

- common/serialization/subtitles/subtitles_v2.cpp
- decompiler/config/jak3/ntsc_v1/inputs.jsonc
- decompiler/config/jak3/ntsc_v1/stack_structures.jsonc
- decompiler/config/jak3/ntsc_v1/type_casts.jsonc
- game/assets/jak2/subtitle/subtitle_lines_ca-ES.json
- game/assets/jak2/subtitle/subtitle_lines_da-DK.json
- game/assets/jak2/subtitle/subtitle_lines_de-DE.json
- game/assets/jak2/subtitle/subtitle_lines_en-GB.json
- game/assets/jak2/subtitle/subtitle_lines_en-US.json
- game/assets/jak2/subtitle/subtitle_lines_es-ES.json
- game/assets/jak2/subtitle/subtitle_lines_fi-FI.json
- game/assets/jak2/subtitle/subtitle_lines_fr-FR.json
- game/assets/jak2/subtitle/subtitle_lines_hu-HU.json
- game/assets/jak2/subtitle/subtitle_lines_is-IS.json
- game/assets/jak2/subtitle/subtitle_lines_it-IT.json
- game/assets/jak2/subtitle/subtitle_lines_ja-JP.json
- game/assets/jak2/subtitle/subtitle_lines_jp-JP.json
- game/assets/jak2/subtitle/subtitle_lines_ko-KR.json
- game/assets/jak2/subtitle/subtitle_lines_lt-LT.json
- game/assets/jak2/subtitle/subtitle_lines_nl-NL.json
- game/assets/jak2/subtitle/subtitle_lines_no-NO.json
- game/assets/jak2/subtitle/subtitle_lines_pl-PL.json
- game/assets/jak2/subtitle/subtitle_lines_pt-BR.json
- game/assets/jak2/subtitle/subtitle_lines_pt-PT.json
- game/assets/jak2/subtitle/subtitle_lines_sv-SE.json
- goal_src/jak2/pc/subtitle2-h.gc
- goalc/build_level/common/build_level.h
for specific cutscene scenarios
> [jak2] new subtitle speakers

- game/assets/jak2/subtitle/subtitle_lines_fr-FR.json
Fixed several translation errors
> Jak 2 3rd update subtitle_lines_fr-FR.json

- decompiler/config/jak3/all-types.gc
- goal_src/jak3/levels/desert/des-bush.gc
- test/decompiler/reference/jak3/levels/desert/des-bush_REF.gc
> jak3: fix `bbush` rings

- decompiler/config/jak3/all-types.gc
- game/graphics/opengl_renderer/foreground/Generic2.cpp
- game/graphics/opengl_renderer/foreground/Generic2_Build.cpp
- goal_src/jak3/engine/entity/entity-h.gc
- goalc/compiler/compilation/Static.cpp
- test/decompiler/reference/jak3/engine/entity/entity-h_REF.gc
- test/decompiler/reference/jak3/engine/entity/entity-table_REF.gc
Fix issue where light-trail is invisible and some actors not spawning due to out of memory.
> [jak3] Fix alpha for prims, entity-table

- game/graphics/opengl_renderer/OpenGLRenderer.cpp
> jak3: add more prim buckets

- goal_src/jak2/engine/ui/hud.gc
> g/j2: fix hud positioning when in mirror mode

- docker/Ubuntu/Dockerfile
adds libssl-dev to apt-get
i atleast had to add this for the docker image to work
> ubuntu Dockerfile fix a missing dependency

- decompiler/config/jak2/all-types.gc
- game/assets/jak2/text/game_custom_text_en-US.json
- goal_src/jak2/engine/ui/text-id-h.gc
- goal_src/jak2/pc/pckernel-impl.gc
- goal_src/jak2/pc/pckernel.gc
- goal_src/jak2/pc/progress/progress-static-pc.gc
- goal_src/jak2/pc/subtitle2.gc
> g/j2: Fix subtitle setting persisting and add a toggle for the hint subtitles

- game/graphics/opengl_renderer/foreground/Merc2.cpp
- game/graphics/opengl_renderer/foreground/Merc2.h
- game/graphics/opengl_renderer/shaders/merc2.frag
- game/graphics/opengl_renderer/shaders/merc2.vert
- goal_src/jak3/engine/gfx/foreground/foreground.gc
Fixes https://github.com/open-goal/jak-project/issues/3709
https://github.com/user-attachments/assets/9fadf624-60b8-460f-9887-693712cc36c0
> [jak3] Add merc fade and support for no texture flag

- goal_src/jak2/engine/target/target-turret.gc
> g/j2: make the turret controls respect the camera settings

- LICENSE
- iso_data/.gitignore
- iso_data/jak2/.gitignore
- iso_data/jak3/.gitignore
- Updates the LICENSE
- Adds empty Jak 2/3 folders to iso_data following the pattern established by the jak1 folder.
> Update LICENSE, and add jak 2/3 iso_data folders

- game/assets/sdl_controller_db.txt
> CI: Periodic Controller Database Update

- common/formatter/rules/rule_config.cpp
- common/util/gltf_util.cpp
- game/kernel/common/kmachine.cpp
- game/kernel/jak2/kmachine.cpp
- game/kernel/jak2/kmachine_extras.cpp
- game/kernel/jak3/kmachine.cpp
- game/kernel/jak3/kmachine_extras.cpp
- goal_src/jak1/kernel-defs.gc
Also adds formatter rules for a couple of macros.
> game: move `pc-encode-utf8-string` to common `kmachine` code

- decompiler/config/jak3/ntsc_v1/stack_structures.jsonc
- goal_src/jak3/levels/desert/wvehicle/was-squad-control.gc
- test/decompiler/reference/jak3/levels/desert/wvehicle/was-squad-control_REF.gc
Fix for cars spawning under ground or in weird places
> [jak3] Fix stack layout for car spawn

- goal_src/jak2/engine/gfx/sky/sky-tng.gc
- goal_src/jak3/engine/gfx/sky/sky-tng.gc
Fix the issue where the moon gets wide when using PC aspect ratios
> [jak2, jak3] Unstretch moon and sun

- common/util/os.cpp
- common/util/os.h
- game/main.cpp
Related to https://github.com/open-goal/launcher/pull/664
Likely Fixes https://github.com/open-goal/launcher/issues/663
> macos: don't assume that all macOS major versions are simple numeric values

- game/graphics/opengl_renderer/Shader.cpp
- game/graphics/opengl_renderer/Shader.h
- game/graphics/opengl_renderer/background/Tie3.cpp
- game/graphics/opengl_renderer/shaders/tie_wind.frag
- game/graphics/opengl_renderer/shaders/tie_wind.vert
I accidentally broke this with the camera matrix improvements, but it's fixed now.
> [jak1] Fix wind

- game/overlord/jak3/dvd_driver.cpp
- game/overlord/jak3/dvd_driver.h
- game/overlord/jak3/iso_cd.cpp
- game/overlord/jak3/isocommon.h
Try to avoid crashes/corruption if a file changes size after you've started the game.
> [jak3] Improve overlord file size handling

- decompiler/extractor/extractor_util.cpp
Fixes the other Jak II hashes after the fix in https://github.com/open-goal/jak-project/pull/3937
> Fix Jak II ISO hashes

- game/overlord/jak2/iso.cpp
- game/overlord/jak3/iso.cpp
- game/overlord/jak3/iso_api.cpp
- game/overlord/jak3/iso_cd.cpp
- game/overlord/jak3/stream.cpp
removing some print statements left over from debugging.
> remove some spammy overlord prints

- game/kernel/common/kprint.h
Fix for the crash reported in https://github.com/open-goal/jak-project/issues/4034
> Increase print buffer size
