open-goal/jak-project

.github/workflows/workflow.yaml, CMakeLists.txt, README.md, cmake/modules/CodeCoverage.cmake, test-cov.sh, test.sh, test/CMakeLists.txt, test_code_coverage.sh
Since we're adding tests at a decent rate, might be nice to have test coverage information.
~~It's supposed to leave a comment on the PR, debugging that, but results can be seen here - https://coveralls.io/github/water111/jak-project~~ - Can't be done for forked PRs, limitation of actions - https://github.com/coverallsapp/github-action/issues/7
If you setup this repo on https://coveralls.io/github/water111/jak-project/settings then maybe the comments will get added (this is just uploading the reports)
=> Add Coveralls.io

common/cross_sockets/xsocket.cpp, common/cross_sockets/xsocket.h, goalc/listener/Listener.cpp, test/test_listener_deci2.cpp
The listener periodically times out waiting on the runtime, which doesn't always mean something is wrong. On windows I mistook this for a socket error instead of just a normal timeout, causing the connection to drop out very quickly if nothing was sent.
=> Fix Listener Socket Timeout on Windows

.editorconfig, CMakeLists.txt, common/type_system/Type.cpp, decompiler/Disasm/Instruction.cpp, decompiler/Disasm/Register.cpp, decompiler/Function/Function.h, decompiler/ObjectFile/ObjectFileDB.cpp, game/kernel/kboot.cpp, game/kernel/kprint.cpp, game/runtime.cpp, goalc/compiler/IR.cpp, goalc/compiler/Util.cpp, goalc/compiler/Val.cpp, goalc/compiler/compilation/Define.cpp, goalc/compiler/compilation/Math.cpp, goalc/emitter/CodeTester.h, goalc/emitter/IGen.h, goalc/emitter/Register.cpp, goalc/goos/Object.h, goalc/goos/TextDB.cpp, goalc/regalloc/Allocator.cpp, third-party/fmt/CMakeLists.txt
Mostly revolved around the new MSVC check for functions that don't cover all paths (ie. a switch statement without a default case).  It appears to not see an assert as a valid default case.
I switched assert(false) to exceptions in these cases.  I believe this should also abort the program, but will also provide a hopefully useful message?  Hopefully this is an improvement.
=> Resolve a good chunk of windows compiler warnings

common/util/FileUtil.cpp, game/system/Deci2Server.cpp, goalc/listener/Listener.cpp, test/test_compiler_and_runtime.cpp
We've had a few random test failures related to the listener connection on github, and recently a test for `format` that sent a lot of data and failed always on github actions.  It seems like the listener can send data faster than the runtime can read it, causing an error that I wasn't checking for. After adding the error check, the `format` test seems to pass.
If all tests pass on this PR, I think this is the fix.
=> Fix a Listener Bug

game/system/iop_thread.cpp
Previously I implemented a system so the IOP code wouldn't have to run at 100% CPU usage in a busy loop, like it does in the original game. However it was not robust to the case where the game C code calls the "is the IOP done?" function in a loop as fast as possible.  This fixes that issue and the CPU usage of `gk` remains very low when nothing is happening.
=> Fix high cpu usage from iop thread

game/main.cpp, gk.sh
Add a `-v` option to runtime to log everything to stdout and flush after each message. This can be used to make all print statements appear in the correct order in the same place, which is useful for debugging.
=> Tweak logger settings to make logging happen in order

common/goos/Object.h, doc/changelog.md, goal_src/kernel-defs.gc, goalc/compiler/Compiler.h, goalc/compiler/Util.cpp, goalc/compiler/compilation/Type.cpp, test/goalc/source_templates/with_game/test-new-array.gc, test/goalc/test_with_game.cpp
The `new` operator now can create arrays and inline arrays on heaps, as required for https://github.com/water111/jak-project/issues/49
Field access is split into a separate function with comments.
=> Add more array stuff and clean up field access

decompiler/ObjectFile/LinkedObjectFile.cpp
```
lw t9, format(s7)                   ;; (set! t9 format)
daddiu a0, s7, #t                   ;; (set! a0 '#t)
daddiu a1, fp, L66                  ;; (set! a1 L66) "~Tprocess: ~A~%"
lwu a2, 4(gp)                       ;; (set! a2 (l.wu (+.i gp 4)))
jalr ra, t9                         ;; (call!)
sll v0, ra, 0
```
If an instruction references a string, includes the contents of the string on the comment.
=> Print strings in assembly

common/type_system/TypeSystem.cpp, common/type_system/TypeSystem.h, decompiler/CMakeLists.txt, decompiler/Disasm/Register.h, decompiler/Function/BasicBlocks.h, decompiler/Function/CfgVtx.cpp, decompiler/Function/CfgVtx.h, decompiler/Function/Function.cpp, decompiler/Function/Function.h, decompiler/Function/TypeAnalysis.cpp, decompiler/IR/BasicOpBuilder.cpp, decompiler/IR/CfgBuilder.cpp, decompiler/IR/IR.cpp, decompiler/IR/IR.h, decompiler/IR/IR_TypeAnalysis.cpp, decompiler/ObjectFile/LinkedObjectFile.cpp, decompiler/ObjectFile/ObjectFileDB.cpp, decompiler/config/all-types.gc, test/test_type_system.cpp
This is the beginning of the decompiler type analysis pass.  This is probably the most important/riskiest decompiler pass, for a few reasons:
- It will dramatically improve the readability of the code.
- Once we give the decompiler type information, it will be able to actually decompile accessing fields of types.
- It is required for the next 2 big decompiler passes, which should make the code easier to read as well
- It must be done in order to know how many arguments each function call takes, which is very important to know.
- There may be ways around this but they will be ugly - like always calling the function with 8 arguments and having "junk" in the unused arguments.  This will make the code very hard to read and not much better than just "translating" the MIPS to x86.
Currently the …
=> Partially Implement Decompiler Type Analysis

decompiler/Function/Function.cpp, decompiler/Function/Function.h, decompiler/Function/TypeAnalysis.cpp, decompiler/IR/BasicOpBuilder.cpp, decompiler/ObjectFile/LinkedObjectFile.cpp, decompiler/ObjectFile/LinkedObjectFile.h, decompiler/ObjectFile/ObjectFileDB.cpp, decompiler/ObjectFile/ObjectFileDB.h, decompiler/config.cpp, decompiler/config.h, decompiler/config/jak1_ntsc_black_label.jsonc, decompiler/gui/decompiler_gui.py, decompiler/main.cpp, goal_src/build/all_objs.txt
This fixes the issue where running a partial decompilation results in incompatible names when compared to running a full decompilation. (https://github.com/water111/jak-project/issues/91)
The object files now have three names:
- The name in the game - the exact name of the file in the game. There are files with the same name and different contents with this scheme.
- The "ag" name. If the file is detected to be an art group, appends "ag" to the end. There are file with the same name and different contents with this scheme.
- The "unique" name. This modifies the "ag" name if there are duplicates so that each version has a unique name.  The suffix is a list of DGO/CGO files where this version appears.  This is now the name using for everything in the decompiler.
The old "versioned" name …
=> Make decompiler naming consistent

decompiler/config/all-types.gc, doc/changelog.md, goal_src/engine/math/vector-h.gc, goalc/compiler/IR.cpp, goalc/compiler/Val.cpp, goalc/compiler/Val.h, test/goalc/source_templates/with_game/test-build-game.gc, test/goalc/source_templates/with_game/test-load-game.gc, test/goalc/source_templates/with_game/test-vector-dot.gc, test/goalc/test_with_game.cpp
Implement a missing case for loading floats that was causing the compiler to error when compiling `vector-dot`, and add a test for this and some functions from the game which use this.
More importantly, this loads GAME.DGO as part of the game tests, which I forgot to do previously. I think KERNEL was being loaded the first time which is why not everything broke.  But that means we never tested a big DGO load (checks for bugs in DGO IOP state machine code) and reloading the kernel (checks for bugs in kscheme on redefinitions) I really hope this works on windows...
=> fix float loads, add dgo loading to game test

common/type_system/TypeSystem.h
Upon initial setup, there was an issue with `runtime_error` not being picked up. It turns out an import `<stdexcept>`was missing.
Add missing import.
=> Added missing import causing runtime_error to not be found.

CMakeLists.txt, common/cross_os_debug/xdbg.cpp, common/cross_os_debug/xdbg.h, common/goal_constants.h, doc/goal_dbg_doc.md, game/kernel/kmalloc.cpp, game/kernel/kscheme.cpp, game/kernel/kscheme.h, goal_src/goal-lib.gc, goalc/CMakeLists.txt, goalc/compiler/Compiler.cpp, goalc/compiler/Compiler.h, goalc/compiler/compilation/Atoms.cpp, goalc/compiler/compilation/CompilerControl.cpp, goalc/compiler/compilation/Debug.cpp, goalc/debugger/Debugger.cpp, goalc/debugger/Debugger.h, goalc/emitter/disassemble.cpp, goalc/emitter/disassemble.h, test/goalc/test_debugger.cpp
Add utilities to print memory in several ways, including disassembling.
Load the symbol table on break, and allow using symbols (or their values) as addresses in debugging forms.
Build Zydis as a shared library.
=> Add some debugger memory utilities

game/kernel/asm_funcs.asm, game/kernel/kboot.cpp, game/kernel/kdgo.cpp, game/kernel/kmachine.cpp, game/kernel/kscheme.cpp, game/kernel/kscheme.h, game/overlord/iso_cd.cpp, game/runtime.cpp, game/sce/deci2.cpp, test/goalc/test_debugger.cpp
Previously GOAL code ran in the stack from the EE thread.  This makes the GOAL stack be located outside of the GOAL address space, which has all sorts of problems. GOAL threading won't work, and you can't get GOAL addresses of things on the stack. It's also an issue for the debugger which is set up to read memory in the GOAL address space.
Breaking into a separate PR because I think this will take a bunch of work to get on windows.
=> move GOAL stack to GOAL memory

assets/.gitignore, assets/textures/.gitignore, common/util/FileUtil.cpp, common/util/FileUtil.h, common/versions.h, decompiler/CMakeLists.txt, decompiler/ObjectFile/ObjectFileDB.cpp, decompiler/ObjectFile/ObjectFileDB.h, decompiler/config.cpp, decompiler/config.h, decompiler/config/all-types.gc, decompiler/config/jak1_ntsc_black_label.jsonc, decompiler/data/tpage.cpp, decompiler/data/tpage.h, decompiler/main.cpp, game/kernel/fileio.cpp, game/kernel/fileio.h, third-party/svpng.h
One of the "data" GOAL object file types is a `tpage` file, which contains packed textures. This PR starts processing these tpages and extracts textures to PNG files in the `assets/textures` folder.
The logic to convert the textures is in `tpage.cpp`. It ended up being way more complicated than I expected because they pack together many textures in a confusing way and copy them to VRAM using the wrong format type, which scrambles the texture up. They store scrambled up textures on the DVD that get "unscrambled" by the copy operation in a confusing way. They use palletized textures to save on VRAM, and the color lookup table (CLUT) has weird scrambling applied to it too.
There are still a number of features to add:
Textures look like this:
It works on around 1/2 of the ~4000 textures. The …
=> Extract Textures

common/goos/Reader.cpp, common/goos/Reader.h, doc/goal_doc.md, test/test_reader.cpp
Game text has weird non-printable characters that the reader can't handle. Now you can do something like `"\cab"` and it will insert the character for `0xab`. This involves fiddling with the string to number and number to string stuff, which is always a pain on Windows so I'm making this a separate PR for testing.
=> [Reader] Support escape codes for any character

common/versions.h, doc/changelog.md, doc/goal_doc.md, goal_src/kernel/gcommon.gc, goalc/compiler/Env.cpp, goalc/compiler/Env.h, goalc/compiler/compilation/Block.cpp, goalc/compiler/compilation/Function.cpp, goalc/compiler/compilation/Type.cpp, test/goalc/source_templates/functions/function-returning-none.static.gc, test/goalc/source_templates/functions/inline-with-block-1.static.gc, test/goalc/source_templates/functions/inline-with-block-2.static.gc, test/goalc/source_templates/functions/inline-with-block-3.static.gc, test/goalc/source_templates/functions/inline-with-block-4.static.gc, test/goalc/source_templates/functions/return-from-trick.static.gc, test/goalc/test_functions.cpp
Will close https://github.com/water111/jak-project/issues/137 and will close https://github.com/water111/jak-project/issues/136
Inlined functions (either through `(declare (inline))` or through putting `(inline func)` as the head) no longer can access blocks defined in the enclosing function. Immediate lambdas (`let`s) still can do this. Inlined functions have a block environment with their own `#f` that they can `return-from`. It takes the same optimization as `block`, where it only forces you to return in a separate GPR ireg if you actually use a `return-from`.
Functions using `return-from #f` to return early from the entire function will now have the correct return type. This is a breaking change that broke existing code so the compiler version was increased.
Functions and `block`s can …
=> [Compiler] Fix return-from, returning none, and inline function block scoping bugs

common/type_system/Type.cpp, common/type_system/Type.h, common/type_system/TypeSystem.cpp, common/type_system/TypeSystem.h, decompiler/CMakeLists.txt, decompiler/Function/BasicBlocks.h, decompiler/Function/Function.cpp, decompiler/Function/Function.h, decompiler/Function/TypeAnalysis.cpp, decompiler/Function/TypeAnalysis.h, decompiler/IR/BasicOpBuilder.cpp, decompiler/IR/IR.cpp, decompiler/IR/IR.h, decompiler/IR/IR_TypeAnalysis.cpp, decompiler/ObjectFile/LinkedObjectFile.cpp, decompiler/ObjectFile/ObjectFileDB.cpp, decompiler/config.cpp, decompiler/config.h, decompiler/config/all-types.gc, decompiler/config/jak1_ntsc_black_label.jsonc, decompiler/util/DecompilerTypeSystem.cpp, decompiler/util/DecompilerTypeSystem.h, decompiler/util/TP_Type.cpp, decompiler/util/TP_Type.h, goal_src/kernel/gcommon.gc
WIP second version of type analysis decompiler pass.
=> Type Prop - Second Attempt

boot_kernel.sh, common/type_system/deftype.cpp, decompiler/config/all-types.gc, doc/changelog.md, game/kernel/kscheme.cpp, goal_src/goal-lib.gc, goal_src/kernel-defs.gc, goal_src/kernel/gcommon.gc, goal_src/kernel/gkernel-h.gc, goal_src/kernel/gkernel.gc, goalc/compiler/CodeGenerator.cpp, goalc/compiler/Compiler.cpp, goalc/compiler/Compiler.h, goalc/compiler/Env.cpp, goalc/compiler/Env.h, goalc/compiler/IR.cpp, goalc/compiler/IR.h, goalc/compiler/Util.cpp, goalc/compiler/compilation/Asm.cpp, goalc/compiler/compilation/Atoms.cpp, goalc/compiler/compilation/Define.cpp, goalc/compiler/compilation/Function.cpp, goalc/compiler/compilation/Math.cpp, goalc/compiler/compilation/Static.cpp, goalc/compiler/compilation/Type.cpp, goalc/emitter/IGen.h, test/goalc/source_templates/variables/static-bitfield-field.gc, test/goalc/source_templates/with_game/test-new-static-basic.gc, test/goalc/test_variables.cpp, test/goalc/test_with_game.cpp
It's time to implement `gkernel.gc` in OpenGOAL!
This is going to have a lot of differences between the actual game and the port because we need to modify the kernel to work for x86-64.  But the non-assembly parts should be pretty similar.  They will be a good way to check the decompiler's correctness because they have a good combination of loops/branching/conditionals, etc...
For now, this is just the start, and I'm just making the PR so I can easily do a diff against master to look at the compiler changes.
Compiler changes:
- Better support for constants. Integer constants can now be GOAL constants, enum constants, etc instead of just plain numbers.
- Bugfix on `'#f` / `'#t`, code was correctly but wasn't as fast as it could be.
- Typechecking for `set!` allows `#f` to be used as a null …
=> Implement `gkernel`: Part 1

decompiler/config/all-types.gc, doc/changelog.md, doc/goal_doc.md, goalc/compiler/CodeGenerator.cpp, goalc/compiler/CodeGenerator.h, goalc/compiler/Compiler.h, goalc/compiler/Env.cpp, goalc/compiler/Env.h, goalc/compiler/IR.cpp, goalc/compiler/Util.cpp, goalc/compiler/compilation/Function.cpp, goalc/compiler/compilation/Type.cpp, goalc/regalloc/Allocator.cpp, goalc/regalloc/Allocator.h, goalc/regalloc/IRegSet.h, goalc/regalloc/allocate.h, test/goalc/source_templates/variables/stack-array-align.gc, test/goalc/source_templates/variables/stack-structure-align.gc, test/goalc/test_variables.cpp
Faster and better on inline assembly.
Baseline before speed improvements:
Starting the compiler, building game 3x takes 4.6 seconds on my computer.
MD5's at ac52c7bca3a34d3fc316875cbff799d85362352c
```
a0c2a6111602300db6f441bf983040a5  iso/KERNEL.CGO
c2f58039fc824702ce903f4d76d5a142  iso/GAME.CGO
```
=> Improve Register Allocator

common/link_types.h, common/versions.h, doc/changelog.md, game/kernel/klink.cpp, goal_src/kernel/gkernel.gc, goalc/compiler/Compiler.h, goalc/compiler/StaticObject.cpp, goalc/compiler/StaticObject.h, goalc/compiler/Util.cpp, goalc/compiler/compilation/Macro.cpp, goalc/compiler/compilation/Static.cpp, goalc/compiler/compilation/Type.cpp, goalc/emitter/ObjectGenerator.cpp, goalc/emitter/ObjectGenerator.h, test/goalc/source_templates/with_game/test-fancy-static-fields.gc, test/goalc/source_templates/with_game/test-new-static-basic.gc, test/goalc/source_templates/with_game/test-static-pair-1.gc, test/goalc/test_with_game.cpp
Add support for pointers to other data in the same segment in the linker (`LINK_PTR`), in `ObjectGenerator` and in `StaticStructure`.
In the compiler, add static pairs, linked lists, etc. For now, it supports quoting only (no quasiquote), so you can't put in GOAL expressions. The only supported elements are: more pairs/lists, strings, symbols, and integers, which are signed 32-bit integers.
Make `StaticString` a child of `StaticBasic`, which makes including strings are pair elements, and eventually including strings a fields much easier.
Add the `StaticResult` class. It's kind of like a `RegVal`, but works with the static part of the compiler.  It would have been really cool if the static stuff could use `Val` like all the rest of the front end, but it seems like there would need to be …
=> [Compiler] Add static data features

CMakeLists.txt, common/util/CMakeLists.txt, game/kernel/asm_funcs.asm, game/kernel/kdgo.cpp, game/kernel/kdgo.h, game/kernel/kscheme.cpp, game/kernel/kscheme.h, game/kernel/ksound.cpp, goal_src/engine/ps2/rpc-h.gc, goal_src/kernel-defs.gc
This cleans up the weird special cases for `format` and `rpc-call`. The default "call C from GOAL" can only do 6 arguments. There used to be weird special cases for `format` because it can use up to 8 arguments, and an ugly hack for `rpc-call` (7 args) to call two functions, the first to set up the first half of the arguments, and the second to set up the rest and actually do the call.
After this PR, there are two ways to call C from GOAL:
The "normal" way, where you get up to 6 arguments. It's super fast on linux and uses no stack. On windows it's a little bit slower and does use some stack, but still fast. So far, this is used almost everywhere.
There's the "stack arg" way, which gives you up to 8 arguments. It's slower on both linux and windows, but is only used in a few places. It …
=> Clean up asm for format

common/goal_constants.h, common/type_system/CMakeLists.txt, common/type_system/TypeFieldLookup.cpp, common/type_system/TypeSystem.cpp, common/type_system/TypeSystem.h, decompiler/IR/BasicOpBuilder.cpp, decompiler/IR/IR.h, decompiler/IR/IR_TypeAnalysis.cpp, decompiler/ObjectFile/LinkedObjectFile.cpp, decompiler/config/jak1_ntsc_black_label.jsonc, decompiler/config/jak1_ntsc_black_label/type_hints.jsonc, decompiler/util/DecompilerTypeSystem.cpp, decompiler/util/TP_Type.h, goalc/compiler/compilation/Type.cpp, test/test_type_system.cpp
Improve the reverse field lookup.  Now we can correctly handle the cases described in https://github.com/water111/jak-project/issues/161.  We also should support inline basics, more types of nested field access, better "get pointer to thing in array", and support for fancy boxed arrays (print and inspect for array type now pass type propagation).
After this PR, KERNEL.CGO:
```
144/211 functions attempted type analysis (68.25%)
125/144 functions that attempted type analysis succeeded (86.81%)
125/211 functions passed type analysis (59.24%)
```
=> [Decompiler] Improve reverse field lookup

CMakeLists.txt, common/type_system/TypeSystem.cpp, decompiler/Function/Function.h, decompiler/Function/TypeAnalysis.cpp, decompiler/IR/BasicOpBuilder.cpp, decompiler/IR/IR.cpp, decompiler/IR/IR.h, decompiler/IR/IR_TypeAnalysis.cpp, decompiler/ObjectFile/ObjectFileDB.cpp, decompiler/config.cpp, decompiler/config.h, decompiler/config/all-types.gc, decompiler/config/jak1_ntsc_black_label.jsonc, decompiler/config/jak1_ntsc_black_label/anonymous_function_types.jsonc, decompiler/config/jak1_ntsc_black_label/type_hints.jsonc, decompiler/util/DecompilerTypeSystem.cpp, decompiler/util/TP_Type.h, goal_src/engine/ps2/vu1-macros.gc, goal_src/engine/util/types-h.gc, goal_src/kernel/gkernel-h.gc, goal_src/kernel/gkernel.gc, goal_src/kernel/gstring-h.gc, goal_src/kernel/gstring.gc, goal_src/kernel/pskernel.gc
It's mostly working! There are only two functions in gstring that fail. The first is just something I haven't implemented yet - a float constant is loaded into a GPR (we give up).  The second one is `string-cat-to-last-char`, which I think has something like:
`(&-> my-string data -1)` to get to the pointer to the byte behind the first byte of the string. Which is a pretty weird thing to do. 
In both cases it would be nice if we could provide some sort of hint? The first might just be a static data hint, like "let L170 be accessed as a float constant".  Or if we don't care about getting types exactly right here, we could just let it load as a 32-bit integer.
The second is a little trickier.  I need to understand the code better to figure out the best way to handle it. In the end we'll …
=> [Decompiler, Game] Run type prop on gstring

decompiler/Function/ExpressionBuilder.cpp, decompiler/ObjectFile/ObjectFileDB.cpp, doc/changelog.md, doc/goal_doc.md, goal_src/kernel/gkernel-h.gc, goalc/compiler/IR.cpp, goalc/compiler/IR.h, goalc/compiler/compilation/Asm.cpp, goalc/compiler/compilation/Function.cpp, goalc/compiler/compilation/Type.cpp, test/goalc/source_templates/kernel/kernel-test.gc
See updated documentation for details.
This allows you to have multiple `suspend` and `process-deactivate`s in the same function.
=> [Compiler] Add `reset-here` option to colored and constrained rlet vars

doc/changelog.md, goalc/compiler/Compiler.h, goalc/compiler/Util.cpp, goalc/compiler/Val.cpp, goalc/compiler/compilation/Asm.cpp, goalc/compiler/compilation/Type.cpp, test/goalc/source_templates/with_game/test-boxed-array-index.gc, test/goalc/test_with_game.cpp
The given case of `(-> x 3)` is now a single instruction instead of 6! (where `x` is an array of `int32`)
Old:
```
[0x1000d] mov ecx, 0x03                          mov-ic igpr-3, 3
[0x10012] mov edx, 0x04                          mov-ic igpr-4, 4
[0x10017] imul edx, ecx                          imul igpr-4, igpr-3
[0x1001a] movsxd rdx, edx
[0x1001d] add rdx, rax                           addi igpr-6, igpr-2
[0x10020] movsxd rax, dword ptr [r15+rdx*1]      mov igpr-5, [igpr-6 + 0]
```
New:
```
[0x1000a] movsxd rax, dword ptr [r15+rax*1+0x0C] mov igpr-3, [igpr-2 + 12]
```
Also, `(-> x <var>)` is now
```
[0x1000f] shl rcx, 0x02                          shl igpr-5, 2
[0x10013] add rcx, rax                           addi igpr-7, igpr-3
[0x10016] movsxd rax, dword ptr [r15+rcx*1]      mov …
```
=> [Compiler] Better array indexing

CMakeLists.txt, README.md, decompiler/IR/IR_ExpressionStack.cpp, decompiler/ObjectFile/ObjectFileDB.cpp, decompiler/util/DecompilerTypeSystem.cpp, game/kernel/klink.cpp, game/kernel/kmachine.h, game/kernel/kscheme.cpp, goalc/listener/Listener.cpp
See readme for how to do it.
Small bugfixes:
- increase GOAL kernel stack to avoid stack overflow
- `memcpy` to `memmove`
- Back up `r10` and `r11` when calling C code from GOAL in linux.
- free memory in Listener
- fix build warnings
=> Add asan build

.gitignore, logs/.gitignore
Certain configurations may use the root directory to create the ``logs`` folder.
=> Add logs folder to root gitignore

common/type_system/TypeSystem.cpp, common/type_system/TypeSystem.h, decompiler/CMakeLists.txt, decompiler/IR2/AtomicOp.cpp, decompiler/IR2/AtomicOp.h, decompiler/IR2/AtomicOpBuilder.cpp, decompiler/IR2/AtomicOpBuilder.h, decompiler/IR2/Env.cpp, decompiler/IR2/Env.h, decompiler/IR2/IR2_common.h, decompiler/IR2/reg_usage.h, decompiler/IR2/variable_naming.cpp, decompiler/IR2/variable_naming.h, decompiler/ObjectFile/ObjectFileDB.h, decompiler/ObjectFile/ObjectFileDB_IR2.cpp, decompiler/util/DecompilerTypeSystem.cpp, decompiler/util/DecompilerTypeSystem.h, decompiler/util/TP_Type.h
Unfortunately, the conversion to SSA is turning out to be relatively slow. For now, I'm just focusing on getting the right answer with an algorithm that's not doomed to be impossibly slow, without worrying about implementation details.
After that, it's probably worth going back and improving the implementation. We can easily map "GOAL registers used in coloring allocator" to "integer between 0, 64", so we can use a 64-bit integer where each bit corresponds to represents sets of registers instead of a `set`/`unordered_set`. I did bitsets in the compiler (https://github.com/water111/jak-project/pull/154) and it worked great, though it was more complicated because you can have arbitrarily many variables in the compiler.
The algorithm is based off of _Simple Generation of Static …
=> [Decompiler] WIP Conversion to SSA and variable naming

decompiler/CMakeLists.txt, decompiler/Function/TypeAnalysis.cpp, decompiler/IR2/AtomicOp.cpp, decompiler/IR2/AtomicOp.h, decompiler/IR2/AtomicOpForm.cpp, decompiler/IR2/AtomicOpTypeAnalysis.cpp, decompiler/IR2/Env.h, decompiler/IR2/Form.cpp, decompiler/IR2/Form.h, decompiler/IR2/FormExpressionAnalysis.cpp, decompiler/IR2/FormStack.cpp, decompiler/IR2/FormStack.h, decompiler/IR2/GenericElementMatcher.cpp, decompiler/IR2/GenericElementMatcher.h, decompiler/ObjectFile/ObjectFileDB_IR2.cpp, decompiler/analysis/atomic_op_builder.cpp, decompiler/analysis/atomic_op_builder.h, decompiler/analysis/expression_build.cpp, decompiler/analysis/reg_usage.cpp, test/decompiler/FormRegressionTest.cpp, test/decompiler/test_FormBeforeExpressions.cpp, test/decompiler/test_FormExpressionBuild.cpp
This adds:
- A post-processing pass to "clean up" `if` conditions that are ugly looking by extracting extra Elements to the parent form.
- A Form matching utility
- Actually adds a function end operation to fix the return value issue
- Refactors rewrite_to_get_reg to work with a variable instead of a reg
- Adds support for dynamic method access. This is the first example where we simplify a form based on type pass info after popping it off of the stack, as opposed to at atomic op -> form conversion. I think it is a good pattern so far.
=> [Decompiler] Expressions (Part 3)

decompiler/IR2/Form.cpp, decompiler/IR2/Form.h, decompiler/IR2/FormExpressionAnalysis.cpp, decompiler/IR2/FormStack.cpp, decompiler/IR2/FormStack.h, decompiler/analysis/expression_build.cpp, test/decompiler/test_FormBeforeExpressions.cpp, test/decompiler/test_FormExpressionBuild.cpp
- No longer print `truthy` when the value is clearly being used as a condition due to enclosing form.
- Rewrite `(if a (set! b c) (set! b d))` and similar as `(set! b (if a c d))`
- Build expressions even when there are coloring moves (see function call in `sort`)
=> [Decompiler] Small tweaks to expression framework

test/goalc/test_control_statements.cpp
Each test needs to at least talk to the runtime at least once so the compiler/runtime are connected and the compiler can send the runtime shutdown message.
=> [Compiler Test] Fix inline test

doc/changelog.md, doc/goal_doc.md, goal_src/goal-lib.gc, goal_src/kernel/gkernel.gc, goalc/compiler/Compiler.h, goalc/compiler/Env.h, goalc/compiler/compilation/Atoms.cpp, goalc/compiler/compilation/Function.cpp, goalc/compiler/compilation/Type.cpp, test/goalc/source_templates/control-statements/methods.static.gc, test/goalc/source_templates/with_game/test-access-inline-array.gc, test/goalc/source_templates/with_game/test-integer-boxed-array.gc, test/goalc/test_game_no_debug.cpp, test/goalc/test_with_game.cpp
- Split `method` into `method-of-type` and `method-of-object` to avoid ambiguity https://github.com/water111/jak-project/issues/225
- Fixed `(-> <obj-of-type-array> type)` not working https://github.com/water111/jak-project/issues/224
- Fixed use-after free https://github.com/water111/jak-project/issues/222
=> [Compiler] Bug fixes

doc/changelog.md, doc/goal_doc.md, goal_src/goal-lib.gc, goalc/compiler/Compiler.h, goalc/compiler/IR.h, goalc/compiler/compilation/Atoms.cpp, goalc/compiler/compilation/ControlFlow.cpp, goalc/compiler/compilation/Type.cpp, test/goalc/source_templates/with_game/test-short-circuit.gc, test/goalc/test_with_game.cpp
The code is more efficient and it gives a more specific compile time type as a result, fixing https://github.com/water111/jak-project/issues/223
Also adds tests for `and` and `or` which I guess I never wrote???
=> [Compiler] Implement and/or in the compiler instead of a macro

decompiler/Disasm/Instruction.cpp, decompiler/Disasm/Instruction.h, decompiler/Disasm/InstructionDecode.cpp, decompiler/Disasm/OpcodeInfo.cpp, decompiler/Disasm/OpcodeInfo.h, test/CMakeLists.txt, test/decompiler/test_InstructionDecode.cpp
As noticed by Vaser in https://github.com/water111/jak-project/pull/258, these three instructions were not decoded correctly.  The `vsqrt` instruction had the wrong syntax, and `vrsqrt` and `vdiv` were missing a fields.
New format:
```
vdiv Q, vf10.y, vf20.z
vrsqrt Q, vf10.y, vf20.z
vsqrt Q, vf20.z
```
which matches the documentation.
=> [Decompiler] Disassemble vdiv/vsqrt/vrsqrt properly

decompiler/IR2/AtomicOp.cpp, decompiler/IR2/AtomicOp.h, decompiler/IR2/AtomicOpForm.cpp, decompiler/IR2/AtomicOpTypeAnalysis.cpp, decompiler/IR2/Form.h, decompiler/IR2/FormExpressionAnalysis.cpp, decompiler/IR2/FormStack.cpp, decompiler/IR2/FormStack.h, decompiler/config/all-types.gc, decompiler/util/DecompilerTypeSystem.cpp, decompiler/util/TP_Type.cpp, decompiler/util/TP_Type.h, test/decompiler/test_FormExpressionBuild.cpp, test/decompiler/test_gkernel_decomp.cpp
I'm not sure this will be 100% successful at recognizing all cases, but it does work on a few test cases from gkernel.
Fixed a bug where assembly ops would error when decompiling after the VDIV fix.
=> [Decompiler] Support virtual method calls

doc/goal_doc.md, goalc/compiler/Compiler.h, goalc/compiler/IR.cpp, goalc/compiler/IR.h, goalc/compiler/compilation/Asm.cpp, goalc/compiler/compilation/Atoms.cpp, goalc/emitter/IGen.h, test/goalc/source_templates/with_game/test-vector-math-1-operand.template.gc, test/goalc/source_templates/with_game/test-vector-math-2-operand-acc.template.gc, test/goalc/source_templates/with_game/test-vector-math-2-operand.template.gc, test/goalc/source_templates/with_game/test-vector-math-division.template.gc, test/goalc/source_templates/with_game/test-vector-math-sqrt.template.gc, test/goalc/source_templates/with_game/test-vector-outer-product.gc, test/goalc/test_with_game.cpp, test/test_emitter_avx.cpp
This adds support for the majority of the remaining VU instructions.  The remaining being:
- R Register
- `vrget`
- `vrnext`
- `vrxorw`
- Flag support needed
- `VCLIP`
- Uses VU Memory
- `vsqi.dest`
- `vlqi.dest`
- Integer related
- `vftoi0` | `vftoi12` | `vftoi4` | `viaddi` | `viand` | `vior` | `vitof0` | `vitof12` | `vitof15` | `vmtir`
- I think it was discussed that these could be handled not through asm instructions, but through some C?
I think I identified an issue with the VDIV/VSQRT instruction encoding, the gist being, `fsf` and `ftf` don't seem to be properly output.
In this PR, the following are supported one way or another (some will require the use of some clever decompiling), for instructions that use the ACC/Q, this will be supported by an additional vector argument, …
=> compiler: Support the majority of the remaining VU VF instructions

decompiler/IR2/FormExpressionAnalysis.cpp, decompiler/IR2/FormStack.cpp, decompiler/IR2/FormStack.h, decompiler/IR2/IR2_common.h, test/decompiler/test_FormExpressionBuild.cpp
The expression propagator doesn't attempt to run on reg-to-reg consuming moves and instead lets the `FormStack` deal with this.  The `FormStack` already did the right thing for `pop_reg`, with the recursive call to `pop_reg`, but it did not totally handle two cases, which were added:
1. The case where there is a coloring move result to get the return value.  Now we can loop up the expression stack following consecutive coloring sets.
2. Just eliminating these.
TODO - there is an issue with this:
```
(set! x (if a (set! y z)))
```
will probably be decompiled as `(set! x (if a z))` and eliminate the `set! y`.
=> [Decompiler] Fix coloring moves

decompiler/ObjectFile/ObjectFileDB_IR2.cpp, decompiler/analysis/cfg_builder.cpp, decompiler/config/all-types.gc, decompiler/config/jak1_ntsc_black_label/label_types.jsonc, decompiler/config/jak1_ntsc_black_label/type_hints.jsonc, decompiler/config/jak1_ntsc_black_label/var_names.jsonc, decompiler/util/data_decompile.cpp, game/kernel/kscheme.cpp, goal_src/engine/collide/collide-func-h.gc, goal_src/engine/collide/collide-mesh-h.gc, goal_src/engine/collide/collide-shape-h.gc, goal_src/engine/game/fact-h.gc, goal_src/engine/math/quaternion.gc, goal_src/engine/math/vector.gc, goal_src/engine/physics/trajectory-h.gc, goal_src/engine/target/pat-h.gc, goal_src/engine/target/surface-h.gc, goal_src/engine/util/smush-control-h.gc, goal_src/engine/util/sync-info-h.gc
Changes a bug where `(asize-of x)` returns the wrong thing for objects of types which did not define their own `asize-of` method and instead inherited from `basic`.
Fix regression from https://github.com/water111/jak-project/pull/292 where the decompiler would abort when it had an error.
Improve printing of data decompilation.
Decompile a few files, pat-h surface-h. Started on `fact-h`.
=> Fix asize bug, decompile a few files

common/CMakeLists.txt, common/goos/Reader.cpp, common/goos/ReplHistory.cpp, common/goos/ReplHistory.h, common/util/FileUtil.cpp, common/util/FileUtil.h, goalc/CMakeLists.txt, goalc/compiler/compilation/CompilerControl.cpp, goalc/main.cpp
Linenoise had all the tools already to support this, the problem (and i could very well have solved it in a less than ideal way) is that the history is stored in a `static` vector.  Being as we have to interact with the history in different points of the app (ie, load the history on startup / save it on exit / etc) these are all in different files, and when doing so the history would be empty.
Wrapping everything to have a single linenoise include, "solves" this problem, and history now works as expected.
It will save a `.opengoal.repl.history` file in your (linux) `$HOME` or (windows) `$USERPROFILE` directory.
=> repl: Support cross-session history

common/goos/PrettyPrinter.cpp, common/goos/PrettyPrinter.h, decompiler/CMakeLists.txt, decompiler/IR2/AtomicOpTypeAnalysis.cpp, decompiler/IR2/Form.cpp, decompiler/IR2/Form.h, decompiler/IR2/FormExpressionAnalysis.cpp, decompiler/ObjectFile/ObjectFileDB.h, decompiler/ObjectFile/ObjectFileDB_IR2.cpp, decompiler/analysis/anonymous_function_def.cpp, decompiler/analysis/anonymous_function_def.h, decompiler/analysis/final_output.cpp, decompiler/analysis/final_output.h, decompiler/config/jak1_ntsc_black_label/label_types.jsonc, test/decompiler/reference/all_forward_declarations.gc, test/decompiler/reference/gkernel_REF.gc, test/offline/offline_test_main.cpp
Support anonymous functions and add the ones in `gkernel.gc` to the offline test.
=> [Decompiler] Support anonymous functions

common/goos/PrettyPrinter.cpp, decompiler/Disasm/InstructionParser.cpp, decompiler/Function/Function.cpp, decompiler/Function/Function.h, decompiler/IR2/Form.cpp, decompiler/IR2/FormExpressionAnalysis.cpp, decompiler/analysis/atomic_op_builder.cpp, decompiler/config/jak1_ntsc_black_label/type_casts.jsonc, test/decompiler/reference/all_forward_declarations.gc, test/decompiler/reference/dgo-h_REF.gc, test/decompiler/reference/gcommon_REF.gc, test/decompiler/reference/gkernel_REF.gc, test/decompiler/reference/gstate_REF.gc, test/decompiler/reference/gstring_REF.gc, test/decompiler/test_FormExpressionBuild.cpp, test/offline/offline_test_main.cpp, test/test_pretty_print.cpp
This fixes a bunch of little things:
- Fix bug in pretty print with breaking lines with empty lists (fixes initial issue in https://github.com/water111/jak-project/issues/319)
- Fix bug in pretty print when breaking control flow forms where the condition isn't a list (fixes my comment in https://github.com/water111/jak-project/issues/319)
- Support for `suspend` in decompiler and `mtlo1`/`mflo1` in the test instruction parser
- Eliminate empty basic block when a function starts with an infinite loop (fixes https://github.com/water111/jak-project/issues/196)
- Support infinite loops in decompiler output
- Add `dgo-h` and `gstate` to offline test
=> [Decompiler] Fix printing, infinite loops, and add gstate/dgo-h

doc/changelog.md, doc/goal_doc.md, goalc/compiler/Compiler.h, goalc/compiler/Util.cpp, goalc/compiler/Val.h, goalc/compiler/compilation/Static.cpp, goalc/compiler/compilation/Type.cpp, test/goalc/source_templates/with_game/test-static-bitfield.gc
The compiler will now accept bifield defintions like
```lisp
(new 'static 'test-bf-type7 :f1 #x12 :f2 (+ #x10 3 #x100) :f3 12.3433 :f4 ((lambda () 1)))
```
It works just like GOAL and will combine all fields known at compile time, then `or` in the others:
```asm
[0x10031] mov rax, 0x20A2BF14000012              mov-ic igpr-11, 9186140812738578
[0x1003b] mov ecx, 0x10                          mov-ic igpr-13, 16
[0x10040] mov edx, 0x03                          mov-ic igpr-14, 3
[0x10045] add rcx, rdx                           addi igpr-12, igpr-14
[0x10048] mov edx, 0x100                         mov-ic igpr-15, 256
[0x1004d] add rcx, rdx                           addi igpr-12, igpr-15
[0x10050] shl rcx, 0x39                          shl igpr-12, 57
[0x10054] shr rcx, 0x29 …
```
=> [Compiler] Support dynamically constructed bitfields

Taskfile.yml, goalc/compiler/Compiler.cpp, goalc/compiler/Compiler.h, goalc/main.cpp
Closes #403
Speeds up the workflow a bit.  Wasn't sure about the `break;` in the arg parsing, hope that doesn't break an assumption/expectation?
=> repl: Add auto-listening capabilities `-auto-lt`

decompiler/IR2/AtomicOpTypeAnalysis.cpp, decompiler/IR2/FormExpressionAnalysis.cpp, decompiler/ObjectFile/LinkedObjectFile.cpp, decompiler/ObjectFile/ObjectFileDB.cpp, decompiler/util/DecompilerTypeSystem.cpp, decompiler/util/data_decompile.cpp
Removing instances where `'` is used in error output, as this breaks editor syntax highlighting (assumes theres a string literal)
vs
=> decomp: Avoid `'` in error output

common/util/json_util.cpp, common/util/json_util.h, decompiler/IR2/AtomicOpForm.cpp, decompiler/ObjectFile/ObjectFileDB.cpp, decompiler/config.cpp, decompiler/config/jak1_ntsc_black_label/label_types.jsonc, test/decompiler/FormRegressionTest.cpp, test/offline/offline_test_main.cpp
It doesn't work if a constant float is used directly in a function argument.
=> Automatically get float label type in most cases

decompiler/Disasm/InstructionParser.cpp, decompiler/Function/CfgVtx.cpp, decompiler/Function/Function.h, decompiler/ObjectFile/ObjectFileDB_IR2.cpp, test/decompiler/FormRegressionTest.cpp, test/decompiler/test_FormBeforeExpressions.cpp
This fixes failing CFGs on:
```
(method 0 fact-info) from fact-h
command-get-process from generic-obs
command-get-trans from generic-obs
dm-cam-render-float from default-menu
(anon-function 82 default-menu) from default-menu
```
Previously the CFG pass would fail when:
- `cond` with an `else` statement
- all code in the `else` statement is optimized out (or it is empty to begin with)
- the block after this `cond` ends with a branch
Also disables most analysis passes when the CFG pass fails - there is now code that assumes the CFG is good and the CFG pass is reliable enough that we don't really care to look at partial decompilations when it fails.
=> [decompiler] Fix failing detection of cond with else where the else is empty

common/goos/PrettyPrinter.cpp, decompiler/util/data_decompile.cpp, decompiler/util/data_decompile.h, docs/markdown/progress-notes/changelog.md, goal_src/engine/level/level-info.gc, goalc/compiler/compilation/Static.cpp, scripts/decomp_progress.py, test/decompiler/reference/all_forward_declarations.gc, test/decompiler/reference/engine/level/level-info_REF.gc, test/decompiler/reference/kernel/gkernel_REF.gc, test/decompiler/test_DataParser.cpp
- Support `(quote x)` in the pretty printer
- Fix up quoting of lists/pairs within static lists
- Fix up printing of fields with symbols in the decompiler
- Allow `new 'static` and `the binteger` to be used in static lists in the compiler
=> [decomp] Decompile level-info

game/system/vm/vm.cpp
The tests got stuck here:
```
[DECI2] Got message: 24 0 0xe042 H -> E
IOP shut down
DMA shut down
dconnect: closed socket at kernel side
[2021-05-12 22:05:47:686] [debug] [VM] Killing
[2021-05-12 22:05:47:686] [debug] [SYSTEM] Thread VM-DMAC is returning
[Listener] Closed connection to target
```
The runtime was stuck at `vm_dead_cv.wait(lk, [&] { return components == 0; });`
I think due to a race condition decrementing components and wait_vm_dead going to sleep
```
--components; // no mutex locked
vm_dead_cv.notify_all();
```
and
```
std::unique_lock<std::mutex> lk(status_mutex);
vm_dead_cv.wait(lk, [&] { return components == 0; });
```
=> [runtime] prevent deadlock during tests

common/CMakeLists.txt, common/goos/Object.cpp, common/util/print_float.cpp, common/util/print_float.h, decompiler/analysis/insert_lets.cpp, test/test_common_util.cpp, third-party/dragonbox.h
This does minimum length representation that is exact, but should round-to-even on all platforms.
The previous implementation had inconsistent rounding behavior between linux/windows because `printf` was different. The rounding mode for `printf` is not in the standard, so implementations do it a little differently.
=> Use dragonbox to print floats

decompiler/IR2/Env.cpp, decompiler/IR2/Env.h, decompiler/IR2/FormExpressionAnalysis.cpp, decompiler/analysis/variable_naming.cpp, decompiler/analysis/variable_naming.h, scripts/update_decomp_reference.py, test/decompiler/reference/all_forward_declarations.gc, test/decompiler/reference/engine/gfx/font-h_REF.gc, test/decompiler/reference/engine/gfx/hw/gs_REF.gc, test/decompiler/reference/engine/math/math_REF.gc, test/decompiler/reference/engine/ps2/pad_REF.gc, test/decompiler/test_FormExpressionBuild2.cpp
The decompiler misrecognized the gpr->fpr as an "argument coloring move" so the use/def info was wrong.  Now it will only recognize `mtc1`'s as coloring moves if the argument is a float.
To make this work, I disabled coloring move recognition unless we have function types.
Also added a script for updating the reference automatically from the result of a failed `offline-tests` run.
=> [decompiler] fix `(gpr->fpr` when an integer arg is converted to float

decompiler/IR2/AtomicOp.h, decompiler/IR2/AtomicOpTypeAnalysis.cpp, decompiler/IR2/Form.h, decompiler/IR2/FormExpressionAnalysis.cpp, decompiler/IR2/FormStack.cpp, decompiler/IR2/FormStack.h
I was expecting this to be much harder, so I'm a little suspicious that this isn't going to work 100% of the time.
=> [decompiler] Get rid of FormStack peek and fix virtual method calls

common/goos/Reader.cpp, decompiler/Function/CfgVtx.cpp, decompiler/Function/CfgVtx.h, decompiler/ObjectFile/ObjectFileDB.cpp, decompiler/ObjectFile/ObjectFileDB.h, decompiler/ObjectFile/ObjectFileDB_IR2.cpp, decompiler/analysis/variable_naming.cpp, decompiler/config.cpp, decompiler/config.h, decompiler/config/jak1_ntsc_black_label.jsonc, decompiler/config/jak1_ntsc_black_label/hacks.jsonc, docs/markdown/progress-notes/changelog.md, goalc/main.cpp, test/decompiler/FormRegressionTest.cpp, test/test_goos.cpp
Also fixes bugs with `''a` and crashing when `goal-lib.gc` has reader errors.
=> [decompiler] add config option for changing cond splitting behavior

decompiler/CMakeLists.txt, decompiler/Function/Function.cpp, decompiler/Function/Function.h, decompiler/ObjectFile/LinkedObjectFile.h, decompiler/ObjectFile/ObjectFileDB.h, decompiler/ObjectFile/ObjectFileDB_IR2.cpp, decompiler/analysis/symbol_def_map.cpp, decompiler/analysis/symbol_def_map.h, decompiler/config.cpp, decompiler/config.h, decompiler/config/jak1_ntsc_black_label.jsonc
In the config, set `"generate_symbol_definition_map": true,` and run the decompiler. It will generate a `symbol_map.json` file in the output folder.
You can kill the decompiler after seeing `[info] Built symbol map in 224.18 ms` if you don't want to wait for the whole thing to run.
The order within files should now be correct, and `deftype`s will win over load/store use of symbols.  Symbols that aren't `deftype` args and are never loaded/stored won't show up.
Example:
```
"gkernel-h": [
"process-tree",
"stack-frame",
"uint64",
"kernel-context",
"thread",
"cpu-thread",
"dead-pool",
"dead-pool-heap-rec",
"dead-pool-heap",
"catch-frame",
"protect-frame",
"handle",
"state",
"event-message-block"
],
```
=> [decompiler] Add pass to generate a symbol definition map file

goalc/compiler/Compiler.h, goalc/compiler/compilation/Atoms.cpp, goalc/compiler/compilation/Type.cpp
I've seen something similar to this in `fisher`, but either way it doesn't hurt to add this
=> [compiler] add `psize-of`

decompiler/IR2/FormExpressionAnalysis.cpp, decompiler/util/data_decompile.cpp, goal_src/engine/dma/dma-disasm.gc, goal_src/engine/gfx/texture.gc, goal_src/engine/gfx/wind-h.gc, goal_src/engine/math/euler-h.gc, goal_src/engine/math/trigonometry.gc, goal_src/engine/ui/credits.gc, goal_src/engine/ui/text-h.gc, goalc/compiler/Compiler.h, goalc/compiler/compilation/Static.cpp, test/decompiler/reference/engine/dma/dma-disasm_REF.gc, test/decompiler/reference/engine/gfx/wind-h_REF.gc, test/decompiler/reference/engine/math/euler-h_REF.gc, test/decompiler/reference/engine/math/trigonometry_REF.gc, test/decompiler/reference/engine/ui/credits_REF.gc, test/decompiler/reference/engine/ui/text-h_REF.gc, test/decompiler/test_DataParser.cpp, test/goalc/source_templates/with_game/test-bitfield-and-enum-types.gc, test/goalc/source_templates/with_game/test-static-boxed-array.gc
Now the failing example in https://github.com/water111/jak-project/issues/563 should look like this, which will be accepted by the compiler.
```lisp
(new 'static 'boxed-array :type generic-dma-foreground-sink :length 0 :allocated-length 9)
```
=> Change syntax for boxed array to support different length and allocated-length

decompiler/IR2/FormExpressionAnalysis.cpp, test/decompiler/reference/kernel/gstring_REF.gc
Code like:
```
(nonzero? (+ (-> arg-word-start 0) -32))
```
will be converted to
```
(!= (-> arg-word-start 0) 32)
```
=> [decompiler] detect small integer not equal

decompiler/IR2/AtomicOpTypeAnalysis.cpp, decompiler/analysis/stack_spill.cpp, decompiler/config/all-types.gc, decompiler/util/DecompilerTypeSystem.cpp, decompiler/util/TP_Type.cpp, decompiler/util/TP_Type.h
Fixed types for large offset loads and added an exception to the stack stuff to allow it to use inconsistent sizes for loading/storing as a workaround for a bug in the original GOAL compiler.
=> [decompiler] Workaround for GOAL fpr -> gpr spill bug and fix >16-bit signed FP loads

decompiler/IR2/bitfields.cpp
`(shl x 16)` is sometimes used to generate an integer constant.
=> [decomp] Handle another case of integer constant

common/type_system/TypeSystem.cpp, common/type_system/TypeSystem.h, decompiler/ObjectFile/LinkedObjectFileCreation.cpp, decompiler/config/all-types.gc, decompiler/config/jak1_ntsc_black_label/label_types.jsonc, decompiler/util/data_decompile.cpp, docs/markdown/progress-notes/changelog.md, goal_src/engine/entity/entity-h.gc, goalc/compiler/StaticObject.cpp, goalc/compiler/StaticObject.h, goalc/compiler/compilation/Static.cpp, goalc/compiler/compilation/Type.cpp, goalc/emitter/ObjectGenerator.cpp, test/decompiler/reference/engine/entity/entity-h_REF.gc, test/goalc/source_templates/with_game/test-type-ref.gc, test/goalc/test_with_game.cpp
This adds a `type-ref` form to the compiler/decompiler to insert a reference to a type in a static object.
There's something weird about this though - the game has `type-ref`s on types that aren't defined yet.  When the linker encounters these, it allocates memory for the type, and in order to do this, it needs to know the number of methods.   To support this, if the type system can't figure out the number of methods, you can manually add a `:method-count` argument.
=> Add type-ref in static data

decompiler/Function/CfgVtx.cpp, decompiler/Function/CfgVtx.h, decompiler/IR2/FormExpressionAnalysis.cpp, decompiler/analysis/stack_spill.cpp, decompiler/analysis/variable_naming.cpp, decompiler/analysis/variable_naming.h, decompiler/config/all-types.gc, decompiler/config/jak1_ntsc_black_label/stack_structures.jsonc, decompiler/util/DecompilerTypeSystem.cpp, test/decompiler/reference/engine/gfx/ripple_REF.gc
- fix multi-block infinite loops
- fix bug with argument registers
- possibly fix bug with vector out of range when trying to call a method without a proper type
- byte stack spills
- ~1K not recognized as a format argument
=> [decompiler] bug fixes related to infinite loop CFGs, argument registers

docs/markdown/progress-notes/changelog.md, goal_src/goal-lib.gc, goal_src/goos-lib.gs, goal_src/kernel/gcommon.gc, goal_src/kernel/gkernel.gc, goal_src/kernel/gstring.gc, goalc/compiler/Compiler.h, goalc/compiler/compilation/Type.cpp, test/offline/offline_test_main.cpp
A few of these still had terrible hand-decompiled functions from months ago.
Also makes `method-of-type` work on type objects that are found at runtime, it just assumes `object`.
=> Clean up files in kernel

decompiler/IR2/Form.h, decompiler/IR2/FormExpressionAnalysis.cpp, decompiler/IR2/FormStack.cpp, decompiler/IR2/FormStack.h, decompiler/analysis/cfg_builder.cpp, test/decompiler/reference/engine/load/file-io_REF.gc, test/decompiler/test_FormExpressionBuild2.cpp
This fixes two bugs that appear to fix all known use-def issues.
First, it fixes a bug where attempted structuring on the same vertex multiple times, resulting in env updates happening twice. Now these are cached.  This was harmless but triggered error.
The second bug is a little more complicated. The structuring pass marks the `(set! x #f)` in the delay slot as not a def, and leaves the defs as the actual expressions that write.  Of course, we may not find one in all cases because of move elimination.
This standardizes on the last non-eliminated set, not in a delay slot, as the result variable to use for a `cond` without an else.
We could possibly use something else if detecting this causes trouble, but this was easy to implement and easy to understand the debug output.
=> Fix use def issues

decompiler/IR2/FormExpressionAnalysis.cpp, decompiler/IR2/FormStack.h, decompiler/analysis/insert_lets.cpp, goal_src/engine/math/quaternion-h.gc, goal_src/engine/math/quaternion.gc, test/decompiler/reference/decompiler-macros.gc, test/decompiler/reference/engine/math/matrix_REF.gc, test/decompiler/reference/engine/math/quaternion_REF.gc, test/decompiler/reference/engine/target/joint-mod-h_REF.gc, test/decompiler/test_FormExpressionBuild2.cpp
New:
```lisp
(defun quaternion-rotate-x! ((arg0 quaternion) (arg1 quaternion) (arg2 float))
(let
((a1-3
(quaternion-vector-angle!
(new-stack-quaternion0)
(vector-x-quaternion! (new-stack-vector0) arg1)
arg2
)
)
)
(quaternion-normalize! (quaternion*! arg0 a1-3 arg1))
)
)
```
Old:
```lisp
(defun quaternion-rotate-x! ((arg0 quaternion) (arg1 quaternion) (arg2 float))
"Rotate existing quaternion along x axis. This has a different implementation
from the others for some reason."
(let ((s4-0 quaternion-vector-angle!)
(s3-0 (new 'stack-no-clear 'quaternion))
)
(set! (-> s3-0 vec quad) (the-as uint128 0))
(let ((t9-0 vector-x-quaternion!)
(a0-1 (new 'stack-no-clear 'vector))
)
(set! (-> a0-1 quad) (the-as uint128 0))
(let ((a1-3 (s4-0 s3-0 (t9-0 a0-1 arg1) arg2)))
(quaternion-normalize! …
```
=> recognize vector, matrix, quaternion constructors in a better way

decompiler/analysis/variable_naming.cpp, goal_src/engine/ps2/rpc-h.gc, goal_src/goal-lib.gc, goalc/compiler/IR.cpp, goalc/listener/Listener.cpp
Fixes:
- Missing casts in decompiler
- Very bad stack address bug in the compiler when using both address of variables and stack structures.
- Bug in `rpc-h` (manually decompiled wrong, a long time ago)
- Removes stupid "loaded twice" warning from compiler.
=> [decompiler] Fix cast bug, compiler stack bug, and rpc-h bug

.gitignore, .vscode/settings.json
Requires VSCode
You will need the following extension - https://github.com/fabiospampinato/vscode-highlight
It has a few rough-edges, but for the most part it's pretty solid
=> tooling: Add some very basic IR2 Syntax Highlighting

.github/workflows/build-doc-app.yaml
Not cleaning up the folder is an issue... https://github.com/water111/jak-project/tree/master/docs/js
This fixes that, leaving the hashes in the file names as it seems a little annoying to fix AND it's for a purpose - it's to cache-bust on a new version of the file.  But the hashes should only change when the file itself changes (the css folder has far fewer versions for example)
=> docs: cleanup frontend artifacts when rebuilding

common/util/DgoReader.cpp, common/util/FileUtil.cpp, tools/dgo_unpacker.cpp
=> Make dgo unpacker work on pal dgos with wrong size

decompiler/ObjectFile/ObjectFileDB_IR2.cpp
will fix https://github.com/water111/jak-project/issues/730
=> [decompiler] Don't crash when static refs pass fails

docs/markdown/progress-notes/changelog.md, goalc/compiler/compilation/Define.cpp, test/goalc/source_templates/with_game/test-set-u64-from-float.gc, test/goalc/test_with_game.cpp
this makes storing consistent with other promotions to 64-bit, which the decompiler and GOAL code both rely on.
=> [goalc] support storing a float in a 64-bit memory location

common/goos/Interpreter.cpp, common/goos/Interpreter.h, common/goos/Object.cpp, common/goos/Object.h, common/goos/Reader.cpp, common/goos/TextDB.cpp, common/goos/TextDB.h, goalc/compiler/Compiler.cpp, goalc/compiler/Compiler.h, goalc/compiler/Env.cpp, goalc/compiler/Env.h, goalc/compiler/Util.cpp, goalc/compiler/Val.cpp, goalc/compiler/compilation/Asm.cpp, goalc/compiler/compilation/Atoms.cpp, goalc/compiler/compilation/Block.cpp, goalc/compiler/compilation/CompilerControl.cpp, goalc/compiler/compilation/ControlFlow.cpp, goalc/compiler/compilation/Define.cpp, goalc/compiler/compilation/Function.cpp, goalc/compiler/compilation/Macro.cpp, goalc/compiler/compilation/Math.cpp, goalc/compiler/compilation/State.cpp, goalc/compiler/compilation/Static.cpp, goalc/compiler/compilation/Type.cpp, goalc/make/MakeSystem.cpp, goalc/regalloc/IRegSet.h, test/test_goos.cpp, test/test_reader.cpp
This speeds up compilation by 25-30%. It now takes under 3 seconds to start the compiler, run `(build-game)`, and exit the compiler.
This adds some new tracking for macros that will be required to do accurate address -> line mapping in the future.
Compiler errors were changed significantly, but should be better in all cases.
=> Compiler performance improvements and error clean-up

decompiler/IR2/FormExpressionAnalysis.cpp, decompiler/IR2/IR2_common.h
Will fix https://github.com/water111/jak-project/issues/815 and improve the error message on int-to-float in cases where it's actually invalid.
Will improve the error message for https://github.com/water111/jak-project/issues/814 to tell you that you might have the return type wrong.
Also will update gtest submodule (https://github.com/water111/jak-project/issues/817), to hopefully prevent a compiler warning on newer versions of Visual Studio.
=> [decompiler] update gtest, fix some small bugs

test/goalc/test_with_game.cpp, tools/MemoryDumpTool/main.cpp
also delete the bogus game-cnt.go file generated by running unit tests.
=> [mem tool] support handles

decompiler/util/data_decompile.cpp, goal_src/engine/gfx/texture.gc, goalc/compiler/compilation/Static.cpp, test/goalc/source_templates/with_game/test-false-in-static-pointer.gc, test/goalc/test_with_game.cpp
should fix https://github.com/water111/jak-project/issues/861
=> Handle pointers set to #f in static structures

decompiler/analysis/atomic_op_builder.cpp, decompiler/config/all-types.gc, decompiler/config/jak1_ntsc_black_label/hacks.jsonc, decompiler/config/jak1_ntsc_black_label/type_casts.jsonc, goal_src/engine/ambient/mood-tables.gc, goal_src/engine/ambient/mood.gc, test/decompiler/reference/engine/ambient/mood-tables_REF.gc, test/decompiler/reference/engine/ambient/mood_REF.gc
There was a case for storing an FPR into the symbol table that wasn't handled in `atomic_op_builder.cpp`.  Otherwise these functions were pretty normal.
There's still some weirdness with the end of the mood-context, but I'm not going to worry about this now - I am pretty sure we match the behavior of the game but might have a few types wrong/a trick misunderstood.
=> Finish up a few functions in mood

common/type_system/state.cpp, common/type_system/state.h, decompiler/IR2/FormExpressionAnalysis.cpp, decompiler/main.cpp, goalc/compiler/compilation/State.cpp, test/decompiler/reference/engine/game/effect-control_REF.gc, test/offline/offline_test_main.cpp
compiler will be less strict about types of functions in `defstate`
decompiler will insert missing cast for `run-function-in-process` with less than 6 args when expression prop fails.
flipped diff for ref tests
=> Small state fixes

common/goos/Interpreter.cpp, common/goos/Interpreter.h, common/goos/Reader.cpp, goal_src/engine/level/level.gc, goal_src/goal-lib.gc, goal_src/goos-lib.gs, goal_src/user/.gitignore, goal_src/user/readme.md, goalc/compiler/Compiler.cpp, goalc/compiler/Compiler.h, goalc/main.cpp, scripts/batch/gc-no-lt.bat, scripts/batch/gc.bat, scripts/batch/repo-settings-mark.bat, scripts/batch/repo-settings-unmark.bat
Implements "user profiles" to GOOS/GOAL, allowing you to have extra custom code loaded at start-up that isnt part of the standard library. Also can be used for conditional compilation to tune settings for specific users.
A username can be selected with the `-user <username>` parameter in `gc`. The `-user-auto` parameter can also be used, and it reads the username from the file `goal_src/user/user.txt` (it reads the first uncommented valid word as the username).
There's a GOOS `user?` macro that will return `#t` if the current user matches any of its arguments. For example, `(user? mark john)` will return `#t` if the current user is either `mark` or `john`, and `#f` otherwise. You can use this for conditional compilation.
There is a `*user*` variable in both GOAL and GOOS which holds the …
=> [goos/goal] user profiles

decompiler/config/jak1_ntsc_black_label.jsonc, docs/markdown/progress-notes/changelog.md, goal_src/engine/camera/cam-layout.gc, goal_src/engine/debug/anim-tester.gc, goal_src/engine/debug/default-menu.gc, goalc/compiler/Compiler.h, goalc/compiler/Env.h, goalc/compiler/compilation/Atoms.cpp, goalc/compiler/compilation/Function.cpp, goalc/compiler/compilation/Macro.cpp, goalc/compiler/compilation/Static.cpp, goalc/compiler/compilation/Type.cpp
This fixes a few places where we put things in the main segment when we should put it in debug.  There is also a `(declare-file (debug))` form to change the default segment to `debug`.
With these fixes, `default-menu`'s `main` segment is empty. In total we save ~109 kB of global heap after loading the engine.
This will fix https://github.com/water111/jak-project/issues/998
and improves https://github.com/water111/jak-project/issues/975 a bit more
=> [goalc] better control over debug-segment

decompiler/IR2/AtomicOpForm.cpp
This fixes an issue where storing a constant integer in a location with
a type that is both an enum/bitfield and a child of signed integer. The
logic for dropping casts for signed integer constants was accidentally
being applied to any child of `integer`.
=> [decompiler] Fix stores of constant enum/bitfield

game/graphics/opengl_renderer/SkyBlendCPU.cpp, game/graphics/opengl_renderer/tfrag/Tfrag3.cpp
fixes weird sky colors due to integer overflow when there's lightning and a bug where some tfrag trees never loaded their vertices.
=> fix sky and tfrag bugs

.github/workflows/windows-workflow.yaml
this is a wrapper for `choco` that will retry on transient errors, hopefully making our build more consistent.
=> ci: retry on transient chocolatey failures

common/goos/Reader.cpp, common/goos/Reader.h, common/goos/TextDB.h, goalc/compiler/Compiler.cpp, goalc/compiler/Compiler.h, test/offline/offline_test_main.cpp
```
-- Compilation Error! --
No method or function named obj for type type
Form:
(obj vec4s)
Location:
gcommon:108
((obj vec4s))
^
Code:
(obj vec4s)
```
errors with the real file name instead of just `string`.
=> [ref tests] pass filename through on compile failures

README.md
This explicitly links our Discord as well as adding a "PRs Welcome" badge to our existing badges in order to encourage new users and potential contributors to seek out assistance for questions they might have.
=> Append contributor resources to README.md

common/custom_data/Tfrag3Data.h, common/util/FrameLimiter.h, decompiler/level_extractor/extract_tfrag.cpp, decompiler/level_extractor/extract_tfrag.h, decompiler/level_extractor/extract_tie.cpp, game/graphics/opengl_renderer/BucketRenderer.cpp, game/graphics/opengl_renderer/BucketRenderer.h, game/graphics/opengl_renderer/OpenGLRenderer.cpp, game/graphics/opengl_renderer/SkyRenderer.cpp, game/graphics/opengl_renderer/SkyRenderer.h, game/graphics/opengl_renderer/debug_gui.cpp, game/graphics/opengl_renderer/debug_gui.h, game/graphics/opengl_renderer/tfrag/TFragment.cpp, game/graphics/opengl_renderer/tfrag/TFragment.h, game/graphics/opengl_renderer/tfrag/Tfrag3.cpp, game/graphics/opengl_renderer/tfrag/Tie3.cpp, game/graphics/opengl_renderer/tfrag/Tie3.h, game/graphics/opengl_renderer/tfrag/tfrag_common.cpp, game/graphics/opengl_renderer/tfrag/tfrag_common.h, game/graphics/pipelines/opengl.cpp, goal_src/engine/gfx/background.gc
To get "accurate" PS2-like behavior when lagging, you must turn on frame limiter and the experimental accurate lag mode.
To actually change the frame limit, you must enter the number and then click apply.
=> add vis data to tie/tfrag and better framelimiting/lag

Taskfile.yml
- was double nesting with `jak1/jak1`
- if you've never built the kernel before `gk.exe` will crash and running the repl with it trying to connect to the game has too long of a time-out, so added another recipe that doesn't auto connect.
=> scripts: adjust fix Taskfile recipes to work with recent changes

decompiler/main.cpp
Be explicit about the folder it can't find and switch the poor-mans version check / ISO extraction check to a warning instead.
=> decomp: futher improve the error messages when running the decompiler

CMakeLists.txt, common/custom_data/TFrag3Data.cpp, common/custom_data/Tfrag3Data.h, common/util/FileUtil.cpp, common/util/os.cpp, common/util/os.h, decompiler/level_extractor/extract_level.cpp, decompiler/level_extractor/extract_tfrag.cpp, decompiler/level_extractor/extract_tie.cpp, game/graphics/opengl_renderer/DirectRenderer.cpp, game/graphics/opengl_renderer/Loader.cpp, game/graphics/opengl_renderer/MercRenderer.h, game/graphics/opengl_renderer/SkyBlendCPU.cpp, game/graphics/opengl_renderer/tfrag/Tfrag3.cpp, game/graphics/opengl_renderer/tfrag/Tie3.cpp, game/graphics/opengl_renderer/tfrag/Tie3.h, game/graphics/opengl_renderer/tfrag/tfrag_common.cpp, game/graphics/texture/TexturePool.cpp, game/main.cpp, test/test_common_util.cpp
The current size of the fr3 files is 368 MB, which is pretty big.
With these changes it goes down to about 112 MB, which is still bigger than I'd like. I think we can go a lot lower if we have less duplicate data between lods (tfrag vertices for instance, many are duplicate other than color indices)
=> [graphics] reduce the size of fr3 files

common/dma/gs.h, game/graphics/opengl_renderer/BucketRenderer.cpp, game/graphics/opengl_renderer/OpenGLRenderer.cpp, game/graphics/opengl_renderer/Sprite3.cpp, game/graphics/opengl_renderer/Sprite3.h, game/graphics/opengl_renderer/shaders/sprite3_3d.frag, game/graphics/opengl_renderer/shaders/sprite3_3d.vert, game/graphics/opengl_renderer/tfrag/tfrag_common.cpp
- Fix ordering issue in sprite3 (fixes progress menu tint and powercell sprite issue)
- Fix bug in sprite shader - the scale shouldn't be clamped to the max scale for HUD sprites
- Add blend mode for bomb shadow
- set default sprite renderer to sprite3
=> [sprite] switch to sprite3, fix bugs

game/mips2c/functions/joint.cpp, game/mips2c/mips2c_private.h
kermit.gc does:
```
(set! (-> arg1 scale data (-> s4-0 forward-axis)) (-> s4-0 forward-scale-control))
(cspace<-parented-transformq-joint! arg0 arg1)
```
where `forward-scale-control` is 0 when the tongue is retracted fully.  The `cspace<-parented-transformq-joint!` divides by scale and was ending up with NaNs.  Modifying mips2c `div` (just in that function) to handle divide by 0 like the PS2 fixes it.
=> [graphics] fix plant and frog sps

game/CMakeLists.txt, game/graphics/opengl_renderer/EyeRenderer.cpp, game/graphics/opengl_renderer/EyeRenderer.h, game/graphics/opengl_renderer/OpenGLRenderer.cpp, game/graphics/opengl_renderer/Shader.cpp, game/graphics/opengl_renderer/Shader.h, game/graphics/opengl_renderer/SkyBlendCPU.cpp, game/graphics/opengl_renderer/SkyBlendCPU.h, game/graphics/opengl_renderer/SkyBlendGPU.cpp, game/graphics/opengl_renderer/SkyBlendGPU.h, game/graphics/opengl_renderer/TextureUploadHandler.cpp, game/graphics/opengl_renderer/opengl_utils.cpp, game/graphics/opengl_renderer/opengl_utils.h, game/graphics/opengl_renderer/shaders/eye.frag, game/graphics/opengl_renderer/shaders/eye.vert
There are lots of advantages to doing eyes on the GPU:
- lets us increase the texture size (default is 128x128 now)
- filtering + blending works (unlike my CPU version, which didn't work right when doing both on the pupils)
- the slight offset bug is gone (I guess I don't fully understand how filtered textures work along the edges?)
- we now use the full precision of the animation. The old version had a bug where the lower 4 bits were lost.
=> [graphics] Do eyes on the GPU, fix filtering and offsets

game/graphics/opengl_renderer/foreground/Generic2.h, game/graphics/opengl_renderer/foreground/Generic2_Build.cpp, game/graphics/opengl_renderer/foreground/Generic2_OpenGL.cpp
Fixes two envmap bugs:
- make sure we obey the fogging disable flag set in the `PRIM` register of the giftag (causes "popping" of envmap effect that's pretty obvious as you move away from the misty doors)
- disable draw reordering for HUD draws. Collecting orbs on a crate from a zoomer draws a bunch of orbs on top of each other, which doesn't look right.  As far as I know, this is the only place it happens, so we can work around by disabling the reorder on anything that uses the HUD matrix.
=> fix envmap bugs in generic2

game/graphics/opengl_renderer/DirectRenderer.cpp, game/graphics/opengl_renderer/DirectRenderer2.cpp, game/graphics/opengl_renderer/background/background_common.cpp, game/graphics/opengl_renderer/foreground/Generic2_OpenGL.cpp, game/graphics/opengl_renderer/ocean/OceanTexture.cpp
This fixes some alpha-related issues and (as a hack) just disables writing to the z buffer for the ocean.
=> [graphics] fix ocean alpha and ocean near depth

game/system/newpad.cpp
This adjusts the controller mapping for both gamepad and keyboard to make it more playable. Specifically:
* ~~On gamepad, the right-hand X axis is inverted, now feels correct when used with an Xbox controller. (I'm not sure if this will cause a regression if you're using a PS3 controller, or if the behaviour was incorrect on PS3 controller too - can anyone confirm?).~~
* On keyboard, analog stick movement is now implemented on WASD, and camera controls are on IJKL.
* On keyboard, buttons are now mapped in a scheme that feels somewhat playable (though controller is still preferable):
* X: Space
* Square: F
* Circle: E
* Triangle: R
* R1: Q
=> Input scheme quick fixes

.github/workflows/windows-workflow.yaml
From the last comment here https://github.com/mbitsnbites/buildcache/issues/194#issuecomment-778237822 it seems to be that clang-cl with buildcache still doesn't completely work as expected.
It _seems_ to be working, but not caching anything, as mentioned above:
<details>
<summary>Logs</summary>
```
BuildCache[4768] (DEBUG) Found exe: C:\Program Files\LLVM\bin\clang-cl.exe (C:\PROGRA~1\LLVM\bin\clang-cl.exe, C:\PROGRA~1\LLVM\bin\clang-cl.exe)
BuildCache[4768] (DEBUG) Removing expired data store item "2bb81a33314c1ea562bbd46450c288df"
BuildCache[4768] (DEBUG) Program ID cache miss for C:\PROGRA~1\LLVM\bin\clang-cl.exe
BuildCache[4768] (DEBUG) Invoking: C:\PROGRA~1\LLVM\bin\clang-cl.exe --version
BuildCache[4768] (DEBUG) Filtered arguments: clang-cl.exe /nologo -TP -imsvc …
```
=> ci: stop trying to cache `clang-cl` builds

.github/scripts/releases/upload-release-artifacts/.gitignore, .github/scripts/releases/upload-release-artifacts/index.js, .github/scripts/releases/upload-release-artifacts/package-lock.json, .github/scripts/releases/upload-release-artifacts/package.json, .github/workflows/architecture/releases.md, .github/workflows/draft-new-release.yaml, .github/workflows/inform-pages-repo.yaml, .github/workflows/linux-workflow.yaml, .github/workflows/windows-workflow.yaml, CMakeLists.txt, common/CMakeLists.txt, decompiler/CMakeLists.txt, goalc/CMakeLists.txt, third-party/fmt/CMakeLists.txt, third-party/imgui/CMakeLists.txt, third-party/lzokay/CMakeLists.txt, third-party/mman/CMakeLists.txt
It's a bit tedious to test these things so hopefully i didn't miss anything on the conversion from my fork back to this repo.  But this process has worked well over on pcsx2 (around 500 releases at this point, we won't be releasing nearly that much).  The test i finally got to work - https://github.com/xTVaser/jak-project/releases/tag/v0.1.3
Releases are created manually via workflow dispatch, release notes are currently not automatically generated, but should be pretty easy to do cleanly since we squash merge everything:
A draft release is created until all the necessary assets are uploaded:
And then it's live (ignore the naming, from a previous run, they should all be `open-goal-<windows/linux>-<decompiler/gk/goalc>.<bin/exe>`
```mermaid
sequenceDiagram
Project Repo->>Project Repo: New …
```
=> ci: Add an automated release process

common/custom_data/TFrag3Data.cpp, common/custom_data/Tfrag3Data.h, decompiler/level_extractor/extract_shrub.cpp, decompiler/level_extractor/extract_tfrag.cpp, decompiler/level_extractor/extract_tie.cpp, game/graphics/opengl_renderer/Loader.cpp, game/graphics/opengl_renderer/background/Shrub.cpp, game/graphics/opengl_renderer/background/Shrub.h, game/graphics/opengl_renderer/background/TFragment.cpp, game/graphics/opengl_renderer/background/TFragment.h, game/graphics/opengl_renderer/background/Tfrag3.cpp, game/graphics/opengl_renderer/background/Tfrag3.h, game/graphics/opengl_renderer/background/Tie3.cpp, game/graphics/opengl_renderer/background/Tie3.h, game/graphics/opengl_renderer/background/background_common.cpp, game/graphics/opengl_renderer/background/background_common.h
Switch non-wind TIE, all tfrag, and all shrub, to use `glMultiDrawElements`.  This updates the TFRAG3 format to version 14, so you'll need to extract levels after this change.
At the starting point, the frame time is 6.3ms now, down from 7.6ms.  I think there's probably another few hundred microseconds to gain from TIE wind improvements.
=> [graphics] use multidraws in tie/tfrag/shrub

game/system/newpad.cpp, game/system/newpad.h
if it's just an array of bools, there's no harm if the game/glfw read/write simultaneously. Played for ~5 minutes with no crash, so it seems fixed.
=> fix crash when using keyboard controls

game/graphics/opengl_renderer/background/Tfrag3.cpp
will close #1292 
This avoids deleting time of day textures that were never created.
=> [tfrag] skip creating trees that are never setup

game/overlord/fake_iso.cpp, game/overlord/iso_api.cpp, game/overlord/iso_cd.cpp
This fixes a bug when file A is closed in the same iteration of the iso thread loop that a read from file B completes.
There is a feature that detects if file A is closed, and you have a buffer remaining for file A, then discard the buffer. But obviously this should not happen if file A is closed and you have a buffer for file B ready to go.
This fixes a reliable (for me) visibility corruption bug when riding the gondola up to snowy mountain while there is a heavy system load. The GORDOWN file is closed on the same iso thread loop as the first buffer for SNO.VIS is filled, and this buffer was incorrectly discarded.
=> [overlord] fix fakeiso close bug

decompiler/extractor/main.cpp
Noticed this in someone's video.
=> Fix fancy console colors not working for extractor

.vs/launch.vs.json, common/util/read_iso_file.cpp, common/util/read_iso_file.h, decompiler/extractor/main.cpp, third-party/xxhash.hpp, vendor.yaml
This will enable better UX over on the launcher side, but also catches non-issues early in the process (if the ISO is modified / a very we don't yet support).
The feature always wrongs, but will only fail if enabled -- it will output the C++ snippet to add to the database if it's a missing entry.
Also fixes a bug in the extractor that I caused the other day.
=> extractor: Validate ISO contents and report specific errors

.github/workflows/linux-workflow.yaml
Linux was including the `ci-artifacts/` folder in the tarball
=> ci: make linux release artifact structure match windows

decompiler/extractor/main.cpp
Three changes here:
- extract iso files to `data/iso_data/jak1`. This makes `goalc`'s `(mi)` work on the release for people who want to play around.
- fix extracting for folder. It's useful for debugging because it takes a bit to extract the ISO
- only accept folders if an explicit flag is given. For actual use, we'll only support ISOs, and the launcher won't provide this flag.
Will close https://github.com/open-goal/jak-project/issues/1332
=> [extractor] extract iso to a better spot

common/cross_sockets/XSocket.cpp, common/cross_sockets/XSocket.h, game/system/Deci2Server.cpp
The DECI2 thread was not joining as the call to `accept` is blocking.  The proper way to do this is to instead call `select()` with a timeout, and if it returns successfully, accept it.
This still means there is a slight pause (max of 0.1s) when exiting the game, but this can be reduced (or removed entirely if we just terminate the thread, I don't see the harm in doing so if no client has connected to it)
Closes #1362
Closes #1366
=> game/deci2: Add a timeout on waiting for a client to connect to DECI2

common/goos/Interpreter.cpp, game/kernel/kboot.h, game/kernel/kmachine.cpp, game/overlord/overlord.cpp, game/sound/sdshim.cpp, game/sound/sndshim.cpp, goal_src/game.gp, test/goalc/framework/test_runner.cpp, test/goalc/source_templates/with_game/test-build-all-code.gc, test/goalc/test_with_game.cpp
- adds a toggle to disable sound for unit tests.  Even though we tolerate `cubeb_init` failing, I hit an assert in pulseaudio when running tests on my laptop. 
- clean up logic for IOP argument string lengths
- actually build level code in type consistency (oops) and fix up deps for the `all-code` group.
=> make linux tests pass again

common/util/Assert.cpp, common/util/Assert.h, decompiler/IR2/FormExpressionAnalysis.cpp, test/test_common_util.cpp
If we ever want to turn asserts off, we can now do it by just defining a single macro.
=> assert toggle

game/graphics/opengl_renderer/background/background_common.cpp
closes #1297 
Avoids splitting into two draws (which causes blending issues) if the alpha test is configured in a "useless" way.
We previously caught one of these cases (setting alpha test to NEVER, FB_ONLY to disable depth writes), but now we catch the one used on the title screen (alpha test FB_ONLY, but depth writes always disabled). In this case, we don't need to do the draw splitting at all, so we can get more accurate blending by doing 1 draw with no alpha stuff.
=> [graphics] improve blending when depth write is disabled

decompiler/config/all-types.gc, goal_src/kernel/gkernel.gc, goal_src/levels/village2/swamp-blimp.gc, test/decompiler/reference/levels/village2/swamp-blimp_REF.gc
Will close #1365 and #1336.
When a process is `deactivate`d, the state is set to `dead-state`, and all stack frames are exited, including the `exit` for the current  `state`.  I had a typo in the decompilation of `gkernel.gc`, so the name of `dead-state` is `#f` instead of `'dead-state`. This caused the wrong branch in `process-taskable idle` to be taken, killing all in progress level hints.  This is likely what killed daxter hints.
Also fix a type bug in `swamp-blimp` that caused the cutscene at the end to not play. Wasn't caught by the decompiler because its the usual weird `event` handler stuff.
=> [game] fix ambients stopping and swamp blimp tethers

goal_src/engine/nav/navigate.gc, goal_src/engine/target/logic-target.gc
`ps` crash was because `target` was using the original game's stack size, but should use the updated one.
the ram would disappear because the `navigate` stuff looked at the position of other enemies which are NaNs. All the enemies in the area had a weird chain of setting each other to NaN and I'm not really sure how it all started. I suspect that the stupid snow bunny disappearing or being spawned in because of visibility is the cause, but can't prove it 100% yet.
On PS2 though, this would have behaved like the enemy is infinitely far away, and wouldn't be included in the nav mesh, so explicitly ignoring NaN things doesn't seem like the worst workaround.
=> [game] fix ps crash and disappearing ram

game/graphics/opengl_renderer/EyeRenderer.cpp
Fixes the borders of eyes that are smaller than the 32x32 region when using the GPU eye renderer. The color of the corner should be used as the background in this case, but there was a bug in reading it.
=> [graphics] fix edges of small eyes

decompiler/config/all-types.gc, goal_src/goal-lib.gc, goal_src/kernel-defs.gc, goal_src/kernel/gcommon.gc, goal_src/kernel/gkernel-h.gc, goal_src/kernel/gkernel.gc, goal_src/kernel/gstate.gc, goal_src/kernel/gstring.gc, test/decompiler/reference/kernel/gkernel_REF.gc, test/decompiler/test_gkernel_decomp.cpp, test/goalc/source_templates/with_game/test-load-game.gc, test/goalc/test_with_game.cpp
Clean up some old documentation, use `link-flags` in a few more places.
=> [decomp] clean up KERNEL.CGO code

game/kernel/kmachine.cpp
When in an indoors area, the small time of day icon and text were not being cleared properly and would be filled with garbage data, which resulted in the game status not being updated until you left the area.
=> [discord-rpc] fix status not being updated while indoors

common/symbols.h, decompiler/Function/CfgVtx.cpp, decompiler/ObjectFile/LinkedObjectFile.cpp, decompiler/ObjectFile/ObjectFileDB_IR2.cpp, decompiler/analysis/atomic_op_builder.cpp, decompiler/analysis/atomic_op_builder.h, decompiler/analysis/cfg_builder.cpp, decompiler/analysis/mips2c.cpp, decompiler/analysis/mips2c.h, decompiler/config.cpp, decompiler/config.h, decompiler/config/all-types2.gc, decompiler/config/jak1_ntsc_black_label.jsonc, decompiler/config/jak2/hacks.jsonc, decompiler/config/jak2_ntsc_v1.jsonc, decompiler/main.cpp, game/graphics/gfx.cpp, game/kernel/klink.cpp, game/kernel/klisten.cpp, game/kernel/kmachine.cpp, game/kernel/kprint.cpp, game/kernel/kscheme.cpp, game/mips2c/mips2c_table.cpp, goalc/compiler/IR.cpp, goalc/debugger/Debugger.cpp, test/decompiler/FormRegressionTest.cpp, test/decompiler/test_AtomicOpBuilder.cpp, test/offline/offline_test_main.cpp, test/test_kernel.cpp, tools/MemoryDumpTool/main.cpp
small tweaks required to get all of jak 2 going through atomic ops pass.  There's still some missing stuff, but it's  enough for all the inspect methods and top-levels to get through ao.
This is as much as we need to develop the type inspector stuff, so at this point I'm going to transition to working on decompiler improvements and stop working on jak 2 specific missing things.
=> [decompiler] cleanup to get atomic ops working on jak2 inputs

goal_src/engine/gfx/font.gc
Fixes a bug in the original font renderer where the font shadow offset changed depending on the aspect ratio. It's particularly noticeable with smaller fonts and very wide screens.
=> [game] fix shadow offset in widescreen

game/graphics/opengl_renderer/debug_gui.cpp, game/graphics/opengl_renderer/debug_gui.h, game/graphics/pipelines/opengl.cpp
This is not totally perfect because it uses the primary monitor.  Though this is a gap in our code in general (other places just use the primary monitor as well).
Ideally we'd remember which monitor the game was opened on / is within and handle things accordingly.
Needs to be tested on a slow monitor, for my 144hz -- the game finally runs at the proper speed by default (60fps feels so slow compared to 400fps...)
Likely supersedes #1288
=> game: automatically apply framelimiter on high refresh rate monitors

.github/scripts/releases/error-code-metadata.json, .github/scripts/releases/extract_build_linux.sh, .github/scripts/releases/extract_build_windows.sh, .github/workflows/linux-workflow.yaml, .github/workflows/windows-workflow.yaml, common/log/log.cpp, common/util/FileUtil.cpp, decompiler/extractor/main.cpp
This adds a simple metadata file to the release process that lets the launcher know what error codes mean.  This keeps this repo as the source of truth instead of having to make assumptions in the launcher (and hoping nothing changes).
Also got rid of the `out/` subfolder inside the release assets
=> release: include error metadata file for launcher purposes

.github/workflows/linux-workflow.yaml
On the Linux release version, `cubeb` would fail to init on systems that use Pipewire as the audio backend due to a missing build dependency.
=> actions: add `libpulse-dev` dependency to fix audio on pipewire systems

game/overlord/soundcommon.cpp
`bonelurker-grunt` uses the full 16 characters, so there is no null-terminator.  The print would overflow and read until the next name's null terminator.
The resulting print of the random garbage between was the cause of the mystery chime.
=> game: remove mystery windows chime sound when starting up

README.md
Managed to get it to successfully compile with Clang on a Fedora VM (after adding `#include <array>` to `lzokay.cpp`), but I couldn't test anything because I would get `Illegal instruction` errors, likely due to AVX not working in the VM I was using.
=> readme: add fedora build instructions

game/graphics/display.h, game/graphics/gfx.cpp, game/graphics/gfx.h, game/graphics/pipelines/opengl.cpp, game/graphics/pipelines/opengl.h, game/kernel/kmachine.cpp, goal_src/engine/gfx/texture.gc, goal_src/engine/sparticle/sparticle-launcher.gc, goal_src/kernel-defs.gc, goal_src/pc/pckernel-h.gc, goal_src/pc/pckernel.gc
Fixes lag due to setting window size every frame and adds a window lock so that users can't resize/maximize the window (it won't work). The lock can be changed using `set-window-lock!` if you want to have free control.
=> windows graphics fixes

game/tools/subtitles/subtitle_editor.cpp
=> tools: only allow valid language-ids to be selected in the subtitle editor

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/enhancement-request.yml, .github/ISSUE_TEMPLATE/feature-request.yml, goalc/build_level/gltf_mesh_extract.cpp
This:
- adds some acknowledgements to the bug report (check for duplicates, have your own legit copy)
- asks if they've reproduced the bug on original hardware or not as this is often a first step we take
- improves the version gathering input, as just "release" is too ambiguous
- formats the issue template's yaml a bit
=> github: improve bug report issue template

common/goos/ParseHelpers.h, common/versions.h, decompiler/main.cpp, docs/progress-notes/changelog.md, goalc/compiler/Compiler.cpp, goalc/compiler/Compiler.h, goalc/compiler/Util.cpp, goalc/compiler/compilation/Atoms.cpp, goalc/compiler/compilation/CompilerControl.cpp, goalc/compiler/compilation/Macro.cpp, goalc/make/Tools.cpp, goalc/regalloc/Allocator_v2.cpp, goalc/regalloc/IRegSet.h
The idea described in https://github.com/open-goal/jak-project/issues/1538, plus a few small tweaks to make things a little faster. This also cleans up `asm_file` and how the make system runs the compiler to make the end of the error messages less silly
=> compiler speed improvement

.github/scripts/releases/error-code-metadata.json, decompiler/extractor/main.cpp
This adds some additional context to the extractor, checking the extension type of the game data path if it is not a folder, and returning a more user-friendly error if the game data file is not valid. When I get home I will finish this by adding a size and header check and making sure the error code is properly returned to the launcher. 
Addresses #1539, hoping I'm on the right track here.
=> Replace assert with user-friendly error if ISO is invalid or not found

game/graphics/opengl_renderer/foreground/Merc2.cpp, game/graphics/opengl_renderer/shaders/merc2.vert
Prevents a bug where merc models will disappear due to NaNs in "unused" bones.
=> [merc2] guard against nans in bones

game/overlord/ssound.cpp
Super simple fix to match the original overlord behavior for `CalculateFalloffVolume`.
Fixes #1380.
=> Fix volume calculation when falloff curve is zero

common/goos/ReplUtils.cpp, common/util/FileUtil.cpp, common/util/FileUtil.h, game/kernel/jak1/kmachine.cpp, game/kernel/jak2/kmachine.cpp
Closes #1578 
For Linux:
- Prefers `$XDG_CONFIG_HOME/OpenGOAL` or `$HOME/.config/OpenGOAL`
For Windows:
- `$APPDATA/OpenGOAL`
- `$APPDATA` is equivalent to `$CSIDL_APPDATA` which can be equal to `C:\Documents and Settings\username\Application Data` or `C:\Users\username\AppData\Roaming`
- There is probably a more consistent way using `FOLDERID_RoamingAppData` but:
- You have to either use a Win32 API `SHGetFolderPathW` or a vista+ `SHGetKnownFolderPath` function.  The former uses annoying utf-16 and the latter introduces a new minimum requirement.
=> config: change linux and windows config directories

game/sce/libscf.cpp
Makes `sceCdReadClock` pass the correct date values as required by `scf-get-time` in GOAL by converting every decimal value to a hex `u8` with the same digit representation.
=> game: read current date correctly for save data

goal_src/jak1/pc/pckernel-h.gc, goal_src/jak1/pc/pckernel.gc
Adds a new cheat code that toggles the time of day system to use the real system time.
**Note**: This will only work properly once #1590 is merged.
=> game: add real-time time of day cheat code

game/kernel/common/kmachine.cpp, game/sce/libpad.cpp, game/sce/libpad.h, game/system/newpad.cpp, game/system/newpad.h, third-party/glfw/include/GLFW/glfw3.h, third-party/glfw/src/cocoa_joystick.m, third-party/glfw/src/input.c, third-party/glfw/src/internal.h, third-party/glfw/src/linux_joystick.c, third-party/glfw/src/linux_joystick.h, third-party/glfw/src/null_joystick.c, third-party/glfw/src/win32_init.c, third-party/glfw/src/win32_joystick.c, third-party/glfw/src/win32_platform.h, third-party/glfw/tests/joysticks.c
Adds rumble support to the GLFW library and the game kernel.
Tested on Linux and with a DualSense controller.
Closes #1597
=> glfw, game: add rumble support

common/type_system/Type.h, decompiler/ObjectFile/ObjectFileDB_IR2.cpp, decompiler/analysis/analyze_inspect_method.cpp, decompiler/analysis/analyze_inspect_method.h, decompiler/config/jak2/hacks.jsonc
Support `inspect` methods of processes, use decompiler "guesses" a little more aggressively.
=> [decompiler] missing features in inspect method detection

decompiler/IR2/AtomicOpForm.cpp, decompiler/IR2/Form.cpp, decompiler/IR2/Form.h, decompiler/IR2/FormExpressionAnalysis.cpp, decompiler/analysis/cfg_builder.cpp, decompiler/config/jak2/all-types.gc, decompiler/config/jak2/anonymous_function_types.jsonc, decompiler/config/jak2/hacks.jsonc, decompiler/config/jak2/type_casts.jsonc, test/decompiler/reference/levels/beach/seagull_REF.gc, test/decompiler/reference/levels/finalboss/robotboss_REF.gc
Nothing too interesting in `gcommon`. A few tiny changes:
- `inspect` an array checks to see if the `content-type` is a basic before reading it
- `valid?` is updated for the new symbol stuff
-  `type-type?` checks for the input type being 0
- new `type?` function
- `vector` is defined in `gcommon` now
- `array`'s `asize-of` method uses `(-> obj type size)`, rather than `(-> array size)`
We can use this file to set up the jak2 decomp tests, and as a test for the jak2 compiler changes.
=> [decompiler] jak2-style rtype-of, setup gcommon stuff

common/CMakeLists.txt, common/versions.cpp, common/versions.h, decompiler/extractor/main.cpp, game/kernel/jak1/kmachine.cpp, game/runtime.cpp, game/sce/deci2.cpp, game/sce/deci2.h, game/system/Deci2Server.cpp, game/system/Deci2Server.h, goal_src/goal-lib.gc, goal_src/jak1/compiler-setup.gc, goal_src/jak1/kernel-defs.gc, goal_src/jak2/compiler-setup.gc, goal_src/jak2/kernel-defs.gc, goalc/compiler/Compiler.cpp, goalc/compiler/Compiler.h, goalc/main.cpp, test/goalc/test_arithmetic.cpp, test/goalc/test_collections.cpp, test/goalc/test_compiler.cpp, test/goalc/test_control_statements.cpp, test/goalc/test_debugger.cpp, test/goalc/test_game_no_debug.cpp, test/goalc/test_goal_kernel.cpp, test/goalc/test_variables.cpp, test/goalc/test_with_game.cpp, test/offline/offline_test_main.cpp
This doesn't make any changes to the compiler for jak2 differences, but just sets up the framework for having multiple versions:
- `goal_src/<version>/compiler-setup.gc` is a place to load game-specific stuff like `kernel-defs.gc`, `game.gp` and others (like the jak1 art group stuff)
- `Compiler` takes a version in the constructor. This can be accessed by all C++ `Compiler` code and in GOAL with `GAME_VERSION`.
- `goalc` program defaults to jak1, but takes a `--game jak2` argument like the offline tests.
- other misc small fixes. For now, the majority of tests are jak1 only.
=> [jak2] goalc supports multiple projects

common/dma/gs.h, common/math/Vector.h, docs/scratch/sprite_distort_vu1.txt, game/graphics/opengl_renderer/BucketRenderer.h, game/graphics/opengl_renderer/OpenGLRenderer.cpp, game/graphics/opengl_renderer/Shader.cpp, game/graphics/opengl_renderer/Shader.h, game/graphics/opengl_renderer/Sprite3.cpp, game/graphics/opengl_renderer/Sprite3.h, game/graphics/opengl_renderer/shaders/sprite_distort.frag, game/graphics/opengl_renderer/shaders/sprite_distort.vert, goal_src/jak1/engine/gfx/sprite/sprite-distort.gc, goal_src/jak1/engine/gfx/sprite/sprite.gc
This PR implements the sprite distortion effect as part of the sprite3 renderer.
I'm still fairly new to a lot of stuff in this project, so if there's anything I need to refactor or clean up please let me know!
The sprite distort effect needs to read the active framebuffer to do its thing. I implemented this by creating a separate framebuffer managed by the sprite renderer. When it comes time to render sprite distortion, the default framebuffer's color buffer is blitted (using `glBlitFramebuffer`) to this framebuffer. Then the color buffer of this framebuffer is bound to the shader as a texture. I'm not sure what the performance implications of this are. I have a feeling there's a faster way to implement this effect, but this was a super simple approach.
Since the sprite renderer managed …
=> Sprite Distort

game/graphics/opengl_renderer/Shader.cpp, game/graphics/opengl_renderer/Shader.h, game/graphics/opengl_renderer/Sprite3.cpp, game/graphics/opengl_renderer/Sprite3.h, game/graphics/opengl_renderer/shaders/sprite_distort_instanced.frag, game/graphics/opengl_renderer/shaders/sprite_distort_instanced.vert
This adds an additional render path to use instancing for sprite distort instead of one giant mesh. A neat part about this is that a good chunk of the original VU calculations are now in the shader.
The way this works is: vertex data for each possible sprite resolution is calculated ahead of time (and recalculated whenever the sine table changes). This results in much less vertex data and doesn't need to be re-uploaded to the GPU every frame. The pre-calculated vertex data just contains position and texture coordinate information from the sine tables. Then, each frame the sprite-specific data is sent to the GPU as an instanced array containing the per-frame sprite position, scale, and texture coordinates. Finally, the shader then does the original VU calculations with the sine table data …
=> Sprite Distort Instancing

goal_src/jak1/engine/common-obs/generic-obs.gc, goal_src/jak1/engine/common-obs/rigid-body.gc, goal_src/jak1/engine/ui/hud-classes.gc, goal_src/jak1/levels/racer_common/racer-part.gc, goal_src/jak1/levels/rolling/rolling-lightning-mole.gc, goal_src/jak1/levels/swamp/kermit.gc, goal_src/jak1/levels/swamp/swamp-rat.gc
Fixes high FPS issues with:
- Rigidbody simulation (fixes #1511 and issue with floating platforms snapping back to their neutral position when Jak jumps off them too quickly)
- Lightning moles leaving the 'chase' state too easily (fixes the remaining issue in #1524)
- Swamp rats wiggling too fast
- 'Kermit' zipping to Jak while airborne
- Low health HUD flashing
- Low eco HUD flashing
- High zoomer heat HUD flashing
- Camera rotation when falling from a blue eco launcher
Some of these issues were listed in the mega thread #1499
=> Some high FPS fixes

decompiler/ObjectFile/LinkedObjectFile.cpp
Fixes #1631.
The decompiler has a separate link type for the empty pair - it shouldn't have a string.  This won't make much difference in actual memory usage, but makes valgrind happy.
=> [decompiler] fix memory leak on empty pairs

game/graphics/gfx.h, game/graphics/opengl_renderer/OpenGLRenderer.cpp, game/graphics/pipelines/opengl.cpp, goal_src/jak1/pc/pckernel.gc
In this mode, you can resize the window and pick the resolution from the menu.  When the resolution is selected, it will adjust the window to that resolution, but still allows you to resize it as needed.
All the old letterboxing/aspect ratio stuff works like normal.
I tested this for a bit on linux and it seemed to work pretty well, but not sure if there's windows-specific things to watch out for.
=> [graphics] Another possible way to handle windowed

game/mips2c/functions/sparticle_launcher.cpp
The particle adgif cache will crash if the first particle ever launched has a texture-id of 0. It's not clear if this is something that should be supported, but booting up 150fps with ps2-parts enabled causes it. If we just make the cache not crash, the game seems to work fine.
=> [sparticle] workaround for 150fps crashes

goal_src/jak1/engine/gfx/foreground/bones.gc
Will fix https://github.com/open-goal/jak-project/issues/1433
The detection for eyes was wrong and made small models accidentally render with generic.
=> [gfx] fix merc/generic eye detection

decompiler/config/jak2/all-types.gc, game/graphics/pipelines/opengl.cpp, game/kernel/jak1/kscheme.cpp, game/mips2c/functions/collide_cache.cpp, game/mips2c/functions/collide_edge_grab.cpp, goal_src/jak2/kernel/gkernel-h.gc, goalc/build_level/collide_bvh.cpp, test/goalc/CMakeLists.txt, test/goalc/all_goalc_template_tests.cpp, test/goalc/framework/test_runner.cpp, test/goalc/framework/test_runner.h, test/goalc/source_templates/jak2/kernel-test.gc, test/goalc/test_arithmetic.cpp, test/goalc/test_collections.cpp, test/goalc/test_compiler.cpp, test/goalc/test_control_statements.cpp, test/goalc/test_debugger.cpp, test/goalc/test_goal_kernel2.cpp, test/goalc/test_jak2_compiler.cpp, test/goalc/test_type_consistency.cpp, test/goalc/test_variables.cpp, test/goalc/test_vector_float.cpp, test/goalc/test_with_game.cpp, third-party/xdelta3/xdelta3/xdelta3.h
- Split a few of the giant goalc test files. Remove the `all_goalc_template_tests.cpp` file and use individual files. After the cleanup, this no longer helped compile times.
- Clean up includes, restructure so we don't the `inja` include for tests that don't generate GOAL code - this saves a lot of time compiling.
- Set up the jak 2 kernel test, fixed a bug in the `catch-frame`.
=> Cleanup goalc tests, fix jak2 kernel bugs

CMakePresets.json
changes it back to what it was before. Saves the hassle of having duplicate scripts for Windows.
=> change out folder for Windows release w/ debug info

game/graphics/opengl_renderer/OpenGLRenderer.cpp, game/graphics/opengl_renderer/ShadowRenderer.cpp
Previously we used depth-fail (see https://en.wikipedia.org/wiki/Shadow_volume). I did not look closely enough at the original code and I got it wrong.  Depth-fail works if the camera is in the shadow volume, but has slightly different behavior on leaky meshes as depth-pass.  It turns out there are some cases (farmer, daxter on the rock in the intro cutscene) where the mesh has a hole, but it's oriented in a way where it only causes problems with depth-fail.  So this switches things to depth pass.
I did try to get the camera inside of the volume and it seems like the game properly disables the shadow when this happens.  It's easy to see this on the pelican when it's flying around.
=> [graphics] switch to depth-pass shadows

CMakeLists.txt
Gets rid of the annoying doxygen errors on every build invocation.
And fixes make install in some environments.
=> Exclude unnecessary third-party build targets

.github/workflows/linting.yaml, Taskfile.yml, common/util/unicode_util.h, decompiler/extractor/main.cpp, decompiler/main.cpp, game/main.cpp, lsp/handlers/lsp_router.cpp, lsp/main.cpp, lsp/protocol/hover.h, lsp/state/workspace.cpp, test/offline/offline_test_main.cpp, test/test_main.cpp, tools/dgo_packer.cpp, tools/dgo_unpacker.cpp, tools/level_tools/level_dump/main.cpp, tools/memory_dump_tool/main.cpp
Hopefully this resolves things, should probably test prior to merging on linux.  I confirmed utf-8 args are still getting into windows properly.
Closes #1688
=> utf8: fix locale mis-handling on linux

game/runtime.cpp, game/sce/iop.cpp, game/sce/iop.h, game/sce/sif_ee.cpp, game/system/IOP_Kernel.cpp, game/system/IOP_Kernel.h, game/system/iop_thread.cpp, game/system/iop_thread.h
This is an experiment on top of #1684 that implements more realistic scheduling of threads and a new strategy for throttling the IOP.
Given that the current solution is working well I'm not very certain if this is a good idea.
Threads are now scheduled like the kernel on the real IOP does them, the highest priority thread in ready state is always ran. For this to work we now also respect the argument to DelayThread and leave them in wait state until the specified time runs out.
This also requires changing the method by which we throttle the IOP kernel, wait_run_iop now uses information from the scheduler to wait until the kernel has a new thread ready to run.
=> Implement scheduling of IOP threads.

decompiler/config/all-types.gc, game/assets/jak1/text/game_text_en.gs, game/graphics/display.cpp, game/graphics/display.h, game/graphics/gfx.cpp, game/graphics/gfx.h, game/graphics/pipelines/opengl.cpp, game/graphics/pipelines/opengl.h, game/kernel/common/kmachine.cpp, game/kernel/common/kmachine.h, game/kernel/jak1/kmachine.cpp, goal_src/jak1/engine/ui/progress/progress-h.gc, goal_src/jak1/engine/ui/progress/progress-static.gc, goal_src/jak1/engine/ui/progress/progress.gc, goal_src/jak1/engine/ui/text-h.gc, goal_src/jak1/kernel-defs.gc, goal_src/jak1/pc/pckernel-h.gc, goal_src/jak1/pc/pckernel.gc, goal_src/jak1/pc/progress-pc.gc, third-party/imgui/imgui_impl_glfw.cpp
Worth mentioning that the selected location is referred to as 'monitor' in code but 'display' on the UI. Monitor is consistent with GLFW's terms, but display makes more sense to users. The options are also listed as just 'DISPLAY 1', 'DISPLAY 2', etc. I would have preferred to show the monitor's name but I wasn't sure how to get those strings into GOAL.
Let me know if I went a little overboard on the refactoring, I ran into some issues tracking the previous windowed pos/size when going from fullscreen to windowed, so I changed it quite a bit.  
Also, I had to modify the ImGui source, their GLFW implementation hijacks the monitor changed callback but never calls our registered callback (unlike the other events they steal). I have no idea why that code is even in ImGui's current release …
=> Add in-game option to switch fullscreen monitor

game/main.cpp
Some machines with dual-GPUs cannot properly detect OpenGOAL as a high-performance application and properly utilize the dedicated GPU. This sets a flag for both Radeon and NVIDIA GPUs to always use the high performance GPU when available. I do not have a dual-GPU machine to test this on, but this should just work out of the box, and doesn't seem to cause any issues for machines that aren't utilizing dual-GPUs.
=> Automatically switch to dedicated GPU in OpenGOAL runtime

.github/workflows/linux-build-clang.yaml, .github/workflows/linux-build-gcc.yaml, .github/workflows/windows-build-clang.yaml, .github/workflows/windows-build-msvc.yaml, test.sh, test/CMakeLists.txt, test/decompiler/FormRegressionTest.cpp, test/decompiler/FormRegressionTest.h, test/decompiler/test_DisasmVifDecompile.cpp, test/decompiler/test_FormBeforeExpressions.cpp, test/decompiler/test_FormExpressionBuild.cpp, test/decompiler/test_FormExpressionBuild2.cpp, test/decompiler/test_FormExpressionBuild3.cpp, test/decompiler/test_FormExpressionBuildLong.cpp, test/decompiler/test_gkernel_jak1_decomp.cpp, test/decompiler/test_math_decomp.cpp
Reports will showup in the wrong spot unfortunately due to an underlying github issue - https://github.com/dorny/test-reporter/issues/67
=> tests: Cleanup decompiler test fixtures and try to improve the test output / add a readable report

game/graphics/opengl_renderer/debug_gui.cpp
The imgui checkbox for v-sync hasn't been functional since the in-game vsync option was added.  The imgui checkbox gets overridden by the game so this is just a source of potential confusion now.  You have to change vsync via the game.
=> game/imgui: remove V-Sync checkbox as it can't be interacted with

.github/workflows/inform-pages-repo.yaml, .github/workflows/update-controller-db.yaml, goal_src/jak1/old/citb-drop-plat-OLD.gc, goal_src/jak1/old/fisher-OLD.gc, goal_src/jak1/old/lava/lava.gc, goal_src/jak1/old/racer-states-OLD.gc, goal_src/jak1/old/sage-finalboss-OLD.gc, goal_src/jak1/old/target-racer-OLD.gc, goal_src/jak1/old/target-racer-h-OLD.gc, goal_src/jak1/old/village-obs-OLD.gc, goal_src/jak2/kernel/dgo-h.gc, goal_src/jak2/kernel/gcommon.gc, goal_src/jak2/kernel/gkernel-h.gc, goal_src/jak2/kernel/gkernel.gc, goal_src/jak2/kernel/gstate.gc, goal_src/jak2/kernel/gstring-h.gc, goal_src/jak2/kernel/gstring.gc
I also missed adding the placeholder to the only files we've done in jak 2 ( the kernel ones )
=> goal_src: Get rid of `*OLD*` files in jak1's goal_src

decompiler/ObjectFile/ObjectFileDB.h, decompiler/ObjectFile/ObjectFileDB_IR2.cpp, decompiler/analysis/analyze_inspect_method.cpp, decompiler/analysis/analyze_inspect_method.h, decompiler/config/jak2/all-types.gc
This moves some types to the right files, and gives them parents/flag-asserts.
There weren't as many as I thought, which is nice.
=> [decompiler] handle types without inspects better in all-types

goal_src/jak1/pc/util/knuth-rand.gc
- I had a bug where I wasn't adding the min back
- `(sar (* bound (knuth-rand-next 31)) 31)` will always returns -1 or 0 when bound is a power of 2, should use `imul64` instead here
=> fix bug in knuth RNG

decompiler/config/all-types.gc, game/system/newpad.cpp, game/system/newpad.h, goal_src/jak1/engine/ps2/pad.gc
Seems stable for me - I was able to connect/disconnect the 4 controllers before/after the game started and they were always properly assigned to/cleared from cpads. 
You can test by reassigning controllers during the game with the below commands:
```
(set! (-> *target* control unknown-cpad-info00) (-> *cpad-list* cpads 0))
(set! (-> *target* control unknown-cpad-info00) (-> *cpad-list* cpads 1))
(set! (-> *target* control unknown-cpad-info00) (-> *cpad-list* cpads 2))
(set! (-> *target* control unknown-cpad-info00) (-> *cpad-list* cpads 3))
```
Spawning additional Jaks is not part of these changes, but we were able to use this to spawn 4 Jaks and have a unique controller for each:
https://www.youtube.com/watch?v=BeVl4x6gjC0
=> Support 4 controllers

custom_levels/test-zone/test-zone.jsonc, goalc/build_level/Entity.cpp
Adds support for `vector` and `float` in actor `res-lump` tags in custom level JSON files.
Also added some small documentation for currently available types to use in the `test-zone` JSON file.
=> custom levels: add support for more res types in actor lumps

.github/scripts/releases/extract_build_linux.sh
This is for a regression test for the extractor I'm adding in the jenkins server.  I'm only doing a minimal build over there (only offline-tests and extractor) so these steps fail since there is no gk/goalc executables.
This technically is only a partial regression test, as it doesn't cover windows.  But it increases confidence that we havn't broken something obvious.
=> tests: allow the binary prep steps in the linux release script to be skipped

Taskfile.yml, decompiler/config/all-types.gc, game/assets/jak1/text/game_text_en.gs, goal_src/jak1/engine/debug/default-menu.gc, goal_src/jak1/engine/game/game-save.gc, goal_src/jak1/engine/ui/progress/progress.gc, goal_src/jak1/engine/ui/text-h.gc, goal_src/jak1/pc/pckernel-h.gc, goal_src/jak1/pc/pckernel.gc, goal_src/jak1/pc/progress-pc.gc
- skips intro cutscene
- removes auto-save prompt
https://www.youtube.com/watch?v=kyLDUQR_UbY
closes #1670 
Other ideas that im not 100% sure on yet (so didn't implement):
- constant fish rng seed
- an even faster way to reset the current save file (couldn't easily figure this out, very coupled with the progress screen right now it seems)
- skipping the "good training boys..." cutscene as well
=> game: add a speedrunner mode which enables a faster new-game/resetting experience

common/util/FileUtil.cpp, common/util/FileUtil.h, game/graphics/display.cpp, game/graphics/display.h, game/graphics/gfx.h, game/graphics/pipelines/opengl.cpp, game/graphics/pipelines/opengl.h, game/kernel/common/kmemcard.cpp, game/kernel/jak1/kmachine.cpp, game/kernel/jak2/kmachine.cpp, goal_src/jak1/pc/pckernel.gc
- restore the windowed mode size properly from `pc-settings.gc`
- when switching to windowed mode from fullscreen, update the size properly
- don't auto-center the window on startup (this was due to a side-effect where it would always adopt the full-screen settings when the fullscreen update was forced)
- save and restore the windowed mode position
I've tested that this seems backwards compatible / doesn't effect full-screen modes but...should be somewhat tested before merging because this stuff has so many edge-cases historically.
=> game: windowed mode related fixes

Taskfile.yml, game/graphics/pipelines/opengl.cpp
There seems to be no reason to update the values here, they are updated by callbacks when moving the window.
There might be value in adding a check to reset to defaults if the monitor changes and it's off-screen, but that's a bit out of scope for this fix (original code only did this by accident).
When restoring to windowed mode, actually use the last position instead of the center of the monitor.
=> game: fix transition from fullscreen (not borderless) to windowed

.vs/launch.vs.json, common/type_system/Type.h, common/type_system/TypeSystem.cpp, common/type_system/TypeSystem.h, common/type_system/defenum.cpp, common/type_system/defenum.h, common/type_system/deftype.cpp, decompiler/IR2/Form.cpp, decompiler/IR2/Form.h, decompiler/analysis/final_output.cpp, decompiler/util/DecompilerTypeSystem.cpp, decompiler/util/DecompilerTypeSystem.h, goalc/compiler/compilation/Define.cpp, goalc/compiler/compilation/Macro.cpp, goalc/compiler/compilation/Type.cpp, lsp/state/workspace.cpp, test/test_type_system.cpp
This will hopefully help us with better documenting the code as we go.  You can now put docstrings in most relevant places in the `all-types` file and they will carry through to the decompiled output.
This also adds support on the compiler side to atleast safely parse the docstrings, they aren't used yet as there isn't much to use it for other than lsp integration / maybe better error messages / repl hints.  A later project!
Some examples:
```lisp
(deftype vec4s (uint128)
"hello world
type docstring for vec4s"
((x float :offset 0)
(y float :offset 32)
(z float :offset 64)
(w float :offset 96))
:method-count-assert 9
:size-assert         #x10
:flag-assert         #x900000010
)
```
```lisp
(define-extern identity "hello world identity" (function object object))
```
```lisp
(deftype …
```
=> decomp: add docstring support to relevant places in all-types

game/kernel/jak1/kmachine.cpp, game/kernel/jak1/kmachine.h, goal_src/jak1/pc/features/autosplit-h.gc, goal_src/jak1/pc/features/autosplit.gc
Searching the entire address range was just too slow, this keeps the struct in GOAL but puts a pointer to it inside the C++ side.  The ASL script can quickly scan these modules in memory and the potential range is much smaller.
This takes the average search from 1000-10000ms to 5-100ms.
=> jak1: put the auto-splitting marker in C++ so it can be quickly found

goalc/compiler/compilation/Static.cpp, test/goalc/source_templates/jak2/jak2-mega-test.gc, test/goalc/test_jak2_compiler.cpp
Will fix the symbol array issue mentioned here: https://github.com/open-goal/jak-project/pull/1802
We do already support symbol arrays, there was just a jak2-specific bug in the logic that special cases `#f` (which can be used without a quote, and in place of any structure, not just a symbol).
Also adds a test.
=> [goalc] Fix error when putting #f in an array of symbols

goal_src/jak1/levels/citadel/citadel-sages.gc
Still comes up from the bottom, but its probably the "correct" way to do it?
The other alternative would be killing Jak when the cutscene is skipped instead of `(start 'play (get-continue-by-name *game-info* "citadel-elevator"))`  To automatically force that reset and have the elevator at base height.
This would make the elevator at the top instantly, however it might mess with hp values and stored levels.
Credit to Barg/dallmeyer
Closes #1831
=> Make the citadel elevator come up when cutscene is skipped

decompiler/ObjectFile/ObjectFileDB_IR2.cpp, lsp/handlers/lsp_router.cpp, lsp/main.cpp, lsp/protocol/document_synchronization.cpp, lsp/state/workspace.cpp, lsp/transport/stdio.cpp, test/decompiler/reference/jak1/engine/anim/joint_REF.gc, test/decompiler/reference/jak1/engine/draw/drawable_REF.gc, test/decompiler/reference/jak1/engine/gfx/sky/sky_REF.gc, test/decompiler/reference/jak1/engine/util/glist_REF.gc, test/decompiler/reference/jak1/levels/rolling/rolling-obs_REF.gc, test/decompiler/reference/jak2/engine/anim/joint_REF.gc
I wasn't fully parsing the JSON LSP request so files weren't being updated -- seems to have fixed it.  Also cleaned up some logs / made `type analysis failed:...` warnings errors instead
=> lsp: re-analyze IR2 files when they change

goal_src/jak1/engine/game/main.gc, goal_src/jak1/pc/features/autosplit.gc, goal_src/jak1/pc/features/speedruns-h.gc
This shows the current settings needed to help provide information when verifying a run, also it removes the two calls to show the version in main.gc and instead does it within the speedrun/auto splitting scope.
- Shows Version
- Shows if Speedrunner mode is on (technically pointless since the text only displays when it is enabled this more just serves to show that there IS a speedrunner mode to viewers and stuff (josh) So hopefully it may cut down on submissions with the mode off)
- Shows if cutscene skips is enabled/disabled.
Tested on 16x9 4x3 the really weird one and borderless/fullscreen
[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/qDC-beEg5Es/0.jpg)](https://www.youtube.com/watch?v=qDC-beEg5Es)
=> [speedrun] Show speedrun information at start of run

common/type_system/defenum.cpp
This was causing an issue in the LSP because the `fmt::print`s clash with the transport over stdin/out
=> logs: prefer exceptions over stdout logs around `defenum`s

lsp/state/workspace.cpp
Found the reason why this wasn't happening -- the path included by the decompiler isn't a proper URL encoded URI -- so I have to convert it appropriately so when vscode sends it's "this file with this URI has changed" event it actually matches the tracked all-types file.
This will make jump-to-defs not drift as the file changes, and new uncommented symbols will actually get picked up
=> lsp: re-process `all-types` file when it changes

lsp/handlers/lsp_router.cpp, lsp/handlers/text_document/go_to.h, lsp/handlers/text_document/hover.h, lsp/main.cpp, lsp/state/workspace.cpp, lsp/state/workspace.h
Some new hover features:
docstrings (`@param/@return` syntax is not yet supported, nor is a syntax-highlighted preview, will do later)
better MIPs instruction descriptions
numeric hovers convert to different bases / tell you the OpenGOAL method id (i can't tell you the amount of times ive done -16 / 4 manually myself...)
Closes https://github.com/open-goal/opengoal-vscode/issues/33
Closes https://github.com/open-goal/opengoal-vscode/issues/31
Related to https://github.com/open-goal/opengoal-vscode/issues/29
=> lsp: improve LSP IR2 hovers

decompiler/util/data_decompile.cpp
Fixes a crash when there's a `(new 'static 'something :field <some anonymous function with a particular set of errors in the decompler>)`.  The output will now be
```
(set! *duck-mods* (new 'static 'surface
:name 'duck
...
:mult-hook <lambda at L615>
:flags (surface-flag duck)
)
```
fixes https://github.com/open-goal/jak-project/issues/1882
=> [decompiler] fix local_vars assert on static lambda

Taskfile.yml, test/offline/offline_test_main.cpp
A small quality of life increase that is more impactful since jak 2 has double the file count.
I often use the offline-tests to find compiler errors / automatically resolve them when i am finalizing a file.  As more and more files are completed this becomes increasingly more inefficient.  When I know that only 1 file needs to be decompiled / compared / compiled, I'd prefer to have a feature like this.
=> tests: allow for a single file to be tested in the offline-tests at a time

decompiler/config/jak2/all-types.gc, goal_src/jak2/levels/city/common/nav-graph-h.gc, test/CMakeLists.txt
Turns out the GCC test was running these MANUAL_TESTs which are essentially the same as running an `mi`
I'm kinda torn on whether or not these should go away, as it would have caught this mistake before merging, but it was decided a long time ago that they shouldn't be run (why they are marked MANUAL).
Either way, this fixes the current test failure in master
=> fix test failure and stop running manual tests in CI

.gitignore
For the level builder, I use .bak files whenever I modify a core file in the project. These let you undo changes, but they don't need to be pushed. I also couldn't find a nice way to do this, but we should also ignore all contents of custom_levels besides test-zone.
=> Ignore backups from OpenMaya

test/CMakeLists.txt
Not sure why this stopped working because i added extra args, might be due to the ninja warning about a duplicate target name
=> tests: run tests in gcc runner again

.vscode/opengoal.code-snippets, .vscode/settings.json, lsp/CMakeLists.txt, lsp/handlers/lsp_router.cpp, lsp/handlers/text_document/completion.h, lsp/protocol/completion.cpp, lsp/protocol/completion.h
Better documentation on what is supported / makes it faster to type them without making mistakes.
=> vscode: add snippets for supported `;; og:...` comments

decompiler/config/all-types.gc, decompiler/config/jak2/all-types.gc, decompiler/util/data_decompile.cpp, goal_src/jak2/engine/dma/dma-buffer.gc, goal_src/jak2/engine/gfx/ocean/ocean-h.gc, goal_src/jak2/engine/gfx/shrub/shrub-work.gc, goal_src/jak2/engine/gfx/sky/sky-data.gc, test/decompiler/reference/jak1/engine/dma/dma-buffer_REF.gc, test/decompiler/reference/jak1/engine/gfx/depth-cue_REF.gc, test/decompiler/reference/jak1/engine/gfx/eye_REF.gc, test/decompiler/reference/jak1/engine/gfx/font-h_REF.gc, test/decompiler/reference/jak1/engine/gfx/ocean/ocean-texture_REF.gc, test/decompiler/reference/jak1/engine/gfx/shrub/shrub-work_REF.gc, test/decompiler/reference/jak1/engine/gfx/sky/sky-tng_REF.gc, test/decompiler/reference/jak2/engine/dma/dma-buffer_REF.gc, test/decompiler/reference/jak2/engine/gfx/ocean/ocean-h_REF.gc, test/decompiler/reference/jak2/engine/gfx/shrub/shrub-work_REF.gc, test/decompiler/reference/jak2/engine/gfx/sky/sky-data_REF.gc, test/decompiler/reference/jak2/engine/util/profile_REF.gc
```
:gif0 (new 'static 'gif-tag64
:nloop #x4
:eop #x1
:pre #x1
:prim (new 'static 'gs-prim :prim (gs-prim-type tri-strip) :iip #x1 :tme #x1 :fge #x1 :abe #x1)
:nreg #x3
)
:gif1 (new 'static 'gif-tag-regs :regs0 (gif-reg-id st) :regs1 (gif-reg-id rgbaq) :regs2 (gif-reg-id xyzf2))
```
instead of
```
:gif (new 'static 'array uint64 2 #x303e400000008004 #x412)
```
=> [decompiler] nicer static giftags

decompiler/Disasm/Instruction.cpp, decompiler/Disasm/Instruction.h, decompiler/Disasm/InstructionDecode.cpp, decompiler/Function/Function.cpp, decompiler/IR2/AtomicOp.cpp, decompiler/IR2/AtomicOp.h, decompiler/IR2/FormExpressionAnalysis.cpp, decompiler/ObjectFile/LinkedObjectFile.cpp, decompiler/ObjectFile/LinkedObjectFile.h, decompiler/ObjectFile/LinkedObjectFileCreation.cpp, decompiler/ObjectFile/LinkedWord.h, decompiler/analysis/analyze_inspect_method.cpp, decompiler/analysis/atomic_op_builder.cpp, decompiler/analysis/cfg_builder.cpp, decompiler/config/jak2/all-types.gc, decompiler/types2/ForwardProp.cpp, decompiler/util/sparticle_decompile.cpp, goal_src/jak2/engine/ui/text-h.gc, goal_src/jak2/engine/ui/text.gc, test/decompiler/reference/jak2/engine/ui/text_REF.gc, test/offline/offline_test_main.cpp
- fix issue described in https://github.com/open-goal/jak-project/issues/1939
- fix `text`, which was manually patched with the wrong offset (was reading the symbol value off by one byte)
- clean up some random useless prints
- make the offline tests keep trying if there's a comparison error, clean up the output a bit so the diffs are all at the end.
=> [decompiler] handle pointer to symbol value, clean up prints on offline test

.github/workflows/linux-build-clang.yaml, .github/workflows/linux-build-gcc.yaml
buildcache's latest release changes to be built on Ubuntu22.04, which breaks our 20.04 runners
=> ci: rollback to previous buildcache version

README.md, Taskfile.yml
- Add pal and ntsc-j version descs so they appear in task --list
- Add example of using a non black label decomp command
- Add warning about (mi) not using paths, and a workaround renaming folders
This is a documentation workaround until https://github.com/open-goal/jak-project/issues/1993 is resolved
=> Adding notes for building non black label versions

test/offline/offline_test_main.cpp
Offline tests ignore comments in their comparison, but there's no reason to strip them from the file that goes into the reference test folder when doing the typical update routine.
This just generates superfluous diffs for all the files already done prior to this change and is meaningless (the lines are dropped anyway)
=> tests: don't strip comments from the dumped failures code

.github/workflows/linux-build-clang.yaml, .github/workflows/linux-build-gcc.yaml
My changes for allowing an explicit tag have now been merged to the original action, so no need to use my fork.
Additionally, buildcache itself reverted to using ubuntu 20.04 to fix this issue, but we'll leave the explicit tag there anyway to avoid sudden breakage in the future.
=> ci: update buildcache back now that things have stabilized

common/CMakeLists.txt, common/goos/Reader.cpp, common/util/FileUtil.cpp, common/util/FileUtil.h, common/util/StringUtil.cpp, common/util/StringUtil.h, goalc/compiler/Compiler.cpp, goalc/compiler/Compiler.h, goalc/compiler/Env.cpp, goalc/compiler/Env.h, goalc/compiler/Util.cpp, goalc/compiler/compilation/CompilerControl.cpp, goalc/main.cpp
This allows you to not have to define the entire file path to a source file to re-compile and load it.  Technically a stop-gap until editor tools are developed around writing OpenGOAL.
As opposed to `(ml "goal_src/jak2/engine/game/main.gc")` (which still works)
This is accomplished via the following config (connection attempts is irrelevant):
```json
{
"numConnectToTargetAttempts": 1,
"jak2": {
"asmFileSearchDirs": [
"goal_src/jak2"
]
}
}
```
This also provides a way to make game-specific configurations for the REPL fairly easily.
=> goalc/repl: Allow hot-loading files via `ml` with just the object name

goal_src/jak1/engine/debug/default-menu.gc
The macros used to create the menus in jak1 were not quoted.  I didn't change the `dm-lambda-float-var` one because it resulted in a compiler error / It seems unused anyway (i couldn't figure out how to show the anim tester menu)
=> jak1: fix debug menu regression around `lambda`s

decompiler/Disasm/Register.cpp, decompiler/config/jak2/all-types.gc, decompiler/util/data_decompile.cpp, game/mips2c/jak2_functions/lights.cpp, game/overlord/sbank.cpp, game/overlord/srpc.cpp, game/sound/989snd/sfxgrain.cpp, game/sound/989snd/sfxgrain.h, game/sound/989snd/sound_handler.h, game/sound/989snd/soundbank.h, goal_src/jak2/levels/underport/sig5-cent1-path0.gc, goal_src/jak2/levels/underport/sig5-cent2-path0.gc, test/decompiler/reference/jak2/levels/underport/sig5-cent1-path0_REF.gc, test/decompiler/reference/jak2/levels/underport/sig5-cent2-path0_REF.gc, test/offline/framework/execution.cpp, test/offline/framework/orchestration.cpp, test/offline/framework/orchestration.h
- Split up DGOs between threads in the multithreaded offline test
- fix some random warnings
- make the sig paths decompile a bit nicer to make some files smaller
=> [jak2] split up big dgos, some minor cleanup

game/overlord/srpc.cpp, game/sound/989snd/blocksound_handler.cpp, game/sound/989snd/blocksound_handler.h, game/sound/989snd/musicbank.cpp, game/sound/989snd/musicbank.h, game/sound/989snd/player.cpp, game/sound/989snd/sfxblock.cpp, game/sound/989snd/sfxblock.h, game/sound/989snd/sfxblock2.cpp, game/sound/989snd/sfxblock2.h, game/sound/989snd/sfxgrain.cpp, game/sound/989snd/soundbank.h
CreateChildSound did not check for nullptr return from soundbank::make_handler, which would happen for sounds with no grains.
Prevent further problems with this by switching to optional instead of passing nullptr.
=> Prevent putting nullptr into child sound list

custom_levels/test-zone/test-zone.jsonc, goalc/build_level/build_level.cpp
It used to automatically assign actor IDs, but reset in between custom levels, so it was possible for actors to share the same actor id with a actor in another level. With this the user can now specify a base_id to make sure that the custom levels never match! (or fix it if they do!)
=> Add base_id for custom levels.

decompiler/level_extractor/extract_tie.cpp, goal_src/jak2/levels/common/enemy/fodder/fodder.gc
I accidentally left some logs in, the extract_tie one was a bad one to leave as it makes the decompiler run significantly slower
=> lint: remove some debugging logs

common/util/StringUtil.cpp, common/util/StringUtil.h, decompiler/config/jak2/anonymous_function_types.jsonc, decompiler/config/jak2/type_casts.jsonc, game/CMakeLists.txt, game/graphics/display.h, game/graphics/gfx.cpp, game/graphics/gfx.h, game/graphics/opengl_renderer/OpenGLRenderer.cpp, game/graphics/opengl_renderer/OpenGLRenderer.h, game/graphics/opengl_renderer/debug_gui.cpp, game/graphics/opengl_renderer/debug_gui.h, game/graphics/pipelines/opengl.cpp, game/kernel/common/kmachine.cpp, game/kernel/common/kmachine.h, game/kernel/jak2/kmachine.cpp, game/tools/filter_menu/filter_menu.cpp, game/tools/filter_menu/filter_menu.h, goal_src/jak2/engine/debug/debug.gc, goal_src/jak2/kernel-defs.gc
This adds a new ImGUI menu to help filter out the clutter on screen.
https://user-images.githubusercontent.com/13153231/210192912-b1c28319-bacb-449c-ad7f-e7308fb75f50.mp4
This also:
- moves the imgui display bool into a game specific config file (you can hide it in jak1, and not in jak2)
- the config file also persists the settings from this menu (except the filters for now, future TODO)
- there is a new `ignore_imgui_hide_keybind` in this file to ignore hiding it when you press Alt
=> game/debugging: Add a new imgui menu to filter debug text and adjust imgui config settings

game/graphics/opengl_renderer/DirectRenderer.cpp, game/mips2c/jak2_functions/font.cpp, game/mips2c/mips2c_private.h, goal_src/jak2/engine/gfx/sprite/particles/sparticle.gc, goal_src/jak2/engine/level/level.gc
Fixes:
- a very old bug in depth in DirectRenderer, probably from the original tfrag stuff. Looked at PCSX2 source code to see how 32/24 bit depths are handled. This fixes hud sprites being drawn behind level geometry.
- saturate `vftoi4` like the ps2 does when the float is too large, fixing hidden text in `hud`. For now it's only using this in the font code because this saturation is actually kinda slow and hasn't been a problem in other places.
- fix crazy particle spawning issue with blue gun and dripping stuff. This would happen if particles kill themselves while being processed (through a callback)
=> [jak2] fix hud and some particles

game/common/str_rpc_types.h, game/overlord/stream.cpp
Untested lazy copy-paste job from jak1
Pretty confident it's the same logic with a new StrFileHeader struct.
=> Overlord: Jak2 stream loading

game/discord.cpp, game/discord.h, game/kernel/jak1/kmachine.h, game/kernel/jak2/kmachine.cpp, game/kernel/jak2/kmachine.h, game/main.cpp, game/runtime.cpp, goal_src/jak2/dgos/engine.gd, goal_src/jak2/dgos/game.gd, goal_src/jak2/engine/debug/default-menu.gc, goal_src/jak2/engine/game/main.gc, goal_src/jak2/engine/load/file-io.gc, goal_src/jak2/game.gp, goal_src/jak2/kernel-defs.gc, goal_src/jak2/kernel/gstring.gc, goal_src/jak2/pc/pckernel-h.gc, goal_src/jak2/pc/pckernel.gc
Notable things:
- This assert is hit when trying to save the pc-settings file, NYI https://github.com/open-goal/jak-project/blob/e630b506903d7f7028dff89702be7f586c2120e7/game/kernel/common/Symbol4.h#L14 so right now settings aren't persisted.  But RPC defaults to on
- The existing functions can probably be made generic based off the game version, but I didn't spend time refactoring them yet as they aren't really ready to be used in jak 2 yet (we have no screenshots for the levels for example)
=> g/jak2: initial Discord RPC implementation

goal_src/jak1/engine/debug/default-menu.gc
This one was forgotten when the other similar menu entries were fixed. So I fixed this now.
=> Fix 'Load... border-mode' in default-menu

goal_src/jak2/engine/level/level.gc, goal_src/jak2/levels/mars_tomb/tomb-obs.gc
- Fix airlock crash
- Hack to fix wrong nickname for `tombc`
=> jak2: tomb fixes

.github/workflows/linting.yaml, .vscode/opengoal.code-snippets, goal_src/jak2/levels/common/airlock.gc, scripts/gsrc/check-for-conflicts.py, scripts/gsrc/update-from-decomp.py
It's easy to forget that a file has manual changes when updating things programmatically.  Now you can annotate said files with `;; og:update-with-merge` and it will use `git merge-file` instead of doing a naive copy-paste.
This will force you to explicitly handle any differences via typical conflict resolution.  And if you forget to do so, CI will detect and reject your PR.
=> scripts: update gsrc files with modifications using git merge

custom_levels/test-zone/test-zone.jsonc, goalc/CMakeLists.txt, goalc/build_level/Entity.cpp, goalc/build_level/Entity.h, goalc/build_level/LevelFile.cpp, goalc/build_level/LevelFile.h, goalc/build_level/build_level.cpp, goalc/build_level/drawable_ambient.cpp, goalc/build_level/drawable_ambient.h
Allows mappers to place ambient hints in their custom levels.
The syntax is as follows in the custom level JSON:
```jsonc
"ambients": [
{
"trans": [-27.34, 92.7, 22.24, 10.0],
"bsphere": [-27.34, 92.7, 22.24, 10.0], // required for the game to know when you are in range of the ambient
"lump": {
"name": "crystalc-ambient-1", // ambient name
"type": "'hint",              // ambient type
"text-id": ["int32", 4297],   // game-text-id to display (if this is >4095, it will display multiple times)
"play-mode": "'notice"        // not sure if this needed/used with level hints
}
}
]
```
This has only been tested with ambient hints so far.
One thing that could probably be improved is the way the ambients are added to the `bsp-header`'s `drawable-tree` (in `LevelFile.cpp`), I haven't been able to …
=> custom levels: add initial support for ambients

goal_src/jak1/pc/features/speedruns.gc
Forgot to mark the "Rock Village" HUD text as seen for this IL speedrun. Doesn't actually affect the run as far as I'm aware, this is more just for consistency with the other ILs.
=> Minor fix for Rock Village IL speedrun

.github/workflows/update-controller-db.yaml
Noticed this has been failing for a while for reasons.  I think I fixed them but can't re-run the current job (out of date from master).  This this gives me a way to manually re-run it.
=> ci: allow manually updating the controller db

.github/workflows/update-controller-db.yaml
The direct commit option doesn't work as there is no way to bypass required status checks -- this makes the merge queue less useful.  Switch to a PR instead.
=> ci: switch to a pull request instead of a direct commit for updating controller db

game/graphics/opengl_renderer/OpenGLRenderer.cpp, game/graphics/opengl_renderer/OpenGLRenderer.h, game/graphics/opengl_renderer/debug_gui.cpp, game/graphics/opengl_renderer/debug_gui.h, game/graphics/opengl_renderer/loader/Loader.cpp, game/graphics/opengl_renderer/loader/Loader.h, game/graphics/pipelines/opengl.cpp
Add a debug window for the loader to show levels and fix an issue with jak 2 level unloading. I never really thought about how this works for > 2 levels, and there is a chance that you could unload the wrong level in some cases.
The problem is some combination of merc-only levels not counting toward the "in use" detection, and the unloader ignoring what the game wants to load.
I don't remember why using merc models doesn't contribute to "in use" but I'm afraid to change this for jak 1. Instead, we can have the unloader avoid unloading levels that the game is telling us are loaded. This is what we should have done originally, but there was a time when Jak 1 didn't tell the loader anything, and we had this stupid detection thing.
I think this is the first step toward just getting rid of the …
=> [jak2] improve loader for jak 2 levels

goal_src/jak1/engine/camera/cam-layout.gc
Just noticed this while looking into #2225 , this line is repeated a few lines later
https://github.com/open-goal/jak-project/blob/b9cd17b20a29a4674d8515e53bf937a92f331b6c/goal_src/jak1/engine/camera/cam-layout.gc#L8-L13
=> Redundant `(declare-file (debug))`

goal_src/jak2/levels/city/common/civilian.gc
Fixes a rare crash that can sometimes happen when civilians are picking a direction to flee in, where a branch count may be 0, causing a divide by 0 MATH_EXCEPTION.
=> [jak2] fix rare civilian flee crash

goalc/main.cpp
Stops the REPL crashing with `device or resource busy` when running `(reload)`
However I think this is indicative of a bigger problem where either the `Compiler` or prompt is not ready to handle input immediately after creation and setting the status to `OK`.
=> repl: prevent REPL crash when running `(reload)`

common/type_system/TypeSystem.cpp, decompiler/util/data_decompile.cpp, game/graphics/opengl_renderer/foreground/Merc2.cpp, game/kernel/jak2/kmachine.cpp, goal_src/jak2/engine/level/level.gc, goalc/compiler/Val.cpp, goalc/compiler/compilation/CompilerControl.cpp
Increase level heaps and borrow heaps. The level heap increase was likely not needed, but better safe than sorry. We allocate the 128 MB main heap anyway so there's no harm.
Also fix the crash when using `-boot`. As I thought it was just a one-line typo in the kernel.
=> [jak 2] fix boot, increase level heap sizes

decompiler/config/jak2/all-types.gc, decompiler/config/jak2/label_types.jsonc, goal_src/jak2/levels/city/common/traffic-engine.gc, test/decompiler/reference/jak2/levels/city/common/traffic-engine_REF.gc
`*alert-level-settings*` was actually an inline array and we were indexing past the end of it. 
I think this will fix some of the strange on-foot guard behavior too.
=> [jak2] fix highly aggressive guard zoomer ambush

common/cross_os_debug/xdbg.cpp, decompiler/config/jak2/all-types.gc, game/kernel/jak2/kboot.cpp, game/sce/libscf.cpp, goal_src/jak1/pc/debug/pc-debug-common.gc, goal_src/jak1/pc/pckernel-h.gc, goal_src/jak1/pc/pckernel-impl.gc, goal_src/jak2/engine/debug/menu.gc, goal_src/jak2/pc/debug/pc-debug-methods.gc, test/decompiler/reference/jak2/engine/debug/menu_REF.gc
Where applicable, of course.
My system language is set to English so I actually can't test this. If anyone has their Windows language (NOT LOCALE) set to Spanish, German, French, Italian or Japanese please test this.
Fixes #1734 
Also fixes the opengoal debugger on Windows and fixes the decomp for `menu` which was causing some crashes related to input handling.
=> [windows] make the games start up in the user's preferred system UI language

game/kernel/jak2/klisten.cpp, game/kernel/jak2/kprint.cpp, game/overlord/fake_iso.cpp, goal_src/jak1/pc/debug/entity-debug.gc
`inspect` also prints with the correct indent now as a result.
=> [jak2] fix crash with `*print-column*` loading the wrong memory

goal_src/jak2/levels/underport/underb-master.gc
Fix crash when the game tries to spawn `jellyfish` in Underport and temporarily disable the rendering of the warp effect until it's properly implemented.
=> jak2: fix `jellyfish` crash and temporarily disable underwater warp

goalc/compiler/compilation/Debug.cpp, goalc/debugger/Debugger.cpp, goalc/debugger/Debugger.h, test/goalc/test_debugger.cpp
Some backtraces are quite large, an option is to increase your terminal buffer -- but dumping to a file is also useful if you want to share the crash.
I'm not crazy about the way I hacked this in, but it felt like the least invasive way for now and I don't want to cause a regression with the debugger.  It's also nice that it dumps with ansi colors as then you can view the backtrace with the original coloring:
Usage:
```clj
(:di "./stacktrace.log")
```
=> dbgr: allow dumping the backtrace to a file

.gitignore, decompiler_out/.gitignore, goalc/main.cpp, log/.gitignore
This gets rid of the `auto-lt` and `auto-dbg` CLI args to `goalc` that have been marked deprecated for a month or so at this point.  The behaviour can be replicated via the `startup.gc` file.
I also removed `decompiler_out/` and `log/` from the repo, as our C++ code is smart enough to create these directories if they are missing now so they are superfluous
=> goalc: remove deprecated CLI args from goalc and remove empty repo folders

common/custom_data/TFrag3Data.cpp, common/custom_data/Tfrag3Data.h, decompiler/level_extractor/MercData.cpp, decompiler/level_extractor/MercData.h, decompiler/level_extractor/extract_merc.cpp, game/graphics/opengl_renderer/EyeRenderer.cpp, game/graphics/opengl_renderer/EyeRenderer.h, game/graphics/opengl_renderer/OpenGLRenderer.cpp, game/graphics/opengl_renderer/OpenGLRenderer.h, game/graphics/opengl_renderer/foreground/Merc2.cpp, game/kernel/jak2/kscheme.cpp, goal_src/jak1/engine/gfx/foreground/bones.gc, goal_src/jak2/engine/draw/drawable.gc, goal_src/jak2/engine/gfx/foreground/eye-h.gc, goal_src/jak2/engine/gfx/sky/sky-tng.gc, goal_src/jak2/engine/gfx/texture/texture.gc
Support rendering eyes with merc for both jak 1 and jak 2.
For jak 1, everything should look the same, but merc will be used to draw eyes. This means that jak is now fully drawn with merc!
For jak 2, eyes should draw, but there are still a few issues:
- the tbp/clut ptr trick is used a lot for these eye textures, so there's a lot that use the wrong texture
- I had to enable a bunch more "texture uploads" (basically emulating the ps2 texture system) in order to get the eyes to upload. It would be much better if the eye renderer could somehow grab the texture from the merc model info, skipping the vram addressing stuff entirely. I plan to return to this.
- I disabled some sky draws in `sky-tng`. After turning on pris2 uploads, the sky flashed in a really annoying way.
=> [merc] support eyes through merc

goal_src/jak2/engine/gfx/merc/merc-blend-shape.gc
Fix so the profile bar doesn't do something silly when `merc-blend-shape` returns early, skipping the part where `end-time` is set.
=> [jak2] fix blerc profile bar issue

goal_src/jak1/engine/game/game-save.gc, goal_src/jak1/engine/game/main.gc
Fixes unnecessary performance degradation when auto-save is enabled.
=> [jak1] disable `auto-save-check`

.github/workflows/release-pipeline.yaml
The launcher and the main repo are now loosely coupled, there is no reason to emit a consumption event when we cut a release anymore.
=> ci: stop emitting event to the launcher repo

common/custom_data/Tfrag3Data.h, decompiler/level_extractor/BspHeader.cpp, decompiler/level_extractor/BspHeader.h, decompiler/level_extractor/extract_level.cpp, decompiler/level_extractor/extract_tfrag.cpp, decompiler/level_extractor/extract_tfrag.h
Support the weird `tfrag-gs-test` and `texture-page-flag` stuff added in jak 2. Solves some issues with partially invisible tfrags.
=> [jak2] fix atest flag in tfrag

game/kernel/jak2/kprint.cpp, goal_src/jak2/engine/gfx/hw/display.gc
The actor heap size was increased but not the DMA buffer because I forgot.
=> [jak2] increase size of DMA buffers + potentially fix print buffer bug

scripts/gsrc/skeleton_creation/check_for_identical_objs.py
left some warning messages / notes for when it's used again and can be checked more closely.  Making the change now so I don't forget.
=> scripts: fix edge-case in gsrc skeleton creation script

game/graphics/opengl_renderer/sprite/Sprite3.cpp, game/graphics/opengl_renderer/sprite/Sprite3.h, game/graphics/opengl_renderer/sprite/Sprite3_Glow.cpp
Fixes an issue where glow sprites are drawn twice, sometimes causing the weird black outlines
=> [jak2] update sprite to check matrix == -1

common/custom_data/Tfrag3Data.h, decompiler/level_extractor/MercData.cpp, decompiler/level_extractor/MercData.h, decompiler/level_extractor/extract_merc.cpp, decompiler/level_extractor/extract_tie.cpp, game/graphics/opengl_renderer/foreground/Merc2.cpp, game/graphics/opengl_renderer/foreground/Merc2.h, goal_src/jak1/engine/gfx/foreground/bones.gc, goal_src/jak2/engine/gfx/foreground/foreground.gc, goal_src/jak2/engine/level/level.gc, goal_src/jak2/kernel/gkernel.gc
- better handling of the `disable-fog` settings for merc, should fix the spotlights. There's a setting in the merc effect, and also a runtime flag for the draw-control. I'm not actually sure what reads these, but the draw-control one is definitely used to disable fog on the spotlights.
- increase merc draw limit to try to fix the issue about partially drawn citizens in the city
- remove useless debug prints (it's okay to die in init, and the medium load buffer size mode is understood now)
=> [jak2] a few small graphics fixes

.gitignore, game/graphics/pipelines/opengl.cpp
This way a user can take multiple data samples from one/multiple play sessions quickly. Creates a directory called profile_data that is added to gitignore to place the data in, and checks to see if a file is there and if so it creates prof1.json prof2.json prof3.json and so on...
=> Dont overwrite profile data

lsp/handlers/lsp_router.cpp, lsp/main.cpp
Something changed to cause this to crash, specifically the error was around using the `nlohmann::json`, `method` variable as a string to find the route handler (expected string, got int).
This worked fine before, but no longer -- maybe a dependency update this month?
You will have to use the `opengoal.opengoalLspPath` setting to use a locally built lsp executable with this fix.
=> lsp: fix route handling json error

goal_src/jak2/levels/atoll/sig0-course.gc, goal_src/jak2/levels/castle/boss/castle-baron.gc, goal_src/jak2/levels/dig/dig-obs.gc
Add some hacks to make the Sig escort, Dig 2 and Krew boss missions completable without streamed audio for now.
=> jak2: add some temporary `gui-control` hacks to make missions completable

README.md, common/repl/config.cpp, common/repl/config.h, goal_src/jak1/game.gp, goal_src/jak2/game.gp, goal_src/user/README.md, goalc/compiler/Compiler.cpp, goalc/compiler/Compiler.h, goalc/main.cpp, goalc/make/MakeSystem.cpp, goalc/make/MakeSystem.h, goalc/simple_main.cpp
Adds a decent way to customize the folders the project file expects the iso data and decompiler data to be in.  When you run any version other than the default, for example Jak 1 PAL, it uses the `gameName` decompiler config to consume and output it's results.
However the project file will assume `jak1` unless you hard-code it differently -- basically, it needs to be explicitly told just the decompiler is told what version to use.
We now have a per-user REPL Config json file, so that can be used to override the default `jak1` behaviour.
Fixes #1993
=> repl: add `gameVersionFolder` to repl-config for running the non-default version

common/util/FileUtil.cpp
Fixes #1771
Probably want to do some testing with the launcher to ensure no breaking changes
before/after:
=> cli: ensure an overridden project path is absolute

goal_src/jak2/engine/nav/nav-enemy.gc
This bug feels very similar to punch glitch, where code worked on PS2 only because some value didn't reach exactly 1.0 or 0.0 with ps2-style floating rounding. It might be better to track down the source of the "only 1.0 on PC" value, rather than patching downstream code to handle it, but I can't easily find it in this case - there's a lot of code that touches this heading value. (it's also possible this bug happens on ps2, but the result is the guard appears to face the wrong direction, rather than disappearing).
Detailed debug notes:
Ran a process that just calls this function:
```
(defun print-guard-info ()
(let ((proc (process-by-name "crimson-guard-level-42" *active-pool*)))
(when proc
(format *stdcon* "PROC: ~A~%" (-> proc state))
(let* ((pd (the process-drawable proc))
(css (-> pd …
```
=> [jak2] fix disappearing guard

goal_src/jak2/engine/collide/collide-shape-h.gc, goal_src/jak2/engine/nav/nav-enemy.gc, goal_src/jak2/levels/city/common/citizen.gc, goal_src/jak2/levels/stadium/stadium-obs.gc
Fixes citizens that disappear (permanently) when being pushed into a "wall" which is the border of a nav mesh that is exactly aligned with coordinate axes.
=> [jak2] more nav-related nan fixes

common/custom_data/Tfrag3Data.h, decompiler/level_extractor/extract_level.cpp, decompiler/level_extractor/extract_shrub.cpp, decompiler/level_extractor/extract_shrub.h, decompiler/level_extractor/extract_tfrag.cpp, game/graphics/opengl_renderer/SkyRenderer.cpp, game/graphics/opengl_renderer/SkyRenderer.h, game/graphics/opengl_renderer/background/Shrub.cpp, game/graphics/opengl_renderer/background/Shrub.h, game/graphics/opengl_renderer/background/TFragment.cpp, game/graphics/opengl_renderer/background/TFragment.h, game/graphics/opengl_renderer/background/Tfrag3.cpp, game/graphics/opengl_renderer/background/Tfrag3.h, game/graphics/opengl_renderer/background/background_common.cpp, game/graphics/opengl_renderer/shaders/shrub.vert, game/graphics/opengl_renderer/shaders/tfrag3.vert
Fixes decal on tfrag:
Sets up jak 2 alpha shrub test settings. They are still too dark, but there's no longer incorrect alpha test:
Fix decal on shrub, a feature used in exactly one place in jak 1:
Fixed issue with u16 overflow in castle on the alpha channel, causing flickering. It barely overflowed, which made me suspicious that we had some error somewhere. But I think that there code is robust against overflows.
=> [jak2] misc fixes to renderers

decompiler/config/jak2/all-types.gc, goal_src/jak2/levels/dig/dig-obs.gc, test/decompiler/reference/jak2/levels/dig/dig-obs_REF.gc
Fixes #2518
They were spawning in, but immediately falling forever
=> d/jak2: fix `dig-sinking-plat`s in dig3

decompiler/config/jak2/all-types.gc, decompiler/config/jak2/ntsc_v1/hacks.jsonc, decompiler/config/jak2/ntsc_v1/type_casts.jsonc, test/decompiler/reference/jak2/levels/hiphog/whack_REF.gc, test/offline/config/jak2/config.jsonc
Fixes #2520 
Just was missing the particle birth func for the score counter, took essentially a guess at the arbitrary data on it -- it works!
=> d/jak2: decompile missing function in `whack`

goal_src/jak2/engine/draw/drawable.gc, goal_src/jak2/engine/gfx/hw/display.gc, goal_src/jak2/levels/common/airlock.gc, goal_src/jak2/pc/pckernel-impl.gc, goal_src/jak2/pc/pckernel.gc
Fixes crash at the end of various missions.
Fixes #2456
=> Do not swap between clocks for airlocks speed

goal_src/jak2/engine/game/task/game-task.gc
Fixes crash when completing city side missions with `city-krew-collection-introduction` open.
Fixes #2539
=> Fix bad `lsack` level borrow

common/serialization/subtitles/subtitles_ser.cpp, common/serialization/subtitles/subtitles_ser.h, game/assets/jak1/subtitle/subtitle-groups.json, game/tools/subtitles/subtitle_editor.cpp, game/tools/subtitles/subtitle_editor.h
Allows for removing a line in the subtitle editor finally, also fixed the following:
- The path the editor used didn't include the game name
- Loading the subtitle project is too slow to do on startup now (4-5seconds in a debug build), do it on demand now
=> subtitles-editor: Allow removing lines and fix some issues

common/goos/Object.cpp, common/goos/Object.h, goalc/compiler/Compiler.h, goalc/compiler/compilation/Math.cpp
Slight change to float divide operations (again). Now it only turns into inverse multiplication if the float is a power of 2 (positive or negative). Non-zero immediate divisors will be compiled as regular float divisions but will forgo the extra branches and checks for divide by zero.
Also fixes #2584
=> less branches for division + fix divide by zeros

goal_src/jak1/kernel/gkernel.gc, goal_src/jak2/kernel/gkernel-h.gc, goal_src/jak2/kernel/gkernel.gc
Somehow this was only causing issues (afaik) with `draw-decoration-load-save` getting corrupted, perhaps because other processes either use the shared dram stack or the gigantic spr stack.
=> [jak2] Fix temp stacks being created outside process stack

goal_src/jak2/levels/temple/mountain-obs.gc
No longer needed after the latest changes in the overlord PR that recently merged.
Fixes #2509
=> g/j2: remove temporary hack to allow the avalanche to play

goal_src/goal-lib.gc, goalc/compiler/Val.h, goalc/compiler/compilation/Function.cpp, goalc/compiler/compilation/Type.cpp, test/goalc/source_templates/control-statements/lambda-1.static.gc
This fixes a long time issue with `lambda`. The `lambda` is a bit overloaded in OpenGOAL: it's used in the implementation of `let`, and also to define local anonymous functions. 
```
(defmacro let (bindings &rest body)
`((lambda :inline #t ,(apply first bindings) ,@body)
,@(apply second bindings)))
```
```
(defmacro defun (name bindings &rest body)
(let ((docstring ""))
(when (and (> (length body) 1) (string? (first body)))
(set! docstring (first body))
(set! body (cdr body)))
`(define ,name ,docstring (lambda :name ,name ,bindings ,@body))))
```
In the first case of a `let`, a `return` from inside the `let` should return from the functioning containing the `let`, not the scope of the `lambda`. In the second case, we should return from the lambda.  The way we told the different between …
=> [goalc] default to non-immediate lambdas if not requested

game/main.cpp
I'm not sure what has changed here...but rebooting in debug mode now hangs.
- It seems to exit the GFX loop prematurely because `MasterExit` is still set to `RESTART_IN_DEBUG` https://github.com/open-goal/jak-project/blob/master/game/runtime.cpp#L431
- And then it gets stuck waiting for the DECI thread to close
This works, but im not sure if it's the right fix / what has changed to require this.
=> game: don't exit prematurely when rebooting in debug

common/custom_data/TFrag3Data.cpp, common/custom_data/Tfrag3Data.h, game/graphics/opengl_renderer/background/Tfrag3.cpp, game/graphics/opengl_renderer/background/Tie3.cpp, game/overlord/jak2/stream.cpp, game/overlord/jak2/vag.cpp
Saves 16 bits and lets us align the `color_index` field properly.
This shouldn't improve or decrease performance by any noticeable amount except maybe in really low end systems.
=> pack tfrag normals into 10 bits

goal_src/jak1/engine/common-obs/process-taskable.gc
In #2457, this use of `less-than-hack` was accidentally removed, reintroducing the "Press O to talk" NaN bug.
=> jak1: fix regression with npc NaNs

goal_src/jak1/engine/ui/text-h.gc, goal_src/jak1/engine/ui/text.gc, goal_src/jak1/pc/debug/default-menu-pc.gc, goal_src/jak1/pc/pckernel-impl.gc
This is being done to unblock adding partial translations to the game.  In the code's current state, we cannot add partial translations because it makes the UX basically unusable, with everything being labelled as Unknown.  At the same time, it isn't really a good workflow to require 100% completion, and we should be providing a path that allows for continuous iteration.
So this change is rather simple, load the english (language 0) text file as a fallback.  If we cannot find something in a `lookup-text!` call, try to look it up in english as well.
Tests:
> current behaviour
> successfully fell-back
> couldn't fallback, still displays Unknown
=> i18n: Lookup untranslated strings from a fallback language (english) instead of displaying `Unknown...`

game/graphics/opengl_renderer/OpenGLRenderer.cpp, game/graphics/opengl_renderer/ShadowRenderer.cpp, game/graphics/opengl_renderer/ShadowRenderer.h, game/graphics/opengl_renderer/foreground/Shadow2.cpp, game/graphics/opengl_renderer/foreground/Shadow2.h, game/graphics/opengl_renderer/shaders/shadow.frag
Fixes Jak 1 shadow color. Old behavior is subtractive blend with a hardcoded value, which often times look way too dark, but it looks like the actual game uses some sort of multiplicative blend and a customizable shadow color (for all shadows at once).
Before vs after:
Also fixes #2646
=> fix shadow colors in jak 1 and jak 2 shadow crash

goal_src/jak1/engine/common-obs/collectables-part.gc
Was accidentally removed in the particle refactor.
=> jak1: add back money starburst

game/overlord/jak2/iso.cpp, game/overlord/jak2/iso.h, game/overlord/jak2/iso_queue.cpp, game/overlord/jak2/spustreams.cpp, game/overlord/jak2/vag.cpp, game/sce/iop.h
Started cleaning up some of the lower hanging fruit.
=> overlord: Some cleanup

third-party/tree-sitter/CMakeLists.txt
This Commit is used to avoid some errors in the build process using Ubuntu that I stumbled upon : 
Discussed in Discord (https://discord.com/channels/756287461377703987/1110990884876603523)
When I tried in a proper docker container using Ubuntu image 20.04, I hit this error : 
```
/build/source/third-party/tree-sitter/tree-sitter/lib/src/././unicode/utf8.h:37:10: fatal error: unicode/umachine.h: No such file or directory
37 | #include "unicode/umachine.h"
```
In detail : 
```
xxx@DESKTOP-324T1BE:~/jak-project$ cmake -B build && cmake --build build -j 12
-- Statically Link? OFF
-- GCC detected - Setting Defaults
-- Using c++ standard c++17
-- CMake version: 3.16.3
-- Project version: 3.2.0
-- Using Stack Protection hardening
-- CMAKE_CXX_COMPILER '/usr/bin/c++' 'GNU' '9.4.0'
-- …
```
=> fix: add unicode tree-sitter include directory

game/runtime.cpp
This caused the IOP thread to use a full core always, just spinning on this. I didn't mean to leave this in.
=> [IOP] revert change that ran the iop way too much

.github/workflows/linux-build-clang.yaml, .github/workflows/linux-build-gcc.yaml, .github/workflows/windows-build-clang.yaml, .github/workflows/windows-build-msvc.yaml
we had a GCC build timeout on master, try to make this less flaky
=> ci: bump timeouts on builds, mostly for cache misses

docs/progress-notes/jak2/shadow-vu1.txt, game/mips2c/jak2_functions/collide_hash.cpp, game/mips2c/mips2c_private.h
Should fix https://github.com/open-goal/jak-project/issues/2679
Here's a test program that will trigger the bug when near these guards:
```lisp
(define *cquery* (new 'global 'collide-query))
(defun test-bad-collide ()
(let ((lower (new 'static 'vector  :x 1681893.8750  :y 61314.2031 :z 345208.6562 :w 1.))
(upper (new 'static 'vector :x 1701603.8750 :y  67624.0625 :z 357881.0312 :w 1.))
;(cquery (new 'stack-no-clear 'collide-query))
)
(set! (-> *cquery* collide-with) (the-as collide-spec 1))
(set! (-> *cquery* ignore-process0) #f)
(set! (-> *cquery* ignore-process1) #f)
(set! (-> *cquery* ignore-pat) (new 'static 'pat-surface :noentity #x1 :nojak #x1 :probe #x1 :noendlessfall #x1))
(set! (-> *cquery* action-mask) (collide-action solid))
(set! (-> *cquery* bbox min quad) (-> lower quad)) …
```
=> [jak2] float patch for bogus collide frags

README.md
SDL requires this dependency on Fedora in order to be configured with OpenGL support.
=> readme: add `mesa-libGL-devel` dependency for fedora users

.github/workflows/build-matrix.yaml, .github/workflows/linting.yaml
We are limited on concurrent builds, when people push branches directly to upstream, we are running duplicate builds for every commit on a PR for no reason.
This should stop that
=> ci: don't run CI builds on non `master` branch pushes

game/system/hid/display_manager.cpp
Fixes https://github.com/open-goal/jak-project/issues/2699
Setting a Windows specific SDL hint that disables OS forced scaling. With Windows handling scaling we are locked into a progressively smaller resolution buffer the higher the Windows display scaling option is set. Not sure if this is the best place to put it.
The game itself handles scaling already but ImGUI does not which can lead to it getting quite small on high DPI devices with high scaling. OS scaling can still be forced on the gk.exe as shown bellow to revert this behaviour if a blurry but larger ImGUI is preferable:
=> SDL: Hint to Windows that we handle DPI scaling

.github/scripts/releases/extract_build_linux.sh, .github/scripts/releases/extract_build_windows.sh, third-party/cmake/modules/SDLOptions.cmake
Also removed the empty `assets` folder that is in every release.
=> cmake: properly statically link SDL when applicable

game/graphics/pipelines/opengl.cpp, game/kernel/common/kmachine.cpp, game/sce/libpad.cpp, game/system/hid/devices/game_controller.cpp, game/system/hid/devices/game_controller.h, game/system/hid/input_manager.cpp, game/system/hid/input_manager.h, game/system/hid/sdl_util.cpp, game/system/hid/sdl_util.h, goal_src/jak1/kernel-defs.gc, goal_src/jak1/pc/progress-pc.gc
Related to #2752
I had to try really hard to reproduce this (constantly unplugging and plugging in my controller).  But this seems to happen for a variety of reasons (i got an DirectX error on the `SDL_GameControllerOpen` call one time), now any issue in the original initialization will result in the controller being skipped and picked up on the next reconnect (hopefully).  
~~This may introduce a bug where controllers that legitimately have no name are ignored.  To work around this, a call to `SDL_GameControllerGetAttached` may be needed to differentiate between a bad device handle and a nameless controller.~~
Nope, controllers in this state return `true` for being "attached and valid":
Also I was able to reproduce the LED crash, hopefully checking the handle is sufficient to stave that …
=> sdl: safer code to resolve intermittent controller crashes related to disconnections

game/overlord/common/fake_iso.cpp, game/overlord/common/fake_iso.h, game/overlord/jak1/fake_iso.cpp, game/overlord/jak1/isocommon.h, game/overlord/jak2/iso_cd.cpp, third-party/BS_thread_pool.hpp
Avoids blocking other IOP threads on IO. 
Idk if it'll really help anything, but at least theoretically it might stop some pathologically slow IO case from blocking the VAG buffer switching.
=> overlord: perform file operations on a thread pool

common/repl/util.cpp, third-party/replxx/.github/workflows/ci.yml, third-party/replxx/.gitignore, third-party/replxx/CMakeLists.txt, third-party/replxx/README.md, third-party/replxx/examples/c-api.c, third-party/replxx/examples/cxx-api.cxx, third-party/replxx/include/replxx.h, third-party/replxx/include/replxx.hxx, third-party/replxx/src/conversion.cxx, third-party/replxx/src/history.cxx, third-party/replxx/src/history.hxx, third-party/replxx/src/prompt.cxx, third-party/replxx/src/prompt.hxx, third-party/replxx/src/replxx.cxx, third-party/replxx/src/replxx_impl.cxx, third-party/replxx/src/replxx_impl.hxx, third-party/replxx/src/terminal.cxx, third-party/replxx/src/terminal.hxx, third-party/replxx/src/unicodestring.hxx, third-party/replxx/src/utf8string.hxx, third-party/replxx/src/util.cxx, third-party/replxx/src/util.hxx, third-party/replxx/src/windows.cxx, third-party/replxx/tests.py, vendor.yaml
Closes #722
Took another stab at this and did way too much reading into the current state of terminals.  The proper way to support pasting multiple lines in a terminal is via bracketed paste - https://en.wikipedia.org/wiki/Bracketed-paste
replxx supports this and looking at the implementation it seems to do it right.  This can be confirmed from basically any linux terminal. (Confirmed on macOS - good enough! https://github.com/open-goal/jak-project/pull/2784#issuecomment-1612725605)
The problem is, PowerShell does not support bracketed paste, and neither does the much older `cmd`.  So the problem isn't our code, we'd have to do a whole bunch of windows specific console code for the `paste` handler (this is what powershell apparently does _instead_ of just supporting bracketed paste like …
=> repl: update replxx and some configuration for bracketed paste

CMakeLists.txt, common/CMakeLists.txt, common/util/dialogs.cpp, common/util/dialogs.h, game/CMakeLists.txt, game/graphics/gfx_test.cpp, game/graphics/gfx_test.h, game/graphics/pipelines/opengl.cpp, game/main.cpp, game/system/hid/sdl_util.cpp, game/system/hid/sdl_util.h, third-party/libtinyfiledialogs/CMakeLists.txt, third-party/libtinyfiledialogs/README.md, third-party/libtinyfiledialogs/files.xml, third-party/libtinyfiledialogs/tinyfiledialogs.c, third-party/libtinyfiledialogs/tinyfiledialogs.h, vendor.yaml
This does two main things:
1. Add native-OS dialog box errors for when a critical error is encountered (no AVX, or no OpenGL 4.3 support).  Right now this error is buried in logs and hopefully caught by the launcher's detection which historically has been flawed for a few reasons, which brings us to the second thing this adds.
- Sidenote, this library can also be used for file/folder selection dialogs so that might be useful eventually.
2. A new flag you can pass to `gk`: `--gpu-test opengl`.  This will try to create an OpenGL context with the exact same code that our game will use and write out a result file.  This should be a much more reliable approach for the launcher to use going forward, and will work well if we ever support other graphic's APIs (vulkan/metal).
```json
{
"error": …
```
=> game: Improve OpenGL version detection and make requirement errors more obvious to the user

.github/workflows/linux-build-clang.yaml, .github/workflows/linux-build-gcc.yaml
This fixes an issue which causes `gk` to fail starting up on linux due to the way SDL's cmake works (it looks for this header while compiling, not when running)
=> ci: ensure linux runners have the proper OpenGL headers

common/util/os.cpp
OpenGOAL incorrectly identifies Intel Macs a not supporting AVX.
Use the CPUID instruction for x86_64 Macs as well as Linux.
=> Make setup_cpu_info work on (Intel) Macs

goal_src/jak1/engine/gfx/foreground/bones.gc
Removes a leftover case for falling to back to generic-merc in jak 1. This should fix the bug where daxter's face wasn't animated in the intro after floating-point blerc was added.
=> [jak1] Merc for title - fixes blerc

common/repl/config.cpp, common/repl/config.h, common/repl/util.cpp, goal_src/user/README.md
Turned on by default, REPL history files are now stored separately per game version.
Users can enable the old behavior by adding `"perGameHistory": false` to their REPL config.
=> repl: separate history by game version

common/util/FileUtil.cpp, game/graphics/pipelines/opengl.cpp, game/system/hid/devices/game_controller.cpp, game/system/hid/devices/game_controller.h, game/system/hid/devices/input_device.h, game/system/hid/devices/keyboard.cpp, game/system/hid/devices/keyboard.h, game/system/hid/devices/mouse.cpp, game/system/hid/devices/mouse.h, game/system/hid/display_manager.cpp, game/system/hid/display_manager.h, game/system/hid/input_bindings.cpp, game/system/hid/input_bindings.h, game/system/hid/input_manager.cpp, game/system/hid/input_manager.h
The current event-based approach is very difficult to get right, and it depends on no events ever being missed.  This changes the keyboard/mouse handling code to a polling-based approach.
Other fixes:
- an issue where modifier keys were not able to be successfully bound (like Left Shift to `X`)
- improves cursor hiding (except when you use the start menu, this seems like an SDL issue, see comment)
- Better discarding of kb/mouse inputs when imgui intercepts input
- properly swap bindings when an already set key is assigned, even if it crosses the distinction of an analog vs normal button
Fixes #2800
=> input: Hopefully make keyboard/mouse handling more consistent

goal_src/jak2/engine/ui/minimap.gc
Some missions add way too many icons so the limit is reached. It seems safe to increase by a large amount.
Fixes #2779
=> increase max minimap icons 64 -> 256

common/texture/texture_conversion.h, game/graphics/opengl_renderer/OpenGLRenderer.cpp, game/graphics/opengl_renderer/TextureAnimator.cpp, game/graphics/opengl_renderer/TextureAnimator.h, goal_src/jak2/engine/common_objs/collectables.gc, goal_src/jak2/engine/gfx/texture/texture-anim.gc
This saved about 1.6 ms per frame in the city for me (~1.3 saved from not doing sky twice, 0.3 saved in format lookup tables).
The big texture animator is about 1.0 ms.
=> [jak2] speed up the sky texture animation

game/overlord/jak2/iso_queue.cpp
This fixes the crash reported in https://github.com/open-goal/jak-project/issues/2833
There was a memory bug here for a long time where our array of `VagCmd` in `iso_queue.cpp` was too small. This caused GetVagCommand to return bogus pointers, and sound code would write over other parts of memory.
=> [jak2] Fix overlord related crash

common/texture/texture_slots.cpp, decompiler/config/jak2/ntsc_v1/inputs.jsonc, game/graphics/opengl_renderer/TextureAnimator.cpp, game/graphics/opengl_renderer/TextureAnimator.h, goal_src/jak2/engine/collide/collide-shape.gc, goal_src/jak2/engine/gfx/texture/texture-anim.gc, goal_src/jak2/engine/level/level.gc
- Add security wall animation
- Add waterfall animations
- Add lava animations
- Update layer values from the game to fix the security wall
- Remove leftover debug in `level.gc` that would break level-specific animations on the second time you visited the level
- Optionally load animated slot textures to the pool so generic can use them (fixes skull gems in UI)
=> [jak2] More progress on texture animations

game/graphics/opengl_renderer/debug_gui.cpp
This coming release will change the keybind to hide the topbar.
This is in an effort to avoid answering the question many times.
=> game: add a clear text label for how to hide the top bar

game/graphics/opengl_renderer/TextureAnimator.cpp, game/graphics/opengl_renderer/debug_gui.cpp, game/overlord/common/fake_iso.cpp
There was a single static path buffer being shared between multiple file i/o threads. So sometimes you would end up using the wrong path for the file, and getting size/data for the wrong file.
I think the original reason to have this buffer was just me being lazy when we changed how project paths works a long time ago. It was a bad idea in the first place.
=> Fix possible crash when loading files

goal_src/jak1/levels/snow/target-ice.gc
This should fix a crash and animation bug in snowy. The way to trigger the bug:
- go on ice
- move forward slowly
- stop moving forward. Reach zero speed when the frame number isn't between 30 and 35 of the ice walking animation
- Due to this bug, the animation gets stuck at frame 60
- Take damage (due to normal lurker or ice lurker)
- Sidekick eye animation crashes because a frame number is NaN.
=> [jak1] Fix ice walking animation bug and crash

decompiler/level_extractor/extract_level.cpp, decompiler/level_extractor/extract_merc.cpp
The yakow texture is actually missing from the real game too. 
This adds a special case in the extractor to replace it with a similar-ish fur texture:
=> [jak2] workaround for missing yakow textures

game/graphics/opengl_renderer/shaders/shrub.vert
Should probably wait until the release just in case. But I'm 99% sure this line was just a mistake in the original implementation.
=> [jak2] fix transparent shrub blending

goal_src/jak2/engine/gfx/ocean/ocean-h.gc, goal_src/jak2/engine/gfx/ocean/ocean-mid.gc, goal_src/jak2/engine/gfx/ocean/ocean-transition.gc
When drawing the spinning palace, there's a terrible hack that lets some stuff be drawn with different camera matrices.
The ocean is drawn with camera-other (which spins), but was being culled with camera (doesn't spin). This changes ocean to use the right camera matrix.
Note that the ocean is special when it comes to camera-other - it always uses camera-other if there is one. Other uses are set per-level and should already be handled correctly.
=> [jak2] Fix ocean culling when using camera-other

game/graphics/opengl_renderer/BlitDisplays.cpp, game/graphics/opengl_renderer/BlitDisplays.h, game/graphics/opengl_renderer/BucketRenderer.h, game/graphics/opengl_renderer/OpenGLRenderer.cpp, game/graphics/opengl_renderer/OpenGLRenderer.h, game/graphics/opengl_renderer/TextureAnimator.cpp, game/graphics/opengl_renderer/opengl_utils.cpp, game/graphics/opengl_renderer/opengl_utils.h, goal_src/jak2/engine/gfx/blit-displays.gc
This changes how `BlitDisplays.cpp` works so it looks at the current render buffer, rather than the back buffer.
This approach is a bit faster because we avoid copying the back buffer on every single frame.
It also removes the black frames when the transition starts/stops.
The remaining issues are:
- there's still a single frame of weirdness with the sprite glow renderer.
- when changing resolutions, it doesn't work super well.
=> [jak2] use current buffer for blit-displays

game/graphics/opengl_renderer/foreground/Merc2.cpp, goal_src/jak2/engine/gfx/foreground/foreground.gc
In jak 2, there's an option to disable envmap. It's used on krew holograms, hiphog trophies, and baron bosses in palace/tomb.
=> [jak2] disable envmap when it should be

game/graphics/opengl_renderer/BucketRenderer.h, game/graphics/opengl_renderer/CollideMeshRenderer.cpp, game/graphics/opengl_renderer/background/Shrub.cpp, game/graphics/opengl_renderer/background/TFragment.cpp, game/graphics/opengl_renderer/background/TFragment.h, game/graphics/opengl_renderer/background/Tie3.cpp, game/graphics/opengl_renderer/background/background_common.cpp, game/graphics/opengl_renderer/background/background_common.h
The way we got/stored background matrices is a bit weird and full of leftovers from the first attempts at porting renderers. This doesn't work well with the Jak 2 "other camera" system where some stuff is rendered with a different camera matrix. 
This cleans most of it up. The exception is that the collide mesh renderer and the additional sprite culling I added still need to peek at some cached camera matrices. 
This fixes the problem where etie uses the wrong matrices for "other camera" levels. Now the "hole covers" go in the holes in the background of the throne room.
=> [gfx] Clean up background renderer matrices, fix "hole covers"

.github/scripts/releases/extract_build_unix.sh, .github/workflows/linux-build-clang.yaml, .github/workflows/macos-build.yaml, .github/workflows/release-pipeline.yaml, .github/workflows/windows-build-clang.yaml
Was causing the macOS release to fail, you can't `strip` a Mach-O binary with gnu's `strip`.  This has the added benefit of majorly reducing binary size which should have a noticable impact in the upload/download steps.
=> ci: strip binaries in their respective runners

goal_src/jak1/engine/ui/progress/progress.gc, goal_src/jak1/pc/progress-pc.gc
=> jak1: start a new game correctly when speedrunner mode is enabled

common/log/log.cpp, common/util/FileUtil.cpp, common/util/FileUtil.h
Small improvement to prevent accidental file deletion.  Shouldn't really happen for the normal `jak-project` logs.  But the LSP for example takes a log-file path, if you put that as your root directory that could cause issues, atleast performance ones (it currently doesn't rotate but that's an unrelated bool that could be flipped without realizing/forgetting about this).
So just look at the immediate directory contents for the expected logs.
=> log: don't recursively iterate when rotating log files

goal_src/jak1/engine/gfx/texture/texture.gc, goalc/build_level/build_level.cpp
Force FR3 file name for custom levels to be uppercase, fixes the crash described in 
https://github.com/open-goal/jak-project/issues/2534
and 
https://github.com/open-goal/jak-project/issues/2897
=> [jak1] Fix texture-related custom level crash

goal_src/jak2/engine/game/main.gc, goal_src/jak2/engine/gfx/foreground/merc/merc-blend-shape.gc
fixes the weird mirror offset stuff
=> [jak2] fix bad blerc on objects with warp

game/kernel/jak2/kmachine.cpp, goal_src/jak1/pc/pckernel-h.gc, goal_src/jak2/engine/ui/bigmap.gc
- fix deci2 hang when closing the game in retail mode.
- change bigmap to always filter because the pixels look really ugly.
- don't start the game in fullscreen by default if we're debugging.
=> [jak2] small minor fixes

game/graphics/opengl_renderer/sprite/GlowRenderer.cpp
oops, forgot to set `glDepthMask`, so sometimes it was enabled, and the drawing for the clear was writing into the depth buffer.
Fixes https://github.com/open-goal/jak-project/issues/2735
=> [jak2] fix glow sprite flickering

game/graphics/opengl_renderer/DirectRenderer.cpp, game/graphics/opengl_renderer/shaders/direct_basic_textured.frag
Fixes https://github.com/open-goal/jak-project/issues/2814
Previously we didn't handle `GREATER` vs `GEQUAL` correctly. I just left this as a TODO by accident.
=> Fix alpha test > vs >= (minimap arrow fix)

game/graphics/opengl_renderer/DirectRenderer.h, game/graphics/opengl_renderer/TextureAnimator.cpp, game/graphics/opengl_renderer/TextureUploadHandler.cpp, goal_src/jak2/pc/pckernel.gc
Fix an issue where the commit sha would not use the right blending mode if `draw-raw-image` is running at the same time.
Fix an issue where japanese subtitles would accidentally overwrite other textures, leading to random textures missing. (in particular, glows would disappear after watching a cutscene with the subtitles on)
=> [jak2] fix a few silly texture bugs

game/kernel/jak1/fileio.cpp, game/kernel/jak2/fileio.cpp, test/test_kernel_jak1.cpp
Ever since we started splitting files up by game version in #1559, these file paths were broken, so whenever the game tried to link art group files, you would get this error because the file is actually located in `out/jak1/obj`:
```
dkernel: file read !open 'out/obj/plat-ag.go' (-1)
ERROR: art-group "plat" is not a valid file.
****** CALL TO loado(plat-ag) ******
[SCE] sceOpen(jak-project/out/obj/plat-ag.go) failed.
```
This was a particular problem in custom levels, causing actors like platforms to not show up.
=> ckernel: fix file paths for art groups and tpages

custom_levels/test-zone/test-zone.jsonc, custom_levels/test-zone/testzone.gd, decompiler/level_extractor/extract_level.cpp, decompiler/level_extractor/extract_level.h, goalc/CMakeLists.txt, goalc/build_level/build_level.cpp, goalc/build_level/build_level.h
Previously, custom levels could only have non-common merc models in them if you had another level loaded whose FR3 did have those models.
Similar to #2934, this PR aims to solve the issue by spinning up a barebones version of the extractor during the custom level build to find any art groups that the level requires, going through all the official level DGOs (ignoring any duplicates), extracting the models and textures from them and adding them to the custom level's FR3 file.
To define all the models you want in your custom level, the level JSONC has a new entry:
```jsonc
// All art groups you want to use in your custom level. Will add their models and corresponding textures to the FR3 file.
// Note: You will still have to add them to your level's .gd file.
"art_groups": ["plat-ag"]
```
I …
=> custom levels: add support for packing models and textures into the FR3 file

game/tools/subtitle_editor/subtitle_editor.cpp, game/tools/subtitle_editor/subtitle_editor.h, goalc/data_compiler/game_text_common.cpp
- fix speaker names and time frames being uneditable in Jak 1
- added toggle to auto-selected a newly created scene as current
- changed the subtitle summary format slightly.
- current scene's name now appears in the UI
=> various subtitle editor fixes

game/graphics/opengl_renderer/sprite/Sprite3.cpp
I don't think this fixes anything, but the number was wrong so might as well fix it.
=> [sprite3] fix max sprite number being wrong

common/audio/audio_formats.cpp, common/audio/audio_formats.h, decompiler/config/jak2/ntsc_v1/inputs.jsonc, decompiler/data/streamed_audio.cpp, decompiler/data/streamed_audio.h, decompiler/main.cpp
There are potentially still some minor issues with the resulting files.  Some of them appear to have minor artifacts that playing through the actual game do not -- but this is a much better starting point for someone to iterate from if they are interested in improving things.
=> decomp: handle dumping jak 2 VAG file assets

decompiler/CMakeLists.txt, decompiler/ObjectFile/LinkedObjectFile.cpp, decompiler/ObjectFile/LinkedObjectFile.h, decompiler/level_extractor/BspHeader.cpp, decompiler/level_extractor/BspHeader.h, decompiler/level_extractor/extract_actors.cpp, decompiler/level_extractor/extract_actors.h, decompiler/level_extractor/extract_level.cpp, decompiler/level_extractor/extract_tfrag.cpp, decompiler/util/goal_data_reader.cpp, decompiler/util/goal_data_reader.h, goalc/build_level/build_level.cpp
This will create a folder like `decompiler_out/jak1/entities` and save a JSON file per level with all the actors.
Also, it should hopefully make custom level building a little faster.
=> Save entities to JSON, and make custom level building a little faster

.github/workflows/inform-pages-repo.yaml, .github/workflows/linting.yaml, .github/workflows/linux-build-clang.yaml, .github/workflows/linux-build-gcc.yaml, .gitignore, .vscode/opengoal.code-snippets, goal_src/jak1/engine/common-obs/generic-obs.gc, goal_src/jak2/engine/collide/collide-mesh.gc, goal_src/jak2/levels/castle/castle-obs.gc, goal_src/jak2/levels/city/helldog/helldog.gc, goal_src/jak2/levels/city/palace/ctypal-obs.gc, goal_src/jak2/levels/common/airlock.gc, goal_src/jak2/levels/palace/pal-obs.gc, scripts/ci/lint-gsrc-removals.py
This is something that's caught us a few times, code is patched and then accidentally removed when doing a big decompilation or cleanup pass.  By flagging such patches with `og:preserve-this` comments, The CI will pick up on them, fail loudly, and it can either be merged anyway or be fixed before merging -- avoiding a regression.
=> CI: check for removed goal_src code that we want or need to perserve

.github/workflows/linting.yaml
Some checks we never want to merge with them failing, others we do.  Separate them accordingly.
=> ci: separate lint checks into a required and optional workflow

game/kernel/jak2/kscheme.cpp, game/kernel/jak2/kscheme.h, goal_src/jak2/engine/load/file-io.gc
These two functions were stubbed out in the Jak 2 C kernel, making it not possible to dynamically link art groups when e.g. manually spawning `process-drawable`s.
I copied them from Jak 1 verbatim and they seem to work fine.
=> [jak2] ckernel: implement `loado` and `load_and_link`

goalc/compiler/compilation/ControlFlow.cpp, goalc/compiler/compilation/Macro.cpp
Ancient bug! Resulted in a 1%-2% decrease in code object file size (and more importantly the asm is more readable).
Fixes #3029
=> [compiler] fix `compile_condition` not attempting macro expansion

goal_src/jak2/pc/features/speedruns.gc, goal_src/jak2/pc/pckernel.gc
This was a copy-paste from jak1's implementation, it's not needed in Jak 2. This fixes a crash when explicitly picking "continue without saving" and the game hits an auto-save trigger.
=> g/j2: don't force auto-save on in jak 2 when starting a speedrun

game/graphics/opengl_renderer/shaders/glow_depth_copy.frag, game/graphics/opengl_renderer/sprite/GlowRenderer.cpp
Fix a typo in the shader. (fixes https://github.com/open-goal/jak-project/issues/3045, and fixes fadeout when glows move offscreen on the bottom).
Also, try a different format for the depth blit, in an attempt to fix this issue https://github.com/open-goal/jak-project/issues/3065.
=> [jak2] new glow fix

goal_src/jak2/engine/ui/minimap.gc, goal_src/jak2/levels/common/race/race-hud.gc
Fixes #2994 the underport and consite icons being green (same color as the goal, likely copy-pasta).
Fixes the hundredths timer in the race timer actually being a 60ths timer.
=> [jak2] fix minor original game visual bugs

decompiler/level_extractor/extract_collide_frags.cpp
Fixes missing collision geometry reported in https://github.com/open-goal/jak-project/issues/3011
The issue happens when there are 256 polygons. In this case `num-polys` is 0 (it's a u8). There are actual cases where there are 0 polygons, so we have to do a more complicated check to get the real count. I should have done this in the first place, but it seemed to work...
=> [jak2] Fix collision renderer extract

decompiler/data/TextureDB.cpp, decompiler/data/TextureDB.h, decompiler/extractor/main.cpp, decompiler/main.cpp
This adds a new feature to the decompiler to complement texture _replacement_ with what I'm calling texture _merging_.
Instead of taking a PNG and using it's data to fully replace an existing texture, we instead only replace the pixels that are non-transparent from the merge image.
This might be useful in a few other situations, **but what I'm interested in using it for is expanding the game's font without having to commit any of the existing texture assets, just merging in individual new characters.**  
For Jak 1, there isn't much empty room available and I'm not sure how easy it would be to support larger font-textures.  But in Jak 2, across all `font.24*` textures, there are over 200 unused character slots.
In some ways, this is an interim workaround because adding brand new textures …
=> decompiler: add texture merging feature

custom_levels/test-zone/test-zone.jsonc, goalc/build_level/build_level.cpp
This adds support for manually specifying which of the game's textures to pack into a custom level's FR3 file. Textures like the zoomer HUD are neither located in the common level files nor part of any art group, so the only way for them to work in custom levels is to directly pack them into the FR3.
=> custom levels: support for packing textures

third-party/zydis/resources/VersionInfo.rc
This fix is for the following error when building with llvm on windows
```
[build] llvm-rc: Error in VERSIONINFO statement (ID 1): 
[proc] The command: "C:\Program Files\CMake\bin\cmake.exe" --build C:/.../git/jak-project-test/out/build/Release --parallel 8 exited with code: 1
[build] Non-ASCII 8-bit codepoint (´┐¢) can't be interpreted in the current codepage
[build] ninja: build stopped: subcommand failed.
```
It's caused by llvm-rc not handling non 8-bit characters.
The same issue is discussed in the curl project here
https://github.com/curl/curl/issues/7765
This commit copies the fix from curl, replacing '©' with '(C)'.
=> Fix build failure at llvm-rc on windows due to codepage error on zydis

decompiler/config/jak2/jak2_config.jsonc, decompiler/config/jak2/pal/label_types.jsonc
This was added as the progress file's L879 has a different type in the PAL
version of the game: being 'progress-global-state' rather than 'unit64'.
The difference caused the decompiler to die with a mismatched type error.
=> Add label_types file merge for PAL version

.github/workflows/windows-build-msvc.yaml
Related to https://github.com/actions/runner-images/issues/8598
For whatever reason, this updating of perl causes cmake to behave totally differently, leading to a consistent failure in SDL.  One glaring difference I noticed was the value of `CMAKE_SYSTEM` was `Windows-6.2.9200` which is for windows 8! instead of what the runners actually use, windows server 2022
=> ci: Workaround CMake/Perl regression in recent windows-2022 images

goal_src/jak1/pc/features/speedruns.gc
This fixes hub2 and hub3 100% categories to start at the same continue point as PS2 runs (also let's you submit a section from a full 100% run)
=> Fix starting continue point for Hub 2/3 category extensions

.github/workflows/windows-build-clang.yaml
This seems to have changed the way the cmake was generated due to it finding libraries that aren't normally found -- causing a bad statically linked release.
=> ci/windows: stop Strawberry perl from changing resulting built artifacts in CI

goal_src/jak1/engine/ui/text.gc, goal_src/jak2/engine/ui/text-h.gc, goal_src/jak2/engine/ui/text.gc, goal_src/jak2/pc/pckernel-impl.gc
It works now so I figured Id open it for input on the final remaining things.
Things Im not satisfied with
*fallback-text-lookup?* being defined in pc-kernel-impl.gc, Isnt there a way to just add this to pc-kernel-common??
I would like a close double check on the logic on lines 198-207 I'm pretty sure all the bases are still covered and it will never not find anything but I just want a double check
Fixes #3118
=> Add fallback text functionality to Jak 2

game/graphics/opengl_renderer/sprite/GlowRenderer.cpp
Maybe fix https://github.com/open-goal/jak-project/issues/3065?
=> [jak2] Try to fix glow again

goal_src/jak2/engine/gfx/mood/mood-funcs.gc, goal_src/jak2/engine/math/trigonometry.gc
This patches the rotation of the palace so that it works in high fps mode.
I didn't change the behavior of anything in `trigonometry.gc` - just added an `unwrap-angle` macro so we could try changing the behavior more easily when debugging high-fps issues in the future. (interestingly, nothing obvious is wrong with using the higher accuracy unwrap function for all trig functions).
=> [jak2] Fix palace rotation at high fps

game/kernel/jak2/kprint.cpp
fixes the crash when this message is displayed:
as far as I can tell, it looks right.
=> [jak2] Pass 0x01 through format

goal_src/jak2/levels/nest/boss/metalkor-states.gc, goal_src/jak2/pc/features/autosplit-h.gc, goal_src/jak2/pc/features/autosplit.gc
Right now the autosplitter has no ending conditions setup, some more code needed to be added to make that a reality.  Jak 2 speedruns have 3 main end triggers to worry about:
- final hit on kor
- all collectables (including darkjak powers)
- all orbs (this one we could already do)
=> g/j2: Add ending condition checks to the autosplitter struct

CMakeLists.txt
No longer dependent on those libraries:
Fixes #3160
=> cmake: use static OpenSSL libraries on linux

game/graphics/opengl_renderer/sprite/GlowRenderer.cpp, game/graphics/opengl_renderer/sprite/GlowRenderer.h, game/graphics/opengl_renderer/sprite/Sprite3_Glow.cpp, goal_src/jak2/engine/gfx/sprite/particles/sparticle.gc, goal_src/jak2/engine/gfx/sprite/sprite-h.gc, goal_src/jak2/engine/gfx/sprite/sprite.gc
Makes the glow sprite renderer flush when full capacity is reached, instead of at the end. Also allows us to reduce the textures used for it (finally). Worst case scenario there's 4-5 flushes per frame.
Fixes incessant flickering in the dig.
=> reduce glow renderer vram usage + raise glow sprite limit

goal_src/jak2/levels/forest/forest-obs.gc
Thought this may have been a regression but apparently we never patched this one.
Fixes #3196
=> fix forest youngsamos crash when he runs out of health

game/graphics/opengl_renderer/loader/Loader.cpp, game/graphics/opengl_renderer/loader/Loader.h, game/graphics/opengl_renderer/loader/LoaderStages.cpp
This should avoid the stuttering due to slow unloading on some drivers.
I also turned up the amount of stuff we load per frame since nobody has been complaining about stutters there, but there has been a few cases of levels loading in too slowly.
(this only changes graphics, not actual GOAL level load times).
=> [Loader] Unload less stuff per frame

common/custom_data/TFrag3Data.cpp, common/custom_data/Tfrag3Data.h, common/formatter/rules/rule_config.h, decompiler/level_extractor/extract_shrub.cpp, game/graphics/opengl_renderer/background/Shrub.cpp, game/graphics/opengl_renderer/background/Shrub.h, goal_src/jak2/engine/gfx/shrub/shrubbery.gc
Fixes the issue reported in https://github.com/open-goal/jak-project/issues/3168, https://github.com/open-goal/jak-project/issues/3189, https://github.com/open-goal/jak-project/issues/3166, https://github.com/open-goal/jak-project/issues/3152, https://github.com/open-goal/jak-project/issues/3224 where a small part of the pipes in the `strip-grenade` mission appear, but shouldn't.
=> [jak2] Support per-proto shrub visibility

decompiler/data/TextureDB.cpp
There are art groups that are present in multiple levels, and that means that also their textures are present in multiple levels. With texture replacement, currently we need to make replacements for all instances if we want it replaced everywhere, but this is not ideal, especially when you make changes to your replacement texture and now you have to put it in each folder again.
I added a way to replace all instances of a texture, by letting texture-replacer people put their replacements into an '_all' folder. I set up the logic in such a way that if you have a replacement for the texture in its corresponding folder, it will take priority over a replacement that you placed into the '_all' folder.
I personally found this very useful for replacing guard textures. The guards appear in a lot …
=> Allow replacing all instances of a texture with one texture

.vs/launch.vs.json, decompiler/ObjectFile/ObjectFileDB.h, decompiler/ObjectFile/ObjectFileDB_IR2.cpp, decompiler/analysis/analyze_inspect_method.cpp, decompiler/config/jak3/all-types.gc, decompiler/config/jak3/jak3_config.jsonc
This will make a best effort attempt at guessing which process a non-virtual state belongs to:
I also noticed some issues while working on this, mainly around how virtual states were being output.  They were being duplicated, for example:
or
I think I've fixed that, but @Hat-Kid I defer to you to see if i've done something terrible.
=> d/j3: all-types: guess at associated process for non-virtual states and fix some issues along the way

game/system/hid/devices/game_controller.cpp, game/system/hid/devices/keyboard.cpp, game/system/hid/input_bindings.cpp, game/system/hid/input_bindings.h, game/system/hid/input_manager.cpp
This was just not implemented end to end.  There are still two notable issues, one that I can live with, one I need to narrow down eventually:
1. Rebinding confirm buttons with trigger (ie. X) behaviour is not 100% as it should be.  I fixed it enough that I can live with it but it's still not proper.  The difficulty is that unlike a button it will re-trigger the pressed state on the journey back to neutral (aka unpressed).
2. If you change the bind for the confirm button, then reset your bindings, the next confirm input is eaten.  This is unrelated to these changes but I briefly looked into it and was unable to find the root cause.
=> game: Fix issues related to remapping with SDL axii's (ie. triggers)

common/goos/Interpreter.cpp, common/log/log.cpp, common/serialization/subtitles/subtitles_v2.cpp, common/util/Assert.cpp, decompiler/ObjectFile/ObjectFileDB_IR2.cpp, decompiler/analysis/expression_build.cpp, decompiler/analysis/inline_asm_rewrite.cpp, decompiler/level_extractor/extract_collide_frags.cpp, game/main.cpp, goalc/compiler/Compiler.cpp, goalc/compiler/Util.cpp, goalc/compiler/compilation/Macro.cpp, goalc/debugger/Debugger.cpp, test/offline/framework/file_management.cpp
The logger used in `goalc` tries to print an already-formatted string `message` using `fmt::print(message);` Usually this doesn't cause problems, but if you try to print, for example, an exception that has special characters (notably `{`) it will try to do another round of formatting/replacements, despite not having any args to replace with, which ends up throwing another exception. This is why errors when parsing custom level JSON cause the REPL to exit.
I've hopefully identified all the various instances of this across the codebase
=> Fix cases of string formatting with non string literals

custom_levels/jak1/test-zone/test-zone.jsonc, custom_levels/jak2/test-zone/test-zone.jsonc, decompiler/util/DecompilerTypeSystem.cpp, decompiler/util/DecompilerTypeSystem.h, goalc/build_level/common/Entity.cpp, goalc/build_level/common/Entity.h, goalc/build_level/jak1/Entity.cpp, goalc/build_level/jak1/Entity.h, goalc/build_level/jak1/build_level.cpp, goalc/build_level/jak2/Entity.cpp, goalc/build_level/jak2/Entity.h, goalc/build_level/jak2/build_level.cpp
This adds support for using enums in lumps using the new lump types `enum-int32` and `enum-uint32`. Also adds these other new lump types:
- `water-height` (takes 3 meter floats, an enum and another optional meter float)
- `eco-info` (takes an enum and an int)
- `vector3m` (3 meter floats + `w` set to 1.0)
=> custom levels: enum lump support

third-party/zydis/include/Zydis/ShortString.h
Fix zydis alignment issues when building on Intel macOS builds was discussed with zydis devs https://github.com/zyantific/zydis/issues/474
Verified locally that I can run open goal with the change.
=> fix zydis alignment issue during build for intel macs

goalc/build_level/jak1/build_level.cpp, goalc/build_level/jak2/build_level.cpp
When giving entities custom actor IDs in your level JSON, it is possible to break entity lookups by actor ID if the actors are not sorted by ID because `entity-by-aid` expects them to be in order.
This sorts the actor list by ID before generating the level file and also checks for any duplicates.
=> custom levels: sort actors by aid and check for duplicates

custom_levels/jak1/test-zone/test-zone.jsonc, goalc/build_level/common/Entity.cpp
Adds two new lump types: `cell-info` and `buzzer-info`.
`cell-info` takes a `game-task` enum value and defines an `eco-info` lump for power cells.
`buzzer-info` takes a `game-task` enum value and an integer and automatically calculates the required value for the buzzer task with the formula `task + buzzer * (1 << 16)`.
=> custom levels: `cell-info` and `buzzer-info` lumps

goalc/build_level/common/gltf_mesh_extract.cpp
It seems like this depends on the version of blender, so we should support both.
=> [gltf] Support either u16 or float for colors

decompiler/config.cpp, decompiler/config.h
This is handy when you want to try comparing the decompiler's output across games (ie. for checking if only naming differs)
=> decomp: add a new config flag to disable var-name casts

CMakeLists.txt
I'm tired of it spamming and I couldn't figure out what adds to non-existent fmt/include dir.
=> cmake: Remove -Wmissing-include-dir

Taskfile.yml, decompiler/config.cpp, decompiler/config.h, decompiler/config/jak1/jak1_config.jsonc, decompiler/config/jak2/jak2_config.jsonc, decompiler/config/jak3/jak3_config.jsonc, decompiler/extractor/main.cpp, decompiler/level_extractor/extract_collide_frags.cpp, decompiler/level_extractor/extract_collide_frags.h, decompiler/level_extractor/extract_level.cpp, decompiler/level_extractor/extract_level.h, decompiler/main.cpp
Added a new `rip_collision` flag to the decompiler config and wired it up. Cleaned up the comments around these fields in the JSON too for clarity
Also refactored a bunch of the related extract functions to read from `config` object rather than pass down a bunch of booleans
=> Rip collision based on config flag

game/graphics/opengl_renderer/sprite/Sprite3_Distort.cpp, goal_src/jak1/engine/gfx/sprite/sprite-distort.gc, goal_src/jak2/engine/gfx/sprite/sprite-distort.gc
Apparently a long standing bug, with https://github.com/open-goal/jak-project/pull/3194 making it more likely to occur.
=> game: fix intermittent sprite_distort related crash

CMakeLists.txt, common/global_profiler/GlobalProfiler.h, common/log/log.h, common/type_system/TypeSystem.cpp, common/util/FileUtil.cpp, common/util/Trie.h, decompiler/Function/Warnings.h, decompiler/IR2/Form.h, decompiler/IR2/GenericElementMatcher.cpp, decompiler/IR2/GenericElementMatcher.h, decompiler/IR2/OpenGoalMapping.cpp, decompiler/VuDisasm/VuDisassembler.cpp, decompiler/data/streamed_audio.cpp, decompiler/extractor/extractor_util.cpp, decompiler/level_extractor/extract_tfrag.cpp, decompiler/util/Error.h, goalc/compiler/StaticObject.cpp, goalc/make/MakeSystem.cpp, goalc/make/Tools.cpp
Just putting this here for consideration, I'm personally not in a big rush to get it.
=> Update to C++20

lsp/state/workspace.cpp
This didn't really pan out as I hoped since files can have thousands of these and there is a limit to how many diagnostics are shown (starting from the top of the file).  This also may have caused the recent instability in the LSP, disabling this i wasn't able to reproduce an LSP crash cycling through 50-100 files.
=> lsp: revert unnamed variable labelling

common/global_profiler/GlobalProfiler.cpp, common/global_profiler/GlobalProfiler.h, game/graphics/gfx.cpp, game/graphics/pipelines/opengl.cpp, game/main.cpp, game/system/hid/display_manager.cpp, game/system/hid/input_manager.cpp
While trying to narrow down why sometimes SDL takes 20-40seconds to initialize I built up some more profiling features.
TLDR - I still don't know why SDL is taking a long time but I've narrowed it down to it initializing the `GAME_CONTROLLER` subsystem.  This isn't unprecedented, I found numerous github issues and articles suggesting this is the problem:
I imagine it is hardware/OS related on some level, there are even some recent commits in SDL that have made it worse on certain platforms.  I've had this problem myself so I will hope to get it again soon so i can debug where in the SDL code the delay occurs and make a proper bug report.  Hopefully this helps but it's not yet confirmed - https://github.com/open-goal/jak-project/pull/3384
=> tracing: add some more startup related events and a new `--profile-until-event` flag

game/system/hid/devices/mouse.cpp, game/system/hid/devices/mouse.h, goal_src/jak2/pc/progress/progress-static-pc.gc
- Wired up the menu settings to change the settings in game, not just on boot
- Removed all the duplication in the game options menu code
- Fixed the mouse code so that it properly brings the virtual analog stick back to neutral when the mouse stops
- Extended the sensitivity min/max for those that want to ensure the slightest movement maxes out virtual analog stick.
=> g/j2: properly wireup mouse settings, properly detect when the mouse has stopped moving

goal_src/jak1/engine/anim/joint.gc, goal_src/jak2/engine/anim/joint.gc, goal_src/jak3/engine/anim/joint.gc
I was missing one of the ways that the joint animation was interpolated. In particular - the `matrix` that defines the root position of the object.
=> [joint] fix missing matrix interpolation

.github/workflows/linux-build-clang.yaml, .github/workflows/linux-build-gcc.yaml, .github/workflows/macos-build-arm.yaml, .github/workflows/macos-build.yaml, .github/workflows/windows-build-clang.yaml, .github/workflows/windows-build-msvc.yaml
The original buildcache action has been archived, and buildcache itself has also moved to github.
I forked the action and was updating it to work, but then the latest buildcache release once again breaks support for older runners (in our case, macos-12 is the lowest, which is acceptable as 11 is EOL).
Either way, switching to sccache is not only a way cleaner solution but it is also well maintained (and works!)
=> ci: move to `sccache`

.github/workflows/macos-build-arm.yaml, .github/workflows/macos-build.yaml
macos-11 is end of life, it has been for 5 months https://endoflife.date/macos, it will be removed as a runner on github in Q2 2024.  Next release will require atleast macOS 12.
=> ci: move to macos-12

game/overlord/jak2/dma.cpp
This is not a fix, but it temporarily works around the potential crash discussed here https://github.com/open-goal/jak-project/issues/2988
As long as this doesn't impact other things, this feels like a good interim fix, as having a broken cutscene is better than a fatal crash and it might be some time before this is properly identified and fixed.
=> g/j2: workaround intermittent lifeseed DMA crash

docs/progress-notes/bones.md, goal_src/jak1/engine/gfx/foreground/bones.gc, goal_src/jak2/engine/gfx/foreground/bones.gc, goalc/compiler/compilation/Asm.cpp, goalc/regalloc/Allocator_v2.cpp, goalc/regalloc/allocator_interface.cpp
Reverse engineer the skinning matrix calculation and port to GOAL.  This is about 3x faster than the MIPS2c version.
As usual, there is a `*use-new-bones*` flag to go back to the old version. 
Fix for a bug in the compiler's `.div.vf` implementation (only happens if src/dst are the same), and fix for a typo in the register allocator that would sometimes cause it not to consider xmm8-xmm15.
=> Port `bones.gc` math to GOAL

goal_src/goal-lib.gc
Uses (block) and (return-from) to support (break) and (continue) with labeling
Supports `(while) (until) (dotimes) (countdown) (loop) (doarray)`
Test cases:
``` lisp
(dotimes (i 5)
(when (= i 2)
(break)
)
(format #t "i: ~D~%" i)
)
;; Output:
;; i: 0
;; i: 1
(dotimes (i 5)
(when (= i 2)
(continue)
)
(format #t "i: ~D~%" i)
)
;; Output:
;; i: 0
;; i: 1
;; i: 3
;; i: 4
(dotimes (i 3)
(when (= i 2)
(continue)
)
(format #t "outer: ~D~%" i)
(dotimes (i 3)
(when (= i 0)
(continue)
)
(format #t "inner: ~D~%" i)
)
)
;; Output:
;; outer: 0
;; inner: 1
;; inner: 2
;; outer: 1
;; inner: 1
;; inner: 2
(dotimes (i 5) :label outer
(when (= i 2)
(continue :from outer)
)
(format #t "outer: ~D~%" i)
(dotimes (i 3)
(when (= i 1)
(continue :from outer)
)
(format #t "inner: ~D~%" i)
)
)
;; Output:
;; outer: 0 …
```
=> [goal] Add labels, break, and continue to loops

decompiler/config/jak3/all-types.gc, game/CMakeLists.txt, game/kernel/common/klink.h, game/kernel/jak3/klink.cpp, game/kernel/jak3/kscheme.cpp, game/kernel/jak3/kscheme.h, game/mips2c/jak3_functions/collide_func.cpp, game/mips2c/jak3_functions/debug.cpp, game/mips2c/jak3_functions/foreground.cpp, game/mips2c/jak3_functions/joint.cpp, game/mips2c/jak3_functions/lights.cpp, game/mips2c/jak3_functions/texture.cpp, game/mips2c/mips2c_table.cpp, goal_src/jak3/engine/anim/joint.gc, goal_src/jak3/engine/camera/cam-start.gc, goal_src/jak3/engine/gfx/foreground/eye-h.gc, goal_src/jak3/engine/gfx/mood/mood.gc, goal_src/jak3/engine/gfx/sprite/particles/sparticle-launcher.gc, goal_src/jak3/engine/gfx/texture/texture.gc, goal_src/jak3/engine/level/level.gc, goal_src/jak3/engine/math/matrix-h.gc, goalc/debugger/Debugger.cpp, test/decompiler/reference/jak3/engine/math/matrix-h_REF.gc
The `test-play` macro is back, though it doesn't call `play` yet. We can at least load all of `game.cgo`, which involves loading a lot of the code we've decompiled, loading/linking objects files compiled by OpenGOAL (like dir-tpages), and loading/linking Jak's art-groups (for jak 3 they are stored v5 format that I added to the linker).
There were no major issues - just a few forgotten mips2c entries and minor bugs/functions that needed stubs. Most of the work was updating the linker. Hopefully I'll never have to touch that code again - I think it supports everything we need for jak 3!
=> [jak3] A bunch of small fixes to get `game.cgo` to load

goal_src/jak1/pc/progress-pc.gc
This was hiding options for people that only had 60hz monitors since the two menus drifted -- it is not necessary for an entire separate menu, just disable the option if applicable.
Don't merge this without testing it throughly
=> g/j1: remove the redundant graphics menu

goal_src/jak1/engine/game/main.gc
fixes this crap - happens if you use the Select variation of the speedrun menu combo (hold L1+R1+X) during movies
https://github.com/open-goal/jak-project/assets/2515356/52ffe700-0662-42d5-aa7d-1d9d71bb94fb
With the changes in this PR, it now behaves as you'd expect - the same as a normal Select pause
For reference, original changes adding the combo on Select - https://github.com/open-goal/jak-project/pull/2196/files
=> Fix bad speedrun Select pause behavior

.github/workflows/macos-build.yaml, CMakeLists.txt
Related to #3439
Will see after a few weeks if the problem resurfaces. All macos related caches have been purged to eliminate that as a possibility.
=> ci: pin to avx for macos

game/main.cpp
`--portable` was using the path to the executable's file, instead of the directory that contains the executable
=> game: fix the path the`--portable` flag determines

goal_src/jak2/engine/debug/default-menu.gc
Adds some debug options that make it easier to quickly complete the game, get orbs, unlock cheats, etc.
=> g/j2: add some debug menu options to unlock things and give orbs/gems/ammo

goal_src/jak1/pc/features/speedruns.gc, goal_src/jak1/pc/progress-pc.gc
Currently PS2 Actor Vis and FPS are only enforced when starting a run - this enforces them on every frame similar to cheats.
In the progress menu, FPS is already disabled in speedrunner mode - this adds the same restriction for PS2 Actor Vis.
Jak 2 already does this properly, no change needed there
=> [jak1] Enforce certain pc-settings in speedrunner mode

common/global_profiler/GlobalProfiler.cpp, common/global_profiler/GlobalProfiler.h, common/log/log.cpp, common/util/compress.cpp, common/util/compress.h, decompiler/ObjectFile/ObjectFileDB_IR2.cpp, game/graphics/opengl_renderer/debug_gui.cpp, game/graphics/opengl_renderer/debug_gui.h, game/graphics/pipelines/opengl.cpp
- Can make the event buffer larger or smaller
- UI shows the current event index / size, so you know how fast it's filling up
- Can save compressed, 10x reduction in filesize and Windows 11 explorer actually supports ZSTD natively now so this isn't inconvenient at all
> An example of almost 1 million events.  Results in a 4mb file.
=> debugging: Improve event profiler utility

common/util/os.cpp, common/util/os.h, decompiler/CMakeLists.txt, decompiler/ObjectFile/ObjectFileDB_IR2.cpp, decompiler/config.cpp, decompiler/config.h, decompiler/config/jak1/jak1_config.jsonc, decompiler/config/jak1/ntsc_v1/inputs.jsonc, decompiler/config/jak1_demo/default/inputs.jsonc, decompiler/config/jak2/jak2_config.jsonc, decompiler/config/jak2/ntsc_v1/inputs.jsonc, decompiler/config/jak3/jak3_config.jsonc, decompiler/config/jak3/ntsc_v1/inputs.jsonc, decompiler/decompilation_process.cpp, decompiler/decompilation_process.h, decompiler/extractor/main.cpp, decompiler/main.cpp
This centralizes the code that both `extractor` and the decompiler executes.  In the past this code was partially-duplicated, meaning that the `extractor` could only do _some_ operations and not others (ie. could not extract the audio files).
I also simplified the process to enable audio streaming in the configuration.  This is to support a new feature in the launcher that allows you to enable these options for the decompiler:
=> decompiler: Cleanup duplication in extractor/decompiler and make it easier to enable streamed audio ripping from CLI

goal_src/jak3/engine/target/flut/flut.gc, goal_src/jak3/engine/target/pilot-states.gc, goal_src/jak3/levels/desert/boss/terraformer-setup.gc, goal_src/jak3/levels/desert/chase/marauder.gc
Fixes a couple of NaN bugs, making the Arena and Marauder Stronghold missions, the leaper corralling mission and final boss playable:
- Fixes #3579:
- After catching a leaper, the `flut` that spawns would have a NaN `world-sphere`
- Fixes #3580:
- `vf0` was being clobbered after a `suspend`, causing them to spawn at the origin.
- The Terraformer's `world-sphere` would be NaN until an animation started playing.
=> jak3: fix some nan bugs

game/graphics/opengl_renderer/OpenGLRenderer.cpp
Logs the OpenGL vendor and renderer, in most cases this helps identify what GPU the game is using, which is something that comes up from time-to-time in support.
=> game: log more OpenGL info

common/util/fnv.h, game/graphics/opengl_renderer/EyeRenderer.cpp, game/graphics/opengl_renderer/EyeRenderer.h, game/graphics/opengl_renderer/foreground/Merc2.cpp, game/graphics/opengl_renderer/foreground/Merc2.h, game/overlord/jak3/iso_cd.cpp, goal_src/jak3/engine/gfx/foreground/eye.gc, goal_src/jak3/engine/gfx/texture/texture.gc
I found two issues with Jak 3 eyes. The first was simple - we were missing a `-pc` texture upload in `texture.gc` for `pris2` textures, which has eye textures for a few characters, like torn or damas. 
The second was a little more annoying. Unlike jak 2 and jak 1, jak 3 can dynamically assign eye slots when merc models are loaded. This involves modifying eye data to tell the eye renderer where to render, and modifying the merc model's adgif shaders to point to the correct eye texture. The modification to the merc adgif shader is problematic since our PC port of merc assumes this slot is constant.
My solution here was to bypass this whole slot system entirely for jak 3. I modified the GOAL eye renderer to tell the c++ eye renderer the name of the merc-ctrl containing the eye. Then, the PC …
=> [jak3] Fix eye slot assignment and textures

game/graphics/opengl_renderer/TextureUploadHandler.cpp, game/graphics/opengl_renderer/TextureUploadHandler.h, game/graphics/opengl_renderer/foreground/Generic2.cpp, game/graphics/opengl_renderer/foreground/Generic2.h, game/graphics/opengl_renderer/foreground/Generic2BucketRenderer.cpp, game/graphics/opengl_renderer/foreground/Generic2BucketRenderer.h, game/graphics/opengl_renderer/foreground/Merc2.cpp, game/graphics/opengl_renderer/foreground/Merc2.h, game/graphics/opengl_renderer/foreground/Merc2BucketRenderer.cpp, game/graphics/opengl_renderer/foreground/Merc2BucketRenderer.h, game/overlord/jak3/dvd_driver.cpp, goal_src/jak3/engine/common-obs/scene-actor.gc
A few minor fixes:
- Fix crash in overlord3 during final boss https://github.com/open-goal/jak-project/issues/3605
- Update goal_src for `scene-actor.gc`, which was not updated after a bug fix for decompiling skelgroups, making some cutscene actors invisible due to using the wrong joint for culling checks.
- Stop using `-1` as an invalid value for texture id's in Merc.cpp. This could sometimes cause Merc2.cpp to accidentally skip updating the OpenGL texture. This fixes the bug where skull gems sometimes didn't have the animated textures.
=> [jak3] A few bug fixes

goal_src/jak1/pc/progress-pc.gc
=> g/j1: fix menu labelling issue in jak1

decompiler/config/jak2/all-types.gc, decompiler/config/jak3/ntsc_v1/type_casts.jsonc, game/overlord/jak2/srpc.cpp, game/overlord/jak2/srpc.h, goal_src/jak1/engine/sound/gsound-h.gc, goal_src/jak1/pc/pckernel-h.gc, goal_src/jak1/pc/pckernel.gc, goal_src/jak2/engine/game/game-info.gc, goal_src/jak2/engine/game/settings.gc, goal_src/jak2/engine/gfx/math-camera.gc, goal_src/jak2/engine/sound/gsound-h.gc, goal_src/jak2/engine/sound/gsound.gc, goal_src/jak2/engine/target/target-turret.gc, goal_src/jak2/pc/pckernel.gc, test/decompiler/reference/jak2/engine/sound/gsound-h_REF.gc
Fixes #3210
TIL that on the PS4/PS5, mirror mode breaks the upscaling
=> jak2: support mirror mode

.github/workflows/build-matrix.yaml, .github/workflows/compiler-output-check.yaml, .gitignore, common/util/DgoWriter.cpp, out/jak1/fr3/.gitignore, out/jak1/iso/.gitignore, out/jak1/obj/.gitignore, out/jak2/fr3/.gitignore, out/jak2/iso/.gitignore, out/jak2/obj/.gitignore, out/jak3/fr3/.gitignore, out/jak3/iso/.gitignore, out/jak3/obj/.gitignore, scripts/gsrc/compare-compilation-outputs.py, scripts/gsrc/jak1-sprite-adjustments.py
=> ci: Add workflow that compares the compiled output between the PR and master

game/CMakeLists.txt, game/system/hid/display_manager.cpp, goal_src/jak1/pc/pckernel-common.gc, goal_src/jak1/pc/pckernel-h.gc
Also saves out the default `pc-settings.gc` file so it's less confusing _and_ so we can request it from users to actually see what it's doing.
The fix in the last release was only to fix bad `game-size` values when _loading_ the file.  But if you don't have a file, it picks a default.
Right now it picks that default by:
1. Your largest reported resolution
2. If that fails, the one that is currently set
In reality this scenario can never really happen (if you have a set resolution, it will be one of the reported ones).  However what can happen is for SDL to be misinformed by bad display/monitor drivers/the OS and be given "supported" resolutions that aren't actually supported.  For example some users have a 4K resolution as their highest, despite them using a 1080p monitor.
The solution is …
=> game: ensure the default `game-size` is also valid when initializing the `pc-settings.gc` file

.github/workflows/compiler-output-check.yaml, .gitignore
Mistake lead to CI failures for PRs that modified goal_src (of course the files are different than master!)
=> ci: compile with `master`'s `goalc`, but with the PR's changes

common/math/Vector.h, common/util/gltf_util.cpp, common/util/gltf_util.h, decompiler/level_extractor/merc_replacement.cpp, goalc/CMakeLists.txt, goalc/build_actor/common/MercExtract.cpp, goalc/build_actor/common/MercExtract.h, goalc/build_actor/common/animation_processing.cpp, goalc/build_actor/common/animation_processing.h, goalc/build_actor/jak1/build_actor.cpp, goalc/build_actor/jak1/build_actor.h, goalc/build_actor/main.cpp, goalc/build_level/common/build_level.cpp
This adds a feature to `build_actor` to support importing skeletons and animations from .glb files.
Multiple animations are handled and will use the name in the GLB. The default `viewer` process will end up playing back the first animation.
There are a few limitations:
- You can only have around 100 bones. It is technically possibly to have slightly more, but certain animations may fail to compress when there are more than ~100 bones.
- Currently, all animations have 60 keyframes per second. This is a higher quality than what is normally used. If animation size becomes problematic, we could make this customizable somehow.
- There is no support for the `align` bone.
=> [build_actor] Add skeleton and animation support

decompiler/level_extractor/extract_level.cpp, decompiler/level_extractor/fr3_to_gltf.cpp, decompiler/level_extractor/fr3_to_gltf.h
e.g. instead of just `beach-foreground.glb` and `beach-background.glb`, you'd now get:
- `beach/babak-lod0.glb`
- `beach/babak-lod1.glb`
- `beach/babak-lod2.glb`
- `beach/barrel-lod0.glb`
- `beach/beach-background.glb`
- `beach/beachcam-lod0.glb`
- ... (42 other files)
- `beach/windmill-one-lod2.glb`
`common` models are also grouped into their own folder
=> Extract merc models into individual glb files

goal_src/jak2/pc/features/autosplit-h.gc, goal_src/jak2/pc/features/autosplit.gc
Goes with https://github.com/open-goal/speedrunning/pull/21
Based on some of the autosplit points from the [comgold sheet](https://docs.google.com/spreadsheets/d/1ZtceX0ZxCLkufVFQuCgVxptvmVgp6deHwPYWxUPi258/edit?gid=0#gid=0), plus one after talking to samos to give a clean split for timing the deload.
```
(tomb-poles-poles uint8) ;; left tomb/daxter boulder start
(fortress-save-friends-introduction uint8) ;; talk to torn (before rescue friends)
(sewer-escort-get-gun uint8) ;; get peacemaker
(forest-protect-introduction uint8) ;; talk to onin (protect samos)
(forest-protect-meeting uint8) ;; talk to samos (protect samos)
```
=> Add more autosplit points for Jak 2 Any%

goal_src/jak3/engine/collide/collide-cache.gc, goal_src/jak3/engine/collide/collide-shape.gc
This is basically applying the same fix as `vector<-cspace!`, which we've been doing since jak 1.
They often make bugs where they use bones before they are properly initialized. On PS2, it's relatively harmless - it results in stuff going to the origin for 1 frame (where it collides with nothing, since the collide cache was filled somewhere else), then going back to normal.
On PC, using these uninitialized bones results in NaNs. This is because  `0 * (1 / w)`  where `w = 0` done in the `update-transforms` is `NaN` on PC, but 0 on PS2. These NaNs propagate to the velocity, and you get stuck with everything being NaN.
=> [jak3] Fix bomb bot bombs disappearing

decompiler/config/jak3/all-types.gc, decompiler/config/jak3/ntsc_v1/stack_structures.jsonc, goal_src/jak3/engine/physics/rigid-body.gc, test/decompiler/reference/jak3/engine/physics/rigid-body_REF.gc
Ended up being a simple fix to a stack type in rigid-body.
=> [jak3] Fix crash with volcano platforms

decompiler/config/jak3/all-types.gc, decompiler/config/jak3/ntsc_v1/label_types.jsonc, goal_src/jak3/engine/level/level.gc, goal_src/jak3/levels/desert/artifact-race/artifact-race.gc, goal_src/jak3/levels/temple/temple-obs2.gc, test/decompiler/reference/jak3/levels/desert/artifact-race/artifact-race_REF.gc, test/decompiler/reference/jak3/levels/temple/temple-obs2_REF.gc
- Fix global heap display in cheat mode
- Fix `tpl-watcher` NaNs after they fire their laser (`vf0` was being clobbered) (Fixes #3684)
- Fix `artifact-race` talkers (Fixes #3685)
=> jak3: misc fixes

game/graphics/opengl_renderer/loader/LoaderStages.cpp, game/kernel/common/kmachine.cpp, game/system/hid/display_manager.cpp, game/system/hid/display_manager.h, goal_src/jak1/kernel-defs.gc, goal_src/jak1/pc/progress-pc.gc, goal_src/jak2/kernel-defs.gc, goal_src/jak2/pc/progress/progress-draw-pc.gc, goal_src/jak2/pc/progress/progress-pc.gc, goal_src/jak3/kernel-defs.gc
I'll test this more thoroughly tomorrow, quick change to allow picking resolutions that would normally be filtered out, while in windowed mode.
=> game: dont filter resolutions in windowed mode

goal_src/jak1/engine/level/level.gc
Fixes #3644 which I believe is the same underlying issue as "NG+ glitch"
To reproduce the issue in #3644 you can:
- choose Hub 2 100% in the speedrun fast reset menu
- hit the blue sage warp gate switch
- go deep enough into any adjacent level (e.g. basin) where `village2` display is turned off
- reset speedrun in the fast reset menu
- tasks are reset but the switch will be pressed, giving the cutscene early
You can also grab orbs/scout flies in `village2`, and they won't be reset properly because of this same bug.
It happens because of the way entity perm status is managed across both `level` vs `game-info` objects.
- when `village2` is deactivated (still loaded but display hidden), its entity perms are copied to `game-info`'s `perm-list` 
- this is how we persist `warp-gate-switch-7` …
=> [jak1] Patch "NG+ glitch"

goal_src/jak3/engine/common-obs/projectile.gc, goal_src/jak3/engine/process-drawable/process-drawable.gc
Fix https://github.com/open-goal/jak-project/issues/3701, and possibly other issues where projectiles were invisible/messed up.  The use of `align16` with the -16 was subtracting 16 in cases when the pointer was already aligned, causing a bad value to be loaded for the quaternion.
I also renamed some variables and did some manual cleanup on a method in process-drawable, since this one comes up a lot during debugging.
=> [jak3] Fix flashing with maker projectiles

decompiler/level_extractor/extract_merc.cpp, game/graphics/opengl_renderer/shaders/emerc.frag, game/kernel/jak3/kscheme.cpp, goal_src/jak2/engine/gfx/foreground/foreground.gc, goal_src/jak3/engine/gfx/foreground/foreground.gc
Fix the envmap texture using the eye texture by default (will require a re-extract to fix), fix envmap strength in all three games being off by 2x. (oops)
With envmap scale fix:
without envmap scale fix (but with texture fix):
=> [jak3] fix envmap texture and strength

decompiler/level_extractor/extract_level.cpp, game/graphics/opengl_renderer/OpenGLRenderer.cpp
Fixes https://github.com/open-goal/jak-project/issues/3720.
The texture page and texture name appear multiple times with different IDs, meaning that we insert the texture with the wrong ID.  Fixed by using IDs for common_tpage textures.  Since this common_tpage feature is only used for minimap stuff, I don't think it can mess up texture animations.
=> [jak3] Fix target marker texture

game/graphics/opengl_renderer/shaders/sprite3_3d.vert, game/graphics/opengl_renderer/sprite/Sprite3.cpp, goal_src/jak3/levels/desert/rescue/neo-satellite.gc
Fixes issue with not handling texture flipping flags in sprite renderer (new jak 3 feature). As far as I can tell, there is no visible difference because the textures that use this flag are symmetric.
Fix issue with not adding an `and` with `0xf` on the offset into the xy table. This is added only in jak 3, where `vi07`'s upper bits are sometimes nonzero, but doesn't hurt to have in all three games.
```
iaddi vi09, vi00, 0xf      |  nop                      
iand vi07, vi07, vi09      |  nop  
```
Fix issue with inf/nan causing the tentacle to not appear:
=> [jak3] Fix neosat particles and tentacle

.gitignore, .vs/launch.vs.json, Taskfile.yml, game/graphics/gfx_test.cpp, game/graphics/gfx_test.h
This is so I can get rid of wgpu from the launcher, where it's only purpose is to figure out the GPU name for the support package.
The problem with it is that on some environments, it errors, but the function cannot have it's errors gracefully handled (it panics and crashes instead).
So I'm tired of it, do it ourselves.
=> game: Update game's GPU test to output the GPU vendor info

game/graphics/opengl_renderer/Shader.cpp, game/graphics/opengl_renderer/Shader.h, game/graphics/opengl_renderer/TextureAnimator.cpp, game/graphics/opengl_renderer/TextureAnimator.h, game/graphics/opengl_renderer/TextureAnimatorDefs.cpp, game/graphics/opengl_renderer/shaders/plain_texture.frag, game/graphics/opengl_renderer/shaders/plain_texture.vert
- fix issue where animated textures that use the size-override feature, and aren't being animated would show up as black - fix for black water in spargus
- fix issue where animated texture uses another animated texture as an input wouldn't get the animated version.
- fix math mistake in how animated texture rotations are handled. This could cause textures to not rotate when a positions were rotated, but textures (st's) weren't.
- fix definition of the ring texture to handle set-alpha-texture-anim-layer-func
https://github.com/user-attachments/assets/0242a59d-62bd-4799-8f6f-2a0aba63649f
=> [jak3] Misc texture anim fixes

common/custom_data/Tfrag3Data.h, decompiler/level_extractor/extract_tie.cpp, game/graphics/opengl_renderer/OpenGLRenderer.cpp, game/graphics/opengl_renderer/background/Tie3.cpp, game/graphics/opengl_renderer/background/Tie3.h
Support animated textures in TIE.  Apparently this is also used in jak 2 for robotank and we never noticed??
https://github.com/user-attachments/assets/bfa45a1a-4a96-4b25-817a-4327afcc7c98
=> [jak3] Support texture anim in TIE

common/CMakeLists.txt, common/util/gltf_util.cpp, common/util/image_resize.cpp, common/util/image_resize.h, goalc/build_level/common/color_quantization.cpp, goalc/build_level/common/gltf_mesh_extract.cpp, test/CMakeLists.txt, test/common/test_image_resize.cpp
- Bug fix to KD tree splitting, should fix cases with bad vertex colors/alphas.
- Normalize normals instead of asserting if they are the wrong length. **the fact that blender exports normals incorrectly is a bug and I doubt their implementation is correct if you've scaled things on only on axis.**
- Automatically resize metallic texture (envmap strength) if it doesn't match the size of the rgb texture instead of asserting
=> [custom levels] A few bug fixes

goal_src/jak2/pc/pckernel-impl.gc, goal_src/jak2/pc/pckernel.gc, goal_src/jak2/pc/progress/progress-static-pc.gc, goal_src/jak2/pc/subtitle2.gc
Re-uses the existing "hinttitles" toggle that's already there, and makes it not depend on if the main subtitles are on or not.
=> [jak2] Correct behavior of hint subtitles toggle

goal_src/jak2/engine/gfx/texture/texture-anim.gc
Since #3735, loading consite in Jak 2 crashes due to an assert in the code that handles the PC clut blender DMA. The unused and half-implemented `kor-transform` texture animation doesn't have any blenders as the texture names are commented out in the C++ definition (and it seems that these textures are defined multiple times within different tpages in the same DGO, leading to errors during startup if uncommented), leading to a mismatch between the actual qwc in GOAL and the assumed DMA data size in C++.
=> jak2: fix consite crash

decompiler/config/jak3/ntsc_v1/inputs.jsonc, decompiler/level_extractor/BspHeader.cpp, decompiler/level_extractor/extract_tie.cpp, goal_src/jak3/game.gp
It looks like one of the tie models in this level has bad color data in the lowest LOD. For now, just skip extracting the lowest lod for this TIE only.
=> [jak3] Fix for precd extraction

README.md
Homebrew has its own formula for go-task which is up-to-date and working.
=> docs: Remove instructions to add go-task tap to Homebrew.

game/graphics/opengl_renderer/shaders/sprite3_3d.vert
Fixes a regression in #3722.
```
[18:34] [error] Failed to compile vertex shader sprite3_3d:
ERROR: 0:122: '&' does not operate on 'unsigned int' and 'int'
ERROR: 0:129: Use of undeclared identifier 'xy0_vf19'
ERROR: 0:129: Use of undeclared identifier 'xy0_vf19'
ERROR: 0:144: '&' does not operate on 'unsigned int' and 'int'
ERROR: 0:151: Use of undeclared identifier 'xy0_vf19'
ERROR: 0:151: Use of undeclared identifier 'xy0_vf19'
```
=> Fix sprite3_3d.vert on macOS

common/dma/dma.h
DMA sizes are 16-bits, not 12-bits. This would cause rare crashes when the ocean far renderer uses more than this.
I'm not really sure what the ocean far rendering is doing at this time, but it happens as stuff is loading in.
There's a chance this fixes crashes in jak 2 as well, since we used to see errors that would be explained by this.
=> Fix crash in ocean-far with invalid DMA size

goal_src/jak2/levels/dig/dig-digger.gc
if you sideflip into grind in the digsite mission, the clasps wont break because it is considered a `board-spin` attack instead of `board`. This extends the condition to allow for `board-spin` as well.
~~Should I wrap this in an `#if PC_PORT`?~~ done
=> [jak2] Fix bug where spinning into grind doesnt break clasps in dig1

CMakeLists.txt, common/formatter/formatter_tree.cpp, game/graphics/opengl_renderer/debug_gui.cpp, game/graphics/opengl_renderer/foreground/Generic2_DMA.cpp, game/kernel/jak2/kmachine.cpp, game/kernel/jak3/kmachine.cpp, game/kernel/jak3/kmachine_extras.cpp, game/mips2c/jak3_functions/shadow.cpp, game/overlord/jak3/iso.cpp, game/overlord/jak3/rpc_interface.h, game/overlord/jak3/sbank.cpp, game/overlord/jak3/sbank.h, game/overlord/jak3/srpc.cpp, game/overlord/jak3/ssound.cpp, game/overlord/jak3/ssound.h, game/sound/sndshim.cpp, game/sound/sndshim.h
Fix compiler warnings, and a bug where the `snd_handle` of `SoundBankInfo` was never set, leading to sound banks never unloading.
The game relies on unloading soundbanks to make sure certain sounds don't play, like the blue gun 1 fire noise when using blue gun 2.
=> [jak3] Fix overlord soundbank unload, fix warnings

goal_src/jak3/game.gp, goal_src/jak3/levels/desert/desert-dust-storm.gc
Simple workaround to put an effect in a different bucket. I don't think there's a difference in the result, but this is just easier to handle on the PC renderer side.
=> [jak3] workaround for intro crash on screen filter

.github/workflows/build-matrix.yaml, .github/workflows/release-pipeline.yaml, CMakeLists.txt, CMakePresets.json, README.md, game/CMakeLists.txt
Create explicit x86_64 and ARM64 macOS build targets, so it's clear that the CI is building x86_64 binaries (on both Intel and ARM64 build machines). Also, use the `CMAKE_APPLE_SILICON_PROCESSOR` CMake variable (which sets `CMAKE_SYSTEM_PROCESSOR`) so `BUILD_X86_ON_MACOS` is not necessary.
And update the README.
=> Create separate x86_64 and ARM64 macOS targets.

decompiler/config/jak3/all-types.gc, goal_src/jak3/engine/physics/ragdoll-h.gc, goal_src/jak3/engine/physics/ragdoll.gc, goal_src/jak3/engine/target/flut/flut-racer.gc, goal_src/jak3/game.gp, test/decompiler/reference/jak3/engine/physics/ragdoll-h_REF.gc, test/decompiler/reference/jak3/engine/physics/ragdoll_REF.gc, test/decompiler/reference/jak3/levels/common/enemy/darkprec/dp-bipedal_REF.gc, test/decompiler/reference/jak3/levels/common/enemy/grunt_REF.gc
`none` methods strike again
Fixes #3774
=> jak3: fix ragdolls settling too early

.github/workflows/macos-build-arm.yaml, .github/workflows/macos-build.yaml
macOS 12 has been end of life for 2 months, GitHub is removing support for the images very soon (within a week or so).  
https://endoflife.date/macos
=> ci: update minimum macOS supported version to Ventura (13)

common/util/gltf_util.cpp, common/util/gltf_util.h, decompiler/level_extractor/merc_replacement.cpp, goalc/build_actor/common/MercExtract.cpp
When a material in Blender has its IOR level changed to anything other than the default value of 0.5, the `KHR_materials_specular` extension is applied during the glTF export, which is what we use to check for envmaps in custom models. If an envmap is undesired, but the IOR value was accidentally changed, the program would assert during model processing if there is no metallic roughness texture attached to the material.
Since this is an easy mistake to make and is hard to spot, this adds a better error message for such cases.
=> custom models: better error for invalid envmap material

game/kernel/jak1/kmachine.cpp, game/kernel/jak2/kmachine.cpp, game/kernel/jak3/kmachine.cpp
Several users have reported that ArchipelaGOAL is not launching properly, even when using the OpenGOAL Launcher. The window pops up with a black screen, and then quits. The only way they can run it is if they double click gk.exe. 
This comes down to the Launcher providing gk.exe with the `config_path` parameter, which leads the program to find `archipelagoal-settings.gc`. Here is an example from me:
```
D:\Applications\Games\OpenGOAL\features\jak1\mods\JakMods\_settings\archipelagoal\OpenGOAL\jak1\settings/Mods/archipelagoal-settings.gc
```
If a user's base OpenGOAL install directory is long enough, this path becomes longer than 128 characters. This overflows the character buffer in `kopen` which is used to open file streams. If you're only slightly over the limit like myself, at 135 …
=> Remove 128 character buffer causing long filenames to crash gk

common/util/gltf_util.cpp, common/util/gltf_util.h, decompiler/level_extractor/merc_replacement.cpp, goalc/build_actor/common/MercExtract.cpp
If a model has a material with specular properties, but is missing a roughness texture, warn and treat it as a normal draw instead of erroring out.
=> custom models: ignore invalid envmap material

.github/workflows/release-pipeline.yaml
Folder names were in common with the normal intel x86 build, the release wasn't going to work.  Hopefully with these changes it will but, still technically untested.  Don't have time to do so tonight.
=> ci: hopefully fix MacOS CI in preparation for release

decompiler/level_extractor/extract_level.cpp, decompiler/level_extractor/extract_level.h, decompiler/level_extractor/extract_merc.cpp, decompiler/level_extractor/extract_merc.h, decompiler/level_extractor/merc_replacement.cpp, goalc/build_level/jak1/build_level.cpp, goalc/build_level/jak2/build_level.cpp, goalc/build_level/jak3/build_level.cpp
Store a small database of which models have already been swapped out in a level to prevent duplicate processing.
Also a small fix for cases where using a model replacement that has no armature would cause merc nightmares due to only having a `max_bones` of 3.
=> model replacements: prevent duplicate processing

game/sound/989snd/blocksound_handler.cpp, game/sound/989snd/blocksound_handler.h, game/sound/989snd/musicbank.cpp, game/sound/989snd/musicbank.h, game/sound/989snd/player.cpp, game/sound/989snd/player.h, game/sound/989snd/sfxblock.cpp, game/sound/989snd/sfxblock.h, game/sound/989snd/sfxgrain.cpp, game/sound/989snd/sndplay.cpp, game/sound/989snd/sound_handler.h, game/sound/989snd/soundbank.h
Add instance limits to the sound library, and a `dump-info` command to `sndplay` to print out all the sounds/flags in an SBK file. 
This is based on the decompiled 989snd library @Ziemas is working on (https://github.com/Ziemas/dec989snd/blob/main/src/sndhand.c#L77)
=> [sound] Add instance limits

game/graphics/opengl_renderer/debug_gui.cpp
Should cover edge cases where the bar is displayed and a keyboard type device is not connected to the system (Steam deck/touch input based device instead).
While it should probably be impossible to display the bar in the first place on such devices it apparently isnt -> https://www.reddit.com/r/jakanddaxter/comments/1h4mht1/how_to_remove_grey_bar_at_top_on_steamdeck/
And even ignoring the whole steamdeck/no keyboard thing adding another way to hide it that is visible on the bar should help reduce people asking about how to hide it. (And hopefully help people who dont ask/dont know where to ask!)
https://github.com/user-attachments/assets/7f132781-675c-451e-8b39-2a78fa098b9e
=> Add option to hide the imgui bar with a click event

goalc/build_actor/common/MercExtract.cpp, goalc/build_actor/common/animation_processing.cpp
Fixes the issue with animations doing a full 180 degree rotation and disappearing.  The quaternions in the GLB export "flip", and when interpolating animation frames in between a flip, we got bogus quaternions.
Fixes https://github.com/open-goal/jak-project/issues/3786
Also fix a crash in `goalc` when using merc models without any materials.
=> Fix animation processing interpolation bug, crash on no merc material

goalc/build_level/common/color_quantization.cpp, goalc/build_level/common/gltf_mesh_extract.cpp
A few improvements to color palette selection. These were made by tracing some particularly bad colors through and seeing where it made obviously bad decisions for splitting. I tested on crystal cave, and a test GLBs from Kuitar that previously had issues with alpha.
- The previous approach to splitting was based on trying to keep a tree of deduplicated colors balanced (same count in each leaf). This is not really a good idea for generating color palettes. A better approach is to try to minimize the volume of the child node, limiting how inaccurate a color can be. Splitting is now chosen based on the average of the _deduplicated channel values_, which in practice seems to work pretty well for Kuitar's levels. Other approaches could work here too.
- The previous approach of alternating …
=> [Custom Levels] Improve color palette generation

common/util/gltf_util.cpp, common/util/gltf_util.h, custom_assets/blender_plugins/opengoal.py, decompiler/IR2/FormExpressionAnalysis.cpp, decompiler/level_extractor/extract_level.cpp, decompiler/level_extractor/extract_level.h, decompiler/level_extractor/extract_merc.cpp, decompiler/level_extractor/merc_replacement.cpp, decompiler/level_extractor/merc_replacement.h, game/graphics/opengl_renderer/foreground/Merc2.cpp, goalc/build_actor/common/MercExtract.cpp, goalc/build_actor/common/MercExtract.h
Two new flags were added to the Blender plugin to allow reusing the mod and/or eye draws of the original model that is being replaced. Works pretty well for eyes, but the blerc draws can cause some Z-fighting with the non-moving parts of the model.
Also a small refactor to the merc replacement code to de-duplicate some code by moving stuff to `gltf_util.cpp`.
=> custom models: option to copy mod/eye draws from original model

goalc/build_actor/common/animation_processing.cpp
Fix a missing scale factor when using the large mode in the animation compressor. This would make some joints have a translation of near 0 if the original animation had stuff moving a large distance
=> custom actor, fix animation compression

game/overlord/jak3/dma.cpp, game/overlord/jak3/iso.cpp
Change jak 3 SPU DMA to run the interrupt handler "immediately" (or at least before `DMA_SendToSPUAndSync` returns). 
This fixes an issue where audio can hang during fast cutscene playback. I'm hoping it fixes more issues with looping/stuck audio as well, but this needs more testing.
I originally wanted to do it this way, but thought that it didn't work - from Jak 2 it seemed like things broke if the DMA was too fast. But, at least for Jak 3, everything seems to work like this. This will remove a huge source of non-deterministic timing in audio stuff and hopefully make things easier to debug. It also means that a large portion of streaming audio code will never have to run - from the game's point of view there's always the next SPU buffer available.
If this works well, I might revisit jak …
=> [Jak3] Adjust overlord SPU dma to avoid audio hangs

game/overlord/jak3/stream.cpp
Accidentally incrementing `s` twice in the loop, so queued streams in slot 1, and 3 were skipped by the overlord.
This would usually cause the audio to never start playing because the game would wait for the audio to successfully get queued.
=> [jak3] Fix issue where some vag streams never queue

game/graphics/opengl_renderer/debug_gui.cpp, game/graphics/opengl_renderer/debug_gui.h, game/overlord/jak3/dma.cpp, game/overlord/jak3/dma.h, goal_src/jak3/pc/pckernel.gc
In Jak 3, the default PC settings file would have a language of 255 because it runs before the first settings update. This would cause the game to crash the second time it is started.
I also added this simple imgui window to see the names of streams in the "SPU" memory, which has been useful for debugging
=> [jak3] Avoid language 255 issue

game/graphics/opengl_renderer/background/background_common.cpp, game/graphics/opengl_renderer/shaders/hfrag.vert, game/graphics/opengl_renderer/shaders/merc2.vert, game/graphics/opengl_renderer/shaders/shrub.vert, game/graphics/opengl_renderer/shaders/tfrag3.vert
I finally went through and worked out the math for the camera matrix, and improved how it works for PC rendering. I was able to finally avoid the double perspective divide issue, which I always thought would cause accuracy issues.
This will help tfrag, tie (no envmap), shrub, and hfrag have less z-fighting in cases where the camera and the thing you're looking at are pretty close, but the entire level is far from the origin - like jak 3 temple.  I was able to modify the camera matrix so we don't have to do all the weird scaling/addition in the shader. 
Here's a screenshot from the temple oracle checkpoint, cropped from 4k. This used to have a lot of fighting issues.
It doesn't help issues where the thing you're looking at is very far away (jak 1 mountains, some jak 2 city stuff). It also …
=> [graphics] Improve some camera math

game/kernel/common/kprint.cpp, game/kernel/common/kprint.h, game/kernel/jak1/kprint.cpp, game/kernel/jak2/kprint.cpp, game/kernel/jak3/kprint.cpp
This should fix the crash when entering the freedom HQ elevator. It was caused by a large number of prints, one for each process in the city being killed by `check-for-rougue-process`, which would overflow the print buffer. So I increased the print buffer. 
Detecting buffer overflow here is hard because lots of things are allowed to write to it, including  the user's GOAL print methods. I added a basic check that will assert when there's 1k or less space in the buffer. It won't catch every overflow, but it would have caught this one.
=> [gk] Increase print buffer, add size check

game/mips2c/mips2c_private.h
Kind of silly fix.
The cloth update function sometimes runs before the "setup" is done (`need-setup` is set), which divides by zero in a bunch of places. This fix prevents NaNs from spreading during this time.
=> [jak3] Fix cloth nans

goal_src/jak2/engine/gfx/background/background.gc, goal_src/jak3/engine/gfx/background/background.gc
There's a feature to draw levels with a different camera matrix. This uses `camera-temp-other`, `camera-rot-other`, etc instead of `camera-temp`, `camera-rot`...  I assumed that  `trans-other`  was the "other" version of `trans`, but it turns out this isn't true - `trans-other` is combined with `quat-other` and the original camera matrix.
This fixes the issue by using the translation part of `inv-camera-rot-other` for othercam levels only. (it works in all cases, but I didn't want to use it for normal levels since I think it will be less accurate)
=> Fix camera-other

common/custom_data/TFrag3Data.cpp, game/graphics/opengl_renderer/shaders/etie.vert
A few people in the discord noticed that the shiny part of the subrails looks different between PS2 and OpenGOAL. I looked into this and found a bug where the length of the normals was half what they should have been. Earlier this didn't matter because I normalized them in the shader, but at some point I removed that when refactoring other parts.
I'm not completely convinced we have the intensity/tint multiplier working correctly, but this is at least a step in the right direction. 
https://github.com/user-attachments/assets/ee754011-08ac-4bee-94b2-d0e114b952ec
https://github.com/user-attachments/assets/1079635a-0b92-4965-a991-972ef6048ddf
For fun, here's this fix, plus a random doubling of the envmap effect strength:
https://github.com/user-attachments/assets/726e7b8d-c020-42cf-a594-cad59 …
=> [graphics] Fix issue with envmap math

.clang-format, .github/workflows/compiler-output-check.yaml, .github/workflows/inform-pages-repo.yaml, .github/workflows/linting.yaml, .github/workflows/linux-build-clang.yaml, .github/workflows/linux-build-gcc.yaml, common/formatter/formatter_tree.h, common/global_profiler/GlobalProfiler.h, common/goos/TextDB.h, common/repl/config.h, decompiler/config/jak3/ntsc_v1/type_casts.jsonc, decompiler/config/jak3/ntsc_v1/var_names.jsonc, decompiler/util/data_decompile.h, game/system/hid/devices/input_device.h, game/system/hid/devices/keyboard.h, game/system/hid/devices/mouse.h, game/system/hid/input_bindings.h, lsp/protocol/common_types.h, lsp/state/workspace.cpp, lsp/state/workspace.h, test/offline/framework/file_management.h, test/offline/framework/orchestration.h
Ubuntu 20.04 is hitting it's next EOL stage in april https://endoflife.date/ubuntu
And it's being removed from github actions in april to go along with that https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/
Getting ahead of this before we have random failures, I'll update the launcher along with this change for this month.
On the bright side, we can finally update clang-format!
=> ci: update to ubuntu `22.04`

goalc/build_actor/jak1/build_actor.cpp, goalc/build_actor/jak1/build_actor.h, goalc/build_actor/jak2/build_actor.cpp, goalc/build_actor/jak2/build_actor.h, goalc/build_actor/jak3/build_actor.cpp, goalc/build_actor/jak3/build_actor.h
Because merc effects for custom models would always have the `envmap-usage` flag set, this would also set the `ignore-alpha` flag, making transparency effects not work. Now the envmap flag is only set when the effect actually has an envmap.
=> build-actor: fix merc transparency

common/util/gltf_util.cpp, common/util/gltf_util.h
I fixed this for the only up mod awhile back and forgot to PR it here. 
Some related discussion [here](https://discord.com/channels/756287461377703987/995787558816595968/1320482071583522878) where we realized Blender automatically "renames" the textures, but then the GLB export doesn't reflect those renames
=> Dedupe custom level textures by height/width/data, not just name

.vs/launch.vs.json, goalc/build_level/jak1/build_level.cpp
Follow-up later on improving the validation of the extractor (that may require testing with all iso versions), but this is just some simple safe-guarding code that will improve the error messaging, instead of just a vague invalid map error.
=> goalc: don't assume DGO/CGOs are within the ObjectDB when building levels

goal_src/jak1/engine/game/main.gc, goal_src/jak1/pc/features/speedruns-h.gc, goal_src/jak1/pc/features/speedruns.gc
Fixed up a few things for speedrun mode in Jak 1:
- Changed autosplitter to start run in line with ruleset (first frame after blackout where jak is touching ground). Also tweaked the verification text in bottom left to show "Run Started: Yes/No" to go with this
- Changed speedrun menu button combo to match Jak 2/3 (only need to hold L1+R1 and press Start/Select, no longer need to hold X)
- Treat speedrun menu via Select the same as Start (no more potential for funny pause buffer where actors freeze)
warp gate example:
already grounded example (run starts once partially out of blackout):
=> [jak1] Speedrun mode misc fixes

goal_src/jak2/pc/pckernel.gc, goal_src/jak2/pc/progress/progress-static-pc.gc
Fixes #3906
Wasn't an issue on Jak 1 because that game had no original subtitles, but jak 2's subtitles still go through their original code, which uses the `*setting-control*` object.  This is a regression from when i recently added all languages to the menu options.
- Update the setting at runtime
- Update the setting at initialization time
This may be an issue in Jak 3 as well if the code was copied over.  We'll fix it when we get there.
=> g/j2: change and initialize jak 2 subtitles correctly

common/serialization/subtitles/subtitles_v2.h, goal_src/jak2/engine/scene/scene.gc, goal_src/jak2/pc/pckernel.gc
Fixes #3909 
Long standing issue in Jak 2's subtitles, it's actually kinda incredible that finnish didn't run into this problem.  Later in this code it accesses the subtitle based on the language-id, and finnish is always out of bounds -- but it never caused a catastrophic issue.
Polish on the otherhand is much more out of bounds and always causes an access violation / crash.
Jak 2's subtitle code has no fallback (ie. use english if not translated) for cutscenes, since they are not defined in the base file like in Jak 1.  This means that an untranslated language will render no subtitles during cutscenes.  Translations are welcome!.
Tested a cutscene in:
- english 
- italian (base game with subtitles)
- finnish (new language, actually is translated)
- polish (new language, not translated)
=> g/jak2: don't try to print subtitles that don't exist (non-base language)

game/graphics/pipelines/opengl.cpp, game/system/hid/devices/game_controller.cpp
For dualsense controllers, when the game exits we explicitly clear any trigger effects.  This was happening after SDL was already terminated, so the hardware handles were already lost.
From a practical standpoint though, this mostly just cleans up logs.
=> game: ensure SDL subsystems are cleaned up prior to quitting SDL

game/assets/jak2/subtitle/subtitle_lines_en-US.json
=> Fixed typo in US English subs.

.github/workflows/build-matrix.yaml, .github/workflows/macos-build-arm.yaml, .github/workflows/macos-build.yaml, CMakeLists.txt
libidn2 which is a potential part of libcurl seemingly slipped into the latest release (0.2.25) and it was dynamically linked.
This causes issues:
```
dyld[95648]: Library not loaded: /usr/local/opt/libidn2/lib/libidn2.0.dylib
Referenced from: <9DA6EC1D-F99A-3233-8264-AAEA87F07743> /Users/tyler/Downloads/opengoal-macos-arm-v0.2.25/gk
Reason: tried: '/usr/local/opt/libidn2/lib/libidn2.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libidn2/lib/libidn2.0.dylib' (no such file), '/usr/local/opt/libidn2/lib/libidn2.0.dylib' (no such file)
zsh: abort      ./g
```
My theory for why is that the underlying image changed (now has this library) and so the cmake detected that and started building with it.
The simple fix is to just disable it, as we don't need it.  If we …
=> macos: fix dynamically linked library in static release

game/kernel/common/kmachine.cpp, game/system/hid/display_manager.cpp, game/system/hid/display_manager.h, goal_src/jak1/kernel-defs.gc, goal_src/jak1/pc/debug/default-menu-pc.gc, goal_src/jak1/pc/progress-pc.gc, goal_src/jak2/kernel-defs.gc, goal_src/jak2/pc/debug/default-menu-pc.gc, goal_src/jak2/pc/progress/progress-static-pc.gc, goal_src/jak3/kernel-defs.gc, goal_src/jak3/pc/debug/default-menu-pc.gc, goal_src/jak3/pc/progress/progress-static-pc.gc
Prior to SDL3, borderless windows were kinda a hack, they cleaned all of that up.  The side-effect of that is that the C++ code keeps track of the current window size (it does this for framebuffer sizing, but also to set the size of the window).
This is now an issue because SDL is properly firing events when you change to borderless mode, so our window size gets updated to the size of the entire monitor.  When you switch to windowed mode from borderless, it now seems like it didn't work (it did, its just still taking up the entire screen).
This could be better cleaned up if more settings are extracted out of GOAL and put into C++ so they can be managed and accessed where they belong.  But for now, this is a minimally invasive fix.
Fixes #3917
=> Properly set window size when switching from borderless/fullscreen -> windowed mode

game/graphics/opengl_renderer/foreground/Shadow2.cpp, game/mips2c/jak2_functions/shadow.cpp, game/mips2c/jak3_functions/shadow.cpp
When the `dp-bipedal`s get blown up by the nuke gun, their bones go to NaNs on the last frame. The shadow renderer doesn't handle this well and draws all possible triangles as single tris. This overflows the vif `unpack` field and triggered an assert when sizes inside the shadow renderer weren't consistent.
My guess is that this works on the real game either because:
- their shadow renderer draws garbage data, but you can't tell because the screen is white from the nuke
- no NaN on PS2 means that the shadow renderer behaved differently, not using all single tris.
As a workaround, if the bones are NaN, the shadow renderer treats them as 0, meaning there is no shadow drawn.
=> [jak3] Fix crash with shadow in precursor ship

common/util/read_iso_file.cpp, decompiler/extractor/extractor_util.cpp
Fix bug where files starting past 2^32 bytes were not extracted correctly.
=> [extractor] Fix ISO extraction bug.

goal_src/jak3/levels/desert/chase/desert-chase.gc, goal_src/jak3/levels/desert/hover/scorpion-gun.gc
This needs a parameter, otherwise it was reading some uninitialized value. In some cases, the uninitialized value would leave the nav stuff on, and the marauders would go crazy trying to avoid each other.
=> [jak3] Fix disabling nav

game/graphics/gfx.h, game/graphics/opengl_renderer/OpenGLRenderer.h, goal_src/jak1/pc/pckernel-h.gc
There's a suspicion that MSAA might be what causes the black screen problem for some users, additionally this can cause perf issues for people with really bad PCs so this is probably a better default.
Needs testing before merging, i think this is all inclusive though.
=> game: default MSAA to off

.vs/launch.vs.json, custom_assets/jak2/levels/test-zone/test-zone.jsonc, custom_assets/jak2/levels/test-zone/testzone.gd, custom_assets/jak3/levels/test-zone/test-zone.jsonc, custom_assets/jak3/levels/test-zone/testzone.gd, decompiler/level_extractor/extract_merc.cpp, goalc/build_level/jak2/build_level.cpp, goalc/build_level/jak3/build_level.cpp
I discovered that `yakow`s are kinda broken if you try to use them in custom levels in jak 2/3. 
It's due to the missing `yakow-lod0` texture and associated fix, replacing it with `yak-medfur-end`. This solution works fine for the decompiler on vanilla levels. 
But for building custom levels, the requested art-groups were being handled before the textures were, and so it was impossible to have `yak-medfur-end` on hand to do the replacement. You'd hit an exception here because `idx_in_level_texture` would still be `INT32_MAX`:
https://github.com/open-goal/jak-project/blob/c08118509b84feba002bd9e208f49162b4218556/decompiler/level_extractor/extract_merc.cpp#L806
My fix was just to swap the order when building custom levels, and handle the textures first. I only made the changes for jak2/3, …
=> [jak2/3] Support yakows in custom levels

game/graphics/opengl_renderer/EyeRenderer.cpp, game/graphics/opengl_renderer/EyeRenderer.h, game/graphics/texture/TexturePool.h
When building the eye texture, the background is first set to the top corner of the iris texture.
A long, long time ago, I implemented this by peeking at the data in the texture itself. This doesn't work if the iris texture is animated since the texture will only on the GPU.
To fix this, this PR changes the eye renderer to draw a square over the entire eye texture using iris texture's top corner, avoiding the need for getting the texture data on the CPU. I don't remember why I didn't do this in the first place, but this seems better in every way.
Also `input_data` in TexturePool not being initialized, which was leading to hard-to-debug crashes when it was randomly initialized to a sometimes invalid but non-null pointer.
=> [gfx] Fix eye-related crash, clear color logic

game/mips2c/jak2_functions/collide_hash.cpp
Fixes #3151 by applying the same fix as #2686 to another Mips2C function.
Tested by mashing Jak's body into the bad collision walls for 30 minutes without a single crash.
=> [jak2] Fix Fortress Crash by Patching Mips2C Function

goal_src/jak1/engine/ui/text.gc, goal_src/jak2/engine/ui/text.gc, goal_src/jak3/engine/ui/text.gc
The main bug this fixes is not being able to use level select when your language isn't translated.  Why? Because they use the result from `lookup-text!` to determine if a menu item should be drawn or not.  No text found, no menu item.
However this uncovered a long-standing bug in my fallback extension to this code.  If you call this function with a text-id that doesnt even have an english string, it will recursively keep calling itself until it crashes.  Of course the first few tasks in the game are dummies and have no valid text-id so this had to be fixed.
Should be fixed for all 3 games.
=> game: fix level select for untranslated languages and fix infinite recursion edge-case in `lookup-text!`

game/system/hid/display_manager.cpp, game/system/hid/display_manager.h
Some monitors are very specific about their reported refresh rates:
```
[54:37] [debug] [DISPLAY]: Skipping 640x480 as it requires 360.11hz but the monitor is currently set to 360hz
```
The current code truncated the display mode, but would compare against the reported refresh rate.  As per the log, they are obviously not equal.
- Retain the float component and only round it off when sending the value to GOAL
- Make the comparison more generous, +/- 1.0hz
=> display: be more generous when filtering resolutions by refresh rate

game/graphics/opengl_renderer/OpenGLRenderer.cpp, game/graphics/opengl_renderer/OpenGLRenderer.h
Taking the suggestion from @Calinou (https://github.com/open-goal/jak-project/pull/3943#issuecomment-3017359144), this replaces the resolve/render framebuffer -> window framebuffer blit with an actual drawn tri-strip which covers the entire viewport, which the PCRTC blackout already does.
It appears we have no guarantee what state the internal window framebuffer will be in, so drawing an actual primitive and letting the fragment shader do all the work seems to be the more compatible/functional solution here.
Thanks for the suggestion!
=> Replace PCRTC framebuffer blit with screen quad draw

game/overlord/common/fake_iso.cpp, third-party/filesystem.hpp
The context for this is that i was symlinking files from a mod installation that were identical to the unmodded game, for space considerations, because i remembered having success with that in the past, before the project made the switch to ghc's filesystem library, it seems. <sub>(I was also much more pressed for space back then, but well, i thought writing a small program to check for matches and link them for me would be a good, not-so-difficult exercise...)</sub>
However i quickly started getting weird errors that it couldn't find GAME.CGO or KERNEL.CGO even when i hadn't touched them. Initially since i found that it occurred only when symlinking any files that were earlier alphabetically, i assumed it was some kind of index mismatch, but it was actually caused by a bug in an older …
=> Update filesystem.hpp dependency and un-break symlinks

game/graphics/texture/jak1_tpage_dir.h, goal_src/jak3/levels/desert/des-bush.gc, goal_src/jak3/levels/wascity/defend/was-pre-game.gc
Fixes #3997: The script for the orb that is spawned when getting a medal in the satellite game was using the wrong entity name.
Fixes #3998: The `spider-manager` process was invalid for one frame, causing the score to be set to the value of `#f`, winning the game instantly.
Also doubled the PC port texture count, which should hopefully fix the crash that happens when playing the game all the way through to the end of the Destroy Dark Eco Tanks mission in one sitting.
=> jak3: fix `was-pre-game` crash and `egg-spider` bbush

.github/workflows/macos-build-arm.yaml, .github/workflows/macos-build.yaml
Something has changed, hopefully the system installed cmake plays nice
=> ci: don't explicitly install `cmake` anymore for macOS builds

goal_src/jak2/pc/progress/progress-static-pc.gc
Fixes #4023 
This fixes a duplicated entry in the Jak 2 keybind details page where
"Right Analog Stick Left" appears twice.
File: goal_src/jak2/pc/progress/progress-static-pc.gc
Change: corrected the :entries list to include r-analog-right once
and removed the duplicate r-analog-left, resulting in the 8 expected
analog directions (L and R sticks).
Repro: Options → Input → Reassign Binds → Keyboard (Jak 2)
Before: Right stick shows duplicate "Left"
After: Right stick shows Left/Right correctly
=> jak2: progress: fix duplicate "Right Analog Stick Left" in keybind list

goal_src/jak1/pc/features/autosplit.gc
Not sure if/how this ever worked. The old code splits if you mark the task complete from the debug menu, but not from normal gameplay. 
`autosplit-flag-task-complete!` checks if the `task-perm-list` has the `real-complete` flag. Other than the debug menu and couple special cases, it looks like `task-perm-list` entries only get marked `real-complete` here when we get a fuel-cell
https://github.com/open-goal/jak-project/blob/aad1b53ce31ab0ef4c20ad7f6311cdda84f5c2bf/goal_src/jak1/engine/game/game-info.gc#L287-L300
Fixes one of the issues in #4021
=> [jak1] Fix lavatube oranges autosplit

decompiler/config/jak3/all-types.gc, decompiler/config/jak3/ntsc_v1/type_casts.jsonc, game/graphics/opengl_renderer/BlitDisplays.cpp, game/graphics/opengl_renderer/BlitDisplays.h, game/graphics/opengl_renderer/DirectRenderer.cpp, game/graphics/opengl_renderer/OpenGLRenderer.cpp, game/graphics/opengl_renderer/OpenGLRenderer.h, game/graphics/opengl_renderer/Shader.cpp, game/graphics/opengl_renderer/Shader.h, game/graphics/opengl_renderer/opengl_utils.cpp, game/graphics/opengl_renderer/opengl_utils.h, game/graphics/opengl_renderer/shaders/simple_texture.frag, game/graphics/opengl_renderer/shaders/simple_texture.vert, goal_src/jak3/engine/gfx/background/subdivide.gc, goal_src/jak3/engine/gfx/blit-displays-h.gc, goal_src/jak3/engine/gfx/blit-displays.gc, goal_src/jak3/engine/gfx/foreground/foreground.gc, goal_src/jak3/engine/gfx/hw/display-h.gc, goal_src/jak3/engine/gfx/sky/sky-tng.gc, goal_src/jak3/engine/gfx/vu1-user-h.gc, test/decompiler/reference/jak3/engine/anim/aligner-h_REF.gc, test/decompiler/reference/jak3/engine/gfx/background/subdivide_REF.gc, test/decompiler/reference/jak3/engine/gfx/blit-displays-h_REF.gc, test/decompiler/reference/jak3/engine/gfx/blit-displays_REF.gc, test/decompiler/reference/jak3/engine/gfx/foreground/foreground_REF.gc, test/decompiler/reference/jak3/engine/gfx/hw/display-h_REF.gc, test/decompiler/reference/jak3/engine/gfx/sky/sky-tng_REF.gc
Add the zoom blur effect, used by cutscene effects and a few weapons:
https://github.com/user-attachments/assets/8d231b34-faf8-4b88-a636-edf2b5477ff9
And color filtering
https://github.com/user-attachments/assets/67db5933-4b29-4c77-ad56-5025cbefa328
There's still two blit-displays not covered: scanlines and the light jak slow motion effect.
=> [jak3] Add zoom blur and color filter effect

game/graphics/opengl_renderer/TextureAnimatorDefs.cpp, goal_src/jak3/engine/draw/drawable.gc, goal_src/jak3/engine/gfx/ocean/ocean-mid.gc, goal_src/jak3/engine/gfx/ocean/ocean-transition.gc
Fix textures on the bomb (just a simple typo fix):
Fix issue with ocean culling when in the war factory. In this level, the make the background rotate by defining a different camera matrix. We need to use that matrix when culling the ocean, since it rotates too. This is different on PC because the original game stashed the camera frustum planes in some vf registers for background drawing.
=> [jak3] fix bomb and war factory ocean culling
